### PR TITLE
UNDERTOW-375 Using separate indices for filters mapped by servlet name a...

### PR DESCRIPTION
**Pull request by dankelleher**
...nd url pattern.

I am thinking these indices may belong in DeploymentInfo, it seems strange to store the indices in a location different to the collections they reference. If they were in DeploymentInfo we could also just use filterUrlMappings.size()?

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
**Windows** [Build 946](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=34488&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 299e8cc8544f3a9218c9bcdfdcbf63188afdf47a

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1382](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=34492&buildTypeId=UT_MASTER_LINUX) is now running using a merge of 299e8cc8544f3a9218c9bcdfdcbf63188afdf47a

**Comment by undertow-pull-request** [comment]
**Windows** [Build 946](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=34488&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 299e8cc8544f3a9218c9bcdfdcbf63188afdf47a
Summary: Tests failed: 2 (1 new), passed: 3129, ignored: 369 Build time: 0:12:52
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.handlers.proxy.LoadBalancingProxySPDYTestCase.testStickySessions{proxy}{http2-clear}: java.lang.AssertionError: expected:<200> but was:<503>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)

io.undertow.server.handlers.HttpContinueAcceptingHandlerTestCase.testHttpContinueRejected{proxy}{http2}: org.apache.http.NoHttpResponseException: The target server failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:95)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:61)

```

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1382](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=34492&buildTypeId=UT_MASTER_LINUX) outcome was **FAILURE** using a merge of 299e8cc8544f3a9218c9bcdfdcbf63188afdf47a
Summary: Tests failed: 3 (1 new), passed: 3206, ignored: 292 Build time: 0:14:03
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.handlers.HttpContinueAcceptingHandlerTestCase.testHttpContinueRejected{proxy}{http2}: org.apache.http.NoHttpResponseException: The target server failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:95)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:61)

io.undertow.server.handlers.HttpContinueAcceptingHandlerTestCase.testHttpContinueRejected{proxy}{https}: java.lang.RuntimeException: Buffer Leak io.undertow.server.handlers.HttpContinueAcceptingHandlerTestCase.testHttpContinueRejected{proxy}{https}
	at io.undertow.testutils.DefaultServer$1.testFinished(DefaultServer.java:259)
	at org.junit.runner.notification.RunNotifier$7.notifyListener(RunNotifier.java:191)

io.undertow.server.handlers.HttpContinueConduitWrappingHandlerTestCase.testHttpContinueRejected{proxy}{http2}: org.apache.http.NoHttpResponseException: The target server failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:95)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:61)

```

**Comment by stuartwdouglas** [comment]
The reason why these are located in separate places is because the ServletContext add methods need to add to the start of the filters list, however after any other filters added by the ServletContext methods (as these methods are intended to be used by ServletContainerInitialisers and ServletContextListeners).

**Pull request merged**
