### PR TITLE
 UNDERTOW-1534 HTTP/2 can enter an infinite loop

### PR DESCRIPTION
**Pull request by stuartwdouglas**
Also re-enables the sender test case to see if this is the root cause

### CODE REVIEW

**Comment by gaol** [comment]
Are the test failures related? It failed again after I triggered.

**Comment by fl4via** [comment]
Retest this please

**Comment by gaol** [comment]
https://issues.jboss.org/browse/JBEAP-16855 got verified using this patch, so it looks good.

**Comment by uherberg** [comment]
I can't see the detailed description of this error (some permission issue), but we also see an infinite loop. I am hoping this will fix that.

**Comment by stuartwdouglas** [comment]
Retest this please

**Comment by stuartwdouglas** [comment]
Retest this please

**Pull request merged**
