### PR TITLE
[UNDERTOW-1837] ServletRequest#getLocalPort(), getLocalAddr() and get…

### PR DESCRIPTION
**Pull request by moulalis**
Issue: https://issues.redhat.com/browse/UNDERTOW-1837
JBEAP Issue: https://issues.redhat.com/browse/JBEAP-20907
2.0.x PR :https://github.com/undertow-io/undertow/pull/1045
2.1.x PR: https://github.com/undertow-io/undertow/pull/1046

### CODE REVIEW

**Comment by fl4via** [comment]
@moulalis  can you please check the following failures?
https://github.com/undertow-io/undertow/pull/1044/checks?check_run_id=2002486404
https://github.com/undertow-io/undertow/pull/1044/checks?check_run_id=2002486429
https://github.com/undertow-io/undertow/pull/1044/checks?check_run_id=2002486571
https://github.com/undertow-io/undertow/pull/1044/checks?check_run_id=2002486607
https://github.com/undertow-io/undertow/pull/1044/checks?check_run_id=2002485978
https://github.com/undertow-io/undertow/pull/1044/checks?check_run_id=2002486020
Even though the CI is not stable and we do have to cope with some test failures in the PRs (a problem we are working to solve), those failures are new and likely introduced by your PR.
To do a full run in your local machine, you need to run:
mvn clean package  -Pproxy -Dmaven.test.failure.ignore=true -DfailIfNoTests=false -fae > output.txt
It looks to me, though, that simply running mvn test ProxyForwardedTestCase in servlet module will cause the failure.

**Comment by moulalis** [comment]
> @moulalis can you please check the following failures?
> https://github.com/undertow-io/undertow/pull/1044/checks?check_run_id=2002486404
> https://github.com/undertow-io/undertow/pull/1044/checks?check_run_id=2002486429
> https://github.com/undertow-io/undertow/pull/1044/checks?check_run_id=2002486571
> https://github.com/undertow-io/undertow/pull/1044/checks?check_run_id=2002486607
> https://github.com/undertow-io/undertow/pull/1044/checks?check_run_id=2002485978
> https://github.com/undertow-io/undertow/pull/1044/checks?check_run_id=2002486020
> Even though the CI is not stable and we do have to cope with some test failures in the PRs (a problem we are working to solve), those failures are new and likely introduced by your PR.
> To do a full run in your local machine, you need to run:
> mvn clean package -Pproxy -Dmaven.test.failure.ignore=true -DfailIfNoTests=false -fae > output.txt
> It looks to me, though, that simply running mvn test ProxyForwardedTestCase in servlet module will cause the failure.

@fl4via could you please check it now, the failures are fixed.

**Comment by fl4via** [comment]
@moulalis we are still seeing some failures: https://github.com/undertow-io/undertow/pull/1044/checks?check_run_id=2184399947#step:10:559 This one is in Windows environment

**Comment by moulalis** [comment]
> @moulalis we are still seeing some failures: https://github.com/undertow-io/undertow/pull/1044/checks?check_run_id=2184399947#step:10:559 all of them in Windows

Hi @fl4via, please check it now, it's fixed. Thanks

**Comment by fl4via** [comment]
@moulalis  thanks!

**Review by fl4via — APPROVED** [review]

**Pull request merged**
