### PR TITLE
[UNDERTOW-1901] -  fix max entity handling for multipart

### PR DESCRIPTION
**Pull request by baranowb**
Issue: https://issues.redhat.com/browse/UNDERTOW-1901

### CODE REVIEW

**Review by fl4via — APPROVED** [review]

**Comment by msfm** [comment]
I think the `MULTIPART_MAX_ENTITY_SIZE` option does not exist, so it should be removed from the comment on HttpServerExchange.
And `isMultiPartExchange()` should be moved from HttpServerExchange to ServletInitialHandler like PR#1083 and PR#1084

**Comment by baranowb** [comment]
> `isMultiPartExchange()` should be moved from HttpServerExchange to ServletInitialHandler like PR#1083 and PR#1084.

This has been declined. Reason for this is that other two PRs have it as private method as those are maintenance. This method is actually on purpose in HSE, since its related to exchange.
@ropalka  ^^

**Review by fl4via — CHANGES_REQUESTED** [review]
@baranowb  Can you please split this fix into two parts? I'm adding a Jira and scheduling it for 2.3.x as this changes public class API, and for the time being, lets submit a copy of the 2.0.x fix to master.

**Comment by fl4via** [comment]
@baranowb  Alternatively, and even simpler, we can just change this PR Jira to UNDERTOW-1901, that one is assinged to Undertow 2.3.0.Final, and open a new one for UNDERTOW-1601 master that just cherry-picks the fix that was submitted for 2.0.x

**Comment by baranowb** [comment]
@fl4via yeah, sure.

**Comment by baranowb** [comment]
TODO: update target branch once 2.3.x is up

**Review by fl4via — APPROVED** [review]

**Review by ropalka — APPROVED** [review]

**Pull request merged**
