### PR TITLE
[UNDERTOW-2312] multibytes language in URL request to http/https are …

### PR DESCRIPTION
**Pull request by baranowb**
…broken in EAP access log.
ISsue: https://issues.redhat.com/browse/UNDERTOW-2312

I need to check if there are TCs for access log. Im pushing this just for review ATM.

### CODE REVIEW

**Comment by fl4via** [comment]
I'll update this PR myself as I have a test that is ready for HTTP and now I'm trying to come up with a https one.

**Comment by fl4via** [comment]
Right now I'm working on making the test work with Http2 upgrade. It seems I solved the AJP test case, I'll let you know when I'm done, and I'll update this PR with my fixes.

**Comment by fl4via** [comment]
I have just updated the PR with my latest fixes. I can see that proxy http2 scenario is not working, and the reason for this is that the code goes through a different path when serving the request, and it ends up not invoking HttpRequestParser. It might be an issue in the tests or in the code, at this point I am not sure, and I will need to investigate further to find out.

**Comment by baranowb** [comment]
AFAIR often tests do some shady stuff to mimic "expected behavior".

**Comment by baranowb** [comment]
Sometimes tests mimic desired behavior that is expected, because setup is not attainable (it seems)

**Comment by fl4via** [comment]
the failure that are left are not reproducible in my machine. They will require an investigation in github ci itself

**Review by fl4via — APPROVED** [review]

**Comment by fl4via** [comment]
The problem in Windows CI is fixed. But now we have a problem in the new LotsOfQueryParamtersTestCase test. Investigating.

**Review by jasondlee — APPROVED** [review]
These changes look good to me. Side note: I like the addition of `final`. :)

**Pull request merged**
