### PR TITLE
[UNDERTOW-2002] Fixing StackOverflowError upon AJP read timeout

### PR DESCRIPTION
**Pull request by ropalka**
https://issues.redhat.com/browse/UNDERTOW-2002

### CODE REVIEW

**Comment by shizhenhua01** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by fl4via** [comment]
@shizhenhua01  Hi! Can you please restate in English, sorry, we don't speak your language :-(

**Comment by fl4via** [comment]
@ropalka  I'm rerunning the tests just to make sure that the mem leak in the test output is one of our already known test failures, and not introduced by the commit (since it happens in an AJP test, I thought I'd better double check

**Comment by gaol** [comment]
@fl4via I think you can ignore the message from @shizhenhua01 , it was an automatic reply saying that he/she is on vacation, not sure why this happened  :)

**Pull request merged**
