### PR TITLE
UNDERTOW-1746 - Max and Min content size predicates are implemented backwards

### PR DESCRIPTION
**Pull request by bdw429s**
The MinContentSizePredicate and MaxContentSizePredicate predicates from are named/implemented backwards.  In order to avoid a breaking change, deprecate these, and replace them with 'request-larger-than' and 'request-smaller-than' to make it clearer exactly what is being tested

### CODE REVIEW

**Comment by bdw429s** [comment]
@stuartwdouglas @fl4via This pull request is for ticket https://issues.redhat.com/browse/UNDERTOW-1746 as suggested by Stuart on the mailing list.

**Comment by bdw429s** [comment]
Deprecation notice added

**Comment by stuartwdouglas** [comment]
LGTM, can you squash it into one commit and I will merge.

**Comment by bdw429s** [comment]
@stuartwdouglas I'm not actually sure how to do that.  But you should be able to squash the commits when you merge, no?

image

**Comment by stuartwdouglas** [comment]
git rebase -i origin/master (or git rebase -i upstream/master, depending on how your repo is setup). 

In general I prefer merge commits to squashes in the UI, as it maintains a link to the related PR.

**Comment by bdw429s** [comment]
I managed to squash the commits for this pull, but the merge from when I brought in recent changes to 2.0.x is still there and for the life of me I don't know how to squash that one.  I don't usually like rewriting history on my Git repos-- usually a recipe for me to screw something up :/

**Comment by bdw429s** [comment]
@stuartwdouglas  Anything else I can do here?

**Comment by bdw429s** [comment]
@stuartwdouglas  @fl4via Anything else I can do here to help move this along?

**Comment by stuartwdouglas** [comment]
I merged it under https://github.com/undertow-io/undertow/pull/909 and backported to the 2.0.x branch

**Comment by bdw429s** [comment]
Thanks!

**Comment by fl4via** [comment]
@bdw429s because this was merged under #909, I'm marking this PR as duplicate and I'm closing it.

**Comment by bdw429s** [comment]
Thanks @fl4via

**Pull request closed without merging**
