### PR TITLE
Changing queue overflow response code to 503

### PR DESCRIPTION
**Pull request by matoikar**
Changing from custom response code 513 to RFC7231 https://tools.ietf.org/html/rfc7231#section-6.6.4 response code 503 "Service Unavailable"

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
Can one of the admins verify this patch?

**Comment by nealxyc** [comment]
👍

**Comment by stuartwdouglas** [comment]
This is ok to test

**Comment by fl4via** [comment]
@matoikar thanks for your PR! I created a Jira for ir, can you please add it to the commit message?
https://issues.jboss.org/browse/UNDERTOW-1537
Just add [UNDERTOW-1537] to the beginning of the message. Thanks!

**Comment by matoikar** [comment]
@fl4via Thanks Flavia, updated the commit message to start with the ticket id.

**Pull request merged**
