### PR TITLE
UNDERTOW-379 - closing idle connections

### PR DESCRIPTION
**Pull request by pjagielski**
Pull request to handle https://issues.jboss.org/browse/UNDERTOW-379

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
**Windows** [Build 948](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=34833&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of aaf46bbc336e19dc0246c29da1908e7a360999b6

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1384](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=34837&buildTypeId=UT_MASTER_LINUX) is now running using a merge of aaf46bbc336e19dc0246c29da1908e7a360999b6

**Comment by pjagielski** [comment]
I had to remove this condition in ProxyConnectionPool.timeoutConnections:
` if (data.timeoutKey == null || data.nextTimeout > holder.timeout) {`

The scheduled timeout task was never executed after handling another request on this connection.

**Comment by undertow-pull-request** [comment]
**Windows** [Build 948](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=34833&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of aaf46bbc336e19dc0246c29da1908e7a360999b6
Summary: Tests failed: 8 (8 new), passed: 3130, ignored: 369 Build time: 0:12:53
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.handlers.proxy.LoadBalancerConnectionPoolingTestCase.shouldReduceConnectionPool{proxy}: java.lang.AssertionError: expected:<10> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)

io.undertow.server.handlers.proxy.LoadBalancerConnectionPoolingTestCase.shouldReduceConnectionPool{proxy}{ajp}: java.lang.AssertionError: expected:<10> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)

io.undertow.server.handlers.proxy.LoadBalancerConnectionPoolingTestCase.shouldReduceConnectionPool{proxy}{spdy}: java.lang.AssertionError: expected:<10> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)

io.undertow.server.handlers.proxy.LoadBalancerConnectionPoolingTestCase.shouldReduceConnectionPool{proxy}{https}: java.lang.AssertionError: expected:<10> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)

io.undertow.server.handlers.proxy.LoadBalancerConnectionPoolingTestCase.shouldReduceConnectionPool{proxy}{http2}: java.lang.AssertionError: expected:<10> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)

io.undertow.server.handlers.HttpContinueConduitWrappingHandlerTestCase.testHttpContinueRejected{proxy}{http2}: org.apache.http.NoHttpResponseException: The target server failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:95)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:61)

io.undertow.server.handlers.HttpContinueAcceptingHandlerTestCase.testHttpContinueRejected{proxy}{http2}: org.apache.http.NoHttpResponseException: The target server failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:95)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:61)

io.undertow.server.handlers.proxy.LoadBalancerConnectionPoolingTestCase.shouldReduceConnectionPool{proxy}{http2-clear}: java.lang.AssertionError: expected:<10> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)

```

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1384](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=34837&buildTypeId=UT_MASTER_LINUX) outcome was **FAILURE** using a merge of aaf46bbc336e19dc0246c29da1908e7a360999b6
Summary: Tests failed: 9 (7 new), passed: 3208, ignored: 292 Build time: 0:14:10
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.handlers.proxy.LoadBalancerConnectionPoolingTestCase: java.lang.RuntimeException: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:444)

io.undertow.server.handlers.proxy.LoadBalancerConnectionPoolingTestCase: java.lang.RuntimeException: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:444)

io.undertow.server.handlers.proxy.LoadBalancerConnectionPoolingTestCase: java.lang.RuntimeException: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:444)

io.undertow.server.handlers.proxy.LoadBalancerConnectionPoolingTestCase: java.lang.RuntimeException: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:444)

io.undertow.server.handlers.proxy.LoadBalancerConnectionPoolingTestCase: java.lang.RuntimeException: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:444)

io.undertow.server.handlers.HttpContinueConduitWrappingHandlerTestCase.testHttpContinueRejected{proxy}{http2}: org.apache.http.NoHttpResponseException: The target server failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:95)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:61)

io.undertow.server.handlers.proxy.LoadBalancerConnectionPoolingTestCase: java.lang.RuntimeException: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:444)

io.undertow.server.handlers.HttpContinueConduitWrappingHandlerTestCase.testHttpContinueRejected{proxy}{https}: java.lang.RuntimeException: Buffer Leak io.undertow.server.handlers.HttpContinueConduitWrappingHandlerTestCase.testHttpContinueRejected{proxy}{https}
	at io.undertow.testutils.DefaultServer$1.testFinished(DefaultServer.java:259)
	at org.junit.runner.notification.RunNotifier$7.notifyListener(RunNotifier.java:191)

io.undertow.server.handlers.HttpContinueAcceptingHandlerTestCase.testHttpContinueRejected{proxy}{https}: java.lang.RuntimeException: Buffer Leak io.undertow.server.handlers.HttpContinueAcceptingHandlerTestCase.testHttpContinueRejected{proxy}{https}
	at io.undertow.testutils.DefaultServer$1.testFinished(DefaultServer.java:259)
	at org.junit.runner.notification.RunNotifier$7.notifyListener(RunNotifier.java:191)

```

**Comment by undertow-pull-request** [comment]
**Windows** [Build 949](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=34847&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 16d16ac7b2f38c1f54d18f804aa3a75f92cc1e2a

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1385](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=34851&buildTypeId=UT_MASTER_LINUX) is now running using a merge of 16d16ac7b2f38c1f54d18f804aa3a75f92cc1e2a

**Comment by undertow-pull-request** [comment]
**Windows** [Build 949](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=34847&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 16d16ac7b2f38c1f54d18f804aa3a75f92cc1e2a
Summary: Tests failed: 4 (3 new), passed: 3134, ignored: 369 Build time: 0:12:53
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testDigestSuccess{proxy}{https}: java.lang.AssertionError: expected:<200> but was:<401>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)

io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testDigestSuccess{proxy}{http2-clear}: java.lang.AssertionError: expected:<200> but was:<401>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)

io.undertow.websockets.jsr.test.stress.WebsocketStressTestCase.testCloseReason: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.net.ConnectException: Connection refused: no further information
	at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:252)
	at java.util.concurrent.FutureTask.get(FutureTask.java:111)

io.undertow.server.handlers.HttpContinueConduitWrappingHandlerTestCase.testHttpContinueRejected{proxy}{http2}: org.apache.http.NoHttpResponseException: The target server failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:95)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:61)

```

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1385](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=34851&buildTypeId=UT_MASTER_LINUX) outcome was **FAILURE** using a merge of 16d16ac7b2f38c1f54d18f804aa3a75f92cc1e2a
Summary: Tests failed: 4 (1 new), passed: 3213, ignored: 292 Build time: 0:15:38
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.handlers.HttpContinueAcceptingHandlerTestCase.testHttpContinueRejected{proxy}{http2}: org.apache.http.NoHttpResponseException: The target server failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:95)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:61)

io.undertow.server.handlers.HttpContinueConduitWrappingHandlerTestCase.testHttpContinueRejected{proxy}{https}: java.lang.RuntimeException: Buffer Leak io.undertow.server.handlers.HttpContinueConduitWrappingHandlerTestCase.testHttpContinueRejected{proxy}{https}
	at io.undertow.testutils.DefaultServer$1.testFinished(DefaultServer.java:259)
	at org.junit.runner.notification.RunNotifier$7.notifyListener(RunNotifier.java:191)

io.undertow.server.handlers.HttpContinueAcceptingHandlerTestCase.testHttpContinueRejected{proxy}{https}: java.lang.RuntimeException: Buffer Leak io.undertow.server.handlers.HttpContinueAcceptingHandlerTestCase.testHttpContinueRejected{proxy}{https}
	at io.undertow.testutils.DefaultServer$1.testFinished(DefaultServer.java:259)
	at org.junit.runner.notification.RunNotifier$7.notifyListener(RunNotifier.java:191)

io.undertow.server.handlers.HttpContinueConduitWrappingHandlerTestCase.testHttpContinueRejected{proxy}{http2}: org.apache.http.NoHttpResponseException: The target server failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:95)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:61)

```

**Comment by undertow-pull-request** [comment]
**Windows** [Build 954](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=35796&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 16d16ac7b2f38c1f54d18f804aa3a75f92cc1e2a

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1390](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=35808&buildTypeId=UT_MASTER_LINUX) is now running using a merge of 16d16ac7b2f38c1f54d18f804aa3a75f92cc1e2a

**Comment by undertow-pull-request** [comment]
**Windows** [Build 954](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=35796&buildTypeId=UNDERTOW_MasterWindows) outcome was **SUCCESS** using a merge of 16d16ac7b2f38c1f54d18f804aa3a75f92cc1e2a
Summary: Tests passed: 3138, ignored: 369 Build time: 0:13:51

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1390](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=35808&buildTypeId=UT_MASTER_LINUX) outcome was **FAILURE** using a merge of 16d16ac7b2f38c1f54d18f804aa3a75f92cc1e2a
Summary: Tests failed: 4, passed: 3213, ignored: 292 Build time: 0:15:42
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.handlers.HttpContinueConduitWrappingHandlerTestCase.testHttpContinueRejected{proxy}{https}: java.lang.RuntimeException: Buffer Leak io.undertow.server.handlers.HttpContinueConduitWrappingHandlerTestCase.testHttpContinueRejected{proxy}{https}
	at io.undertow.testutils.DefaultServer$1.testFinished(DefaultServer.java:259)
	at org.junit.runner.notification.RunNotifier$7.notifyListener(RunNotifier.java:191)

io.undertow.server.handlers.HttpContinueAcceptingHandlerTestCase.testHttpContinueRejected{proxy}{https}: java.lang.RuntimeException: Buffer Leak io.undertow.server.handlers.HttpContinueAcceptingHandlerTestCase.testHttpContinueRejected{proxy}{https}
	at io.undertow.testutils.DefaultServer$1.testFinished(DefaultServer.java:259)
	at org.junit.runner.notification.RunNotifier$7.notifyListener(RunNotifier.java:191)

io.undertow.server.handlers.HttpContinueAcceptingHandlerTestCase.testHttpContinueRejected{proxy}{http2}: org.apache.http.NoHttpResponseException: The target server failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:95)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:61)

io.undertow.server.handlers.HttpContinueConduitWrappingHandlerTestCase.testHttpContinueRejected{proxy}{http2}: org.apache.http.NoHttpResponseException: The target server failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:95)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:61)

```

**Comment by undertow-pull-request** [comment]
**Windows** [Build 957](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=35811&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 16d16ac7b2f38c1f54d18f804aa3a75f92cc1e2a

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1393](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=35823&buildTypeId=UT_MASTER_LINUX) is now running using a merge of 16d16ac7b2f38c1f54d18f804aa3a75f92cc1e2a

**Comment by undertow-pull-request** [comment]
**Windows** [Build 957](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=35811&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 16d16ac7b2f38c1f54d18f804aa3a75f92cc1e2a
Summary: Tests failed: 1, passed: 3138, ignored: 369 Build time: 0:13:33
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.handlers.HttpContinueAcceptingHandlerTestCase.testHttpContinueRejected{proxy}{https}: java.lang.RuntimeException: Buffer Leak io.undertow.server.handlers.HttpContinueAcceptingHandlerTestCase.testHttpContinueRejected{proxy}{https}
	at io.undertow.testutils.DefaultServer$1.testFinished(DefaultServer.java:259)
	at org.junit.runner.notification.RunNotifier$7.notifyListener(RunNotifier.java:191)

```

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1393](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=35823&buildTypeId=UT_MASTER_LINUX) outcome was **FAILURE** using a merge of 16d16ac7b2f38c1f54d18f804aa3a75f92cc1e2a
Summary: Tests failed: 2, passed: 3214, ignored: 292 Build time: 0:15:10
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.handlers.HttpContinueAcceptingHandlerTestCase.testHttpContinueRejected{proxy}{https}: java.lang.RuntimeException: Buffer Leak io.undertow.server.handlers.HttpContinueAcceptingHandlerTestCase.testHttpContinueRejected{proxy}{https}
	at io.undertow.testutils.DefaultServer$1.testFinished(DefaultServer.java:259)
	at org.junit.runner.notification.RunNotifier$7.notifyListener(RunNotifier.java:191)

io.undertow.server.handlers.HttpContinueConduitWrappingHandlerTestCase.testHttpContinueRejected{proxy}{http2}: org.apache.http.NoHttpResponseException: The target server failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:95)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:61)

```

**Comment by undertow-pull-request** [comment]
**Windows** [Build 960](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=35870&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 16d16ac7b2f38c1f54d18f804aa3a75f92cc1e2a

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1396](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=35878&buildTypeId=UT_MASTER_LINUX) is now running using a merge of 16d16ac7b2f38c1f54d18f804aa3a75f92cc1e2a

**Comment by undertow-pull-request** [comment]
**Windows** [Build 960](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=35870&buildTypeId=UNDERTOW_MasterWindows) outcome was **SUCCESS** using a merge of 16d16ac7b2f38c1f54d18f804aa3a75f92cc1e2a
Summary: Tests passed: 3145, ignored: 369 Build time: 0:13:02

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1396](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=35878&buildTypeId=UT_MASTER_LINUX) outcome was **FAILURE** using a merge of 16d16ac7b2f38c1f54d18f804aa3a75f92cc1e2a
Summary: Tests failed: 2, passed: 3222, ignored: 292 Build time: 0:15:10
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.handlers.HttpContinueConduitWrappingHandlerTestCase.testHttpContinueRejected{proxy}{https}: java.lang.RuntimeException: Buffer Leak io.undertow.server.handlers.HttpContinueConduitWrappingHandlerTestCase.testHttpContinueRejected{proxy}{https}
	at io.undertow.testutils.DefaultServer$1.testFinished(DefaultServer.java:259)
	at org.junit.runner.notification.RunNotifier$7.notifyListener(RunNotifier.java:191)

io.undertow.server.handlers.HttpContinueAcceptingHandlerTestCase.testHttpContinueRejected{proxy}{https}: java.lang.RuntimeException: Buffer Leak io.undertow.server.handlers.HttpContinueAcceptingHandlerTestCase.testHttpContinueRejected{proxy}{https}
	at io.undertow.testutils.DefaultServer$1.testFinished(DefaultServer.java:259)
	at org.junit.runner.notification.RunNotifier$7.notifyListener(RunNotifier.java:191)

```

**Comment by undertow-pull-request** [comment]
**Windows** [Build 965](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=35988&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 16d16ac7b2f38c1f54d18f804aa3a75f92cc1e2a

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1401](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=35992&buildTypeId=UT_MASTER_LINUX) is now running using a merge of 16d16ac7b2f38c1f54d18f804aa3a75f92cc1e2a

**Comment by undertow-pull-request** [comment]
**Windows** [Build 965](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=35988&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 16d16ac7b2f38c1f54d18f804aa3a75f92cc1e2a
Summary: Exit code 1 (new) Build time: 0:00:14
### Build problems:
Process exited with code 1

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1401](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=35992&buildTypeId=UT_MASTER_LINUX) outcome was **FAILURE** using a merge of 16d16ac7b2f38c1f54d18f804aa3a75f92cc1e2a
Summary: Exit code 1 (new) Build time: 0:00:26
### Build problems:
Process exited with code 1

**Comment by undertow-pull-request** [comment]
**Windows** [Build 969](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=36009&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 16d16ac7b2f38c1f54d18f804aa3a75f92cc1e2a

**Comment by undertow-pull-request** [comment]
**Windows** [Build 971](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=36016&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 16d16ac7b2f38c1f54d18f804aa3a75f92cc1e2a

**Comment by undertow-pull-request** [comment]
**Windows** [Build 969](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=36009&buildTypeId=UNDERTOW_MasterWindows) outcome was **SUCCESS** using a merge of 16d16ac7b2f38c1f54d18f804aa3a75f92cc1e2a
Summary: Tests passed: 3145, ignored: 369 Build time: 0:13:31

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1404](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=36021&buildTypeId=UT_MASTER_LINUX) is now running using a merge of 16d16ac7b2f38c1f54d18f804aa3a75f92cc1e2a

**Comment by undertow-pull-request** [comment]
**Windows** [Build 971](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=36016&buildTypeId=UNDERTOW_MasterWindows) outcome was **SUCCESS** using a merge of 16d16ac7b2f38c1f54d18f804aa3a75f92cc1e2a
Summary: Tests passed: 3145, ignored: 369 Build time: 0:13:56

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1404](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=36021&buildTypeId=UT_MASTER_LINUX) outcome was **FAILURE** using a merge of 16d16ac7b2f38c1f54d18f804aa3a75f92cc1e2a
Summary: Tests failed: 1 (1 new), passed: 3222, ignored: 292 Build time: 0:14:42
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.servlet.test.multipart.MultiPartTestCase.testMultiPartRequestToLarge{proxy}{https}: java.lang.RuntimeException: Buffer Leak io.undertow.servlet.test.multipart.MultiPartTestCase.testMultiPartRequestToLarge{proxy}{https}
	at io.undertow.testutils.DefaultServer$1.testFinished(DefaultServer.java:259)
	at org.junit.runner.notification.RunNotifier$7.notifyListener(RunNotifier.java:191)

```

**Pull request merged**
