### PR TITLE
[UNDERTOW-1876] security-manager and reflection permissions in Direct…

### PR DESCRIPTION
**Pull request by soul2zimate**
…ByteBufferDeallocator/undertow

Fix made in https://issues.redhat.com/browse/UNDERTOW-1558 only covers JDK version < 9, this completes it for JDK >= 9 case.

Issue: https://issues.redhat.com/browse/UNDERTOW-1876
2.1.x PR: https://github.com/undertow-io/undertow/pull/1080
2.0.x PR: https://github.com/undertow-io/undertow/pull/1081

### CODE REVIEW

**Comment by soul2zimate** [comment]
Are any CI jobs running with security manager enabled ?  Because the change only make a difference w/ and w/o security manager enabled.

Also, This change only made for JDK version >= 9, it should not affect any Undertow CI / JDK 8 jobs.

**Review by fl4via — APPROVED** [review]

**Comment by boris-unckel** [comment]
Hello @fl4via @soul2zimate 
this change seems strange to me for security. In [https://issues.redhat.com/browse/UNDERTOW-1558](https://issues.redhat.com/browse/UNDERTOW-1558) is an attachment to reproduce a security manager issue. A META-INF/permissions.xml is missing. Obviously the security manager will throw an exception for restricted methods - nothing is allowed.
Maybe I miss something in the case.
Kind regards
Boris
fyi @bstansberry

**Comment by soul2zimate** [comment]
The `permissions.xml` allows you to define custom security checks for the app/deployment.

In regards to `getDeclaredMethod()` and  `setAccessible` in this example, they require the caller domain to have proper "core"  Java permissions for successful execution. They needs to be wrapped in a `AccessController.doPrivileged()` to mark those calls as "privileged" so that such insufficient permissions from the app/deployment are ignored.

**Comment by boris-unckel** [comment]
@soul2zimate 
> ... to mark those calls as "privileged" so that such insufficient permissions from the app/deployment are ignored.
Thanks for your answer. I'm still not convinced. If it is possible to grant permissions, why should you build the system in a way that makes a grant not necessary? The usecase of activating the Java Security Manager is to enable checks. Someone who expects "activated checks without need to grant rights" is wrong and can simply not enable the JSM.

**Comment by soul2zimate** [comment]
In the example, only the calling of `getDeclaredMethod()` and `setAccessible()` is executed with all the permissions. User can still activate security manager to check other customized permissions if wanted.

**Comment by fl4via** [comment]
@boris-unckel From my pov, anything that is internal and is required to run a regular application should run without throwing unexpected exceptions. Hence, if that internal code runs an action that requires special permission, it should be run from inside a privileged block, unless a malicious attacker can take advantage of that (which is not the case here). Without this fix, a simple attempt to read the input stream in the servlet can cause a security exception. It occurs if memory has to be freed in the background during the read attempt. 
The final user is not supposed to know this specific detail, specially it being something that occurs occasionally. Nor is he expected to know that he has to grant permission to that specific code. This is why this fix is being proposed.

**Pull request merged**
