### PR TITLE
Extend PathTemplate (match method) to support wildcard matching in path string

### PR DESCRIPTION
**Pull request by ArekCzarnik**
hallo *,

i extend PathTemplate to support wildcard matching in path string
for example path url like /docs/{docId}/* match /docs/test/my.

i hope that is ok for the first pull request.

Thanks,
Arek

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
Can one of the admins verify this patch?

**Comment by ctomc** [comment]
this is ok to test

**Comment by stuartwdouglas** [comment]
Oops, I did not notice that this was targetting 1.3.x. As this is a new feature this will need to go into 1.4.x and 2.x. 1.4.x should have a final release very shortly.

**Comment by stuartwdouglas** [comment]
I have reverted the 1.3.x change and cherry-picked it only master and 1.4.x

**Comment by ArekCzarnik** [comment]
Thanks for the merge, sorry that i not request to 1.4.x.

**Pull request merged**
