### PR TITLE
[UNDERTOW-2188] fix deny-uncovered methods to work properly in corner…

### PR DESCRIPTION
**Pull request by baranowb**
… case
Issue: https://issues.redhat.com/browse/UNDERTOW-2188

### CODE REVIEW

**Comment by baranowb** [comment]
on hold with this one.

**Comment by baranowb** [comment]
maybe now.

**Comment by fl4via** [comment]
@baranowb is this PR ready for merging now?

**Comment by baranowb** [comment]
@fl4via yep, first commit was wrong.

**Review by fl4via — APPROVED** [review]

**Pull request merged**
