### PR TITLE
[UNDERTOW-506] GSSAPIAuthenticationMechanism doesn't parse IPv6 addre…

### PR DESCRIPTION
**Pull request by TomasHofman**
…ss correctly

https://issues.jboss.org/browse/UNDERTOW-506
https://bugzilla.redhat.com/show_bug.cgi?id=1172180

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1500](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=62655&buildTypeId=UT_MASTER_LINUX) is now running using a merge of fedac7e968f85fc9251702ff037675b4f06e88e7

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1208](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=62656&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of fedac7e968f85fc9251702ff037675b4f06e88e7

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1500](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=62655&buildTypeId=UT_MASTER_LINUX) outcome was **FAILURE** using a merge of fedac7e968f85fc9251702ff037675b4f06e88e7
Summary: Tests failed: 2 (2 new), passed: 2667, ignored: 302 Build time: 0:15:04
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.handlers.ReceiverTestCase.testAsyncReceivePartialBytes{proxy}{http2-clear}: <no details avaliable>

io.undertow.servlet.test.response.contenttype.ContentTypeFilesTestCase.testFileContentType{proxy}{https}: <no details avaliable>

```

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1208](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=62656&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of fedac7e968f85fc9251702ff037675b4f06e88e7
Summary: Tests failed: 12 (12 new), passed: 2580, ignored: 379 Build time: 0:15:07
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testDigestSuccess: <no details avaliable>

io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testNonceCountReUse: <no details avaliable>

io.undertow.server.handlers.ReceiverTestCase.testAsyncReceivePartialBytes: <no details avaliable>

io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testDigestSuccess{proxy}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxyHTTP2ViaUpgradeTestCase.testHeadersAreLowercase{proxy}{https}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxyHTTP2ViaUpgradeTestCase.testLoadShared{proxy}{https}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxyHTTP2ViaUpgradeTestCase.testLoadSharedWithServerShutdown{proxy}{https}: <no details avaliable>

io.undertow.server.handlers.SenderTestCase.testSyncTransfer{proxy}{http2}: <no details avaliable>

io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testDigestSuccess{proxy}{http2-clear}: <no details avaliable>

io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testNonceCountReUse{proxy}{http2-clear}: <no details avaliable>

io.undertow.server.handlers.ReceiverTestCase.testAsyncReceivePartialBytes{proxy}{http2-clear}: <no details avaliable>


##### there are 2 more failed tests, see build details
```

**Comment by TomasHofman** [comment]
Retest this please.

**Comment by TomasHofman** [comment]
Retest this.

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1501](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=62663&buildTypeId=UT_MASTER_LINUX) is now running using a merge of fedac7e968f85fc9251702ff037675b4f06e88e7

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1209](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=62664&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of fedac7e968f85fc9251702ff037675b4f06e88e7

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1209](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=62664&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of fedac7e968f85fc9251702ff037675b4f06e88e7
Summary: Tests failed: 5 (1 new), passed: 2587, ignored: 379 Build time: 0:15:14
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.handlers.ReceiverTestCase.testAsyncReceivePartialBytes{proxy}: <no details avaliable>

io.undertow.server.handlers.ReceiverTestCase.testAsyncReceivePartialBytes: <no details avaliable>

io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testDigestSuccess{proxy}{http2-clear}: <no details avaliable>

io.undertow.server.handlers.ReceiverTestCase.testAsyncReceivePartialBytes{proxy}{http2-clear}: <no details avaliable>

io.undertow.servlet.test.response.contenttype.ContentTypeFilesTestCase.testFileContentType{proxy}{https}: <no details avaliable>

```

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1501](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=62663&buildTypeId=UT_MASTER_LINUX) outcome was **FAILURE** using a merge of fedac7e968f85fc9251702ff037675b4f06e88e7
Summary: Tests failed: 2, passed: 2667, ignored: 302 Build time: 0:15:45
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.handlers.ReceiverTestCase.testAsyncReceivePartialBytes{proxy}{http2-clear}: <no details avaliable>

io.undertow.servlet.test.response.contenttype.ContentTypeFilesTestCase.testFileContentType{proxy}{https}: <no details avaliable>

```

**Comment by TomasHofman** [comment]
Retest this.

**Comment by ctomc** [comment]
retest this please :)

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1210](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=62839&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of fedac7e968f85fc9251702ff037675b4f06e88e7

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1502](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=62838&buildTypeId=UT_MASTER_LINUX) is now running using a merge of fedac7e968f85fc9251702ff037675b4f06e88e7

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1502](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=62838&buildTypeId=UT_MASTER_LINUX) outcome was **FAILURE** using a merge of fedac7e968f85fc9251702ff037675b4f06e88e7
Summary: Tests failed: 2, passed: 2667, ignored: 302 Build time: 0:14:57
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.handlers.ReceiverTestCase.testAsyncReceivePartialBytes{proxy}{http2-clear}: <no details avaliable>

io.undertow.servlet.test.response.contenttype.ContentTypeFilesTestCase.testFileContentType{proxy}{https}: <no details avaliable>

```

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1210](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=62839&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of fedac7e968f85fc9251702ff037675b4f06e88e7
Summary: Tests failed: 3 (1 new), passed: 2589, ignored: 379 Build time: 0:16:16
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.servlet.test.request.RequestPathTestCase.testRequestPaths{proxy}{https}: <no details avaliable>

io.undertow.server.handlers.ReceiverTestCase.testAsyncReceivePartialBytes: <no details avaliable>

io.undertow.server.handlers.ReceiverTestCase.testAsyncReceivePartialBytes{proxy}: <no details avaliable>

```

**Pull request merged**
