### PR TITLE
[UNDERTOW-2436] fix HttpServerExchange state flag race conditions

### PR DESCRIPTION
**Pull request by aogburn**
https://issues.redhat.com/browse/UNDERTOW-2436

### CODE REVIEW

**Comment by aogburn** [comment]
This is taking an approach equivalent to the [UNDERTOW-1158 fix](https://github.com/undertow-io/undertow/commit/c8ededd90987b0bdacfe85489de55bd13ec9984d) for the ServletInputStream state race conditions

**Review by fl4via — APPROVED** [review]

**Review by ropalka — APPROVED** [review]

**Comment by fl4via** [comment]
I am verifying this with a reproducer in a standalone application. Soon I'll update it with the results so it can be merged. The failures are not caused by this request and will be addressed in a separate PR I'll be submitting soon.

**Comment by fl4via** [comment]
Ci is fixed, we will be merging this one as soon as CI passes (which hopefully is the case now)

**Comment by aogburn** [comment]
Thanks @fl4via !

**Pull request merged**
