### PR TITLE
[UNDERTOW-1530] Access log adds newline by CRLF on Windows

### PR DESCRIPTION
**Pull request by nagetsum**
Issue: https://issues.jboss.org/browse/UNDERTOW-1530

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
Can one of the admins verify this patch?

**Comment by stuartwdouglas** [comment]
This is ok to test

**Comment by fl4via** [comment]
Retest this please

**Comment by fl4via** [comment]
Retest this please

**Comment by fl4via** [comment]
Retest this please

**Comment by fl4via** [comment]
Retest this please

**Pull request merged**
