### PR TITLE
UNDERTOW-488 Allow setting the same cookie more than once

### PR DESCRIPTION
**Pull request by aldaris**
This is the 1.1.9.Final-SNAPSHOT version of the fix in case there will be a new WildFly 8.x release.

### CODE REVIEW

**Comment by stuartwdouglas** [comment]
Because this involves a non backwards compatible API change this will only be in the 1.3 release

**Comment by aldaris** [comment]
If looking for a backwards-compatible version of the fix, would it be okay to introduce a new method like getAllResponseCookies that would return the Deque map, whilst the existing method would be modified to grab the last cookie value from the deque and just return Map<String, Cookie> as it did in the past? Connectors would need to use the Deque version to actually resolve the bug of course.

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1282](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=69999&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 3c8616976d1031500e81be2bcf64c172caae7e8d
Summary: Tests failed: 23 (23 new), passed: 1625, ignored: 211 Build time: 00:13:05
### Failed tests
```
io.undertow.server.handlers.proxy.LoadBalancingProxySPDYTestCase.testLoadSharedWithServerShutdown: java.lang.RuntimeException: java.net.BindException: Address already in use: bind
	at io.undertow.Undertow.start(Undertow.java:177)
	at io.undertow.server.handlers.proxy.AbstractLoadBalancingProxyTestCase.testLoadSharedWithServerShutdown(AbstractLoadBalancingProxyTestCase.java:99)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:477)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:96)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:260)
Caused by: java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:444)
	at sun.nio.ch.Net.bind(Net.java:436)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:182)
	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
	at org.xnio.ssl.JsseXnioSsl.createSslConnectionServer(JsseXnioSsl.java:260)
	at io.undertow.Undertow.start(Undertow.java:168)
	at io.undertow.server.handlers.proxy.AbstractLoadBalancingProxyTestCase.testLoadSharedWithServerShutdown(AbstractLoadBalancingProxyTestCase.java:99)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:477)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:96)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:260)
------- Stdout: -------
{:version=[HTTP/1.1], :path=[/name], x-forwarded-server=[localhost], :host=[localhost:7777], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], :scheme=[https], x-forwarded-proto=[http], x-forwarded-port=[7777], x-forwarded-for=[127.0.0.1], :method=[GET], x-forwarded-host=[localhost], Host=[localhost:7777]}


io.undertow.server.handlers.proxy.LoadBalancingProxyTestCase.testLoadSharedWithServerShutdown: java.lang.RuntimeException: java.net.BindException: Address already in use: bind
	at io.undertow.Undertow.start(Undertow.java:177)
	at io.undertow.server.handlers.proxy.AbstractLoadBalancingProxyTestCase.testLoadSharedWithServerShutdown(AbstractLoadBalancingProxyTestCase.java:101)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:477)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:96)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:260)
Caused by: java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:444)
	at sun.nio.ch.Net.bind(Net.java:436)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:182)
	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
	at io.undertow.Undertow.start(Undertow.java:140)
	at io.undertow.server.handlers.proxy.AbstractLoadBalancingProxyTestCase.testLoadSharedWithServerShutdown(AbstractLoadBalancingProxyTestCase.java:101)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:477)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:96)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:260)


io.undertow.server.handlers.proxy.LoadBalancingProxyTestCase.testDuplicateHeaders: java.lang.AssertionError: expected:<200> but was:<503>
	at io.undertow.server.handlers.proxy.AbstractLoadBalancingProxyTestCase.testDuplicateHeaders(AbstractLoadBalancingProxyTestCase.java:156)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:477)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:96)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:260)


io.undertow.server.handlers.proxy.LoadBalancingProxyAJPTestCase.testLoadSharedWithServerShutdown: java.lang.RuntimeException: java.net.BindException: Address already in use: bind
	at io.undertow.Undertow.start(Undertow.java:177)
	at io.undertow.server.handlers.proxy.AbstractLoadBalancingProxyTestCase.testLoadSharedWithServerShutdown(AbstractLoadBalancingProxyTestCase.java:101)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:477)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:96)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:260)
Caused by: java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:444)
	at sun.nio.ch.Net.bind(Net.java:436)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:182)
	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
	at io.undertow.Undertow.start(Undertow.java:131)
	at io.undertow.server.handlers.proxy.AbstractLoadBalancingProxyTestCase.testLoadSharedWithServerShutdown(AbstractLoadBalancingProxyTestCase.java:101)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:477)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:96)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:260)
------- Stdout: -------
{X-Forwarded-Server=[localhost], User-Agent=[Apache-HttpClient/4.2.6 (java 1.5)], Connection=[Keep-Alive], X-Forwarded-Proto=[http], X-Forwarded-Port=[7777], X-Forwarded-For=[127.0.0.1], Content-Length=[0], Host=[localhost:7777], X-Forwarded-Host=[localhost]}
{X-Forwarded-Server=[localhost], User-Agent=[Apache-HttpClient/4.2.6 (java 1.5)], Connection=[Keep-Alive], X-Forwarded-Proto=[http], X-Forwarded-Port=[7777], X-Forwarded-For=[127.0.0.1], Content-Length=[0], Host=[localhost:7777], X-Forwarded-Host=[localhost]}


io.undertow.server.handlers.proxy.LoadBalancingProxyAJPTestCase.testLoadSharedWithServerShutdown{proxy}: java.lang.RuntimeException: java.net.BindException: Address already in use: bind
	at io.undertow.Undertow.start(Undertow.java:177)
	at io.undertow.server.handlers.proxy.AbstractLoadBalancingProxyTestCase.testLoadSharedWithServerShutdown(AbstractLoadBalancingProxyTestCase.java:99)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:477)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:96)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:260)
Caused by: java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:444)
	at sun.nio.ch.Net.bind(Net.java:436)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:182)
	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
	at io.undertow.Undertow.start(Undertow.java:131)
	at io.undertow.server.handlers.proxy.AbstractLoadBalancingProxyTestCase.testLoadSharedWithServerShutdown(AbstractLoadBalancingProxyTestCase.java:99)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:477)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:96)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:260)


io.undertow.server.handlers.proxy.LoadBalancingProxySPDYTestCase.testLoadSharedWithServerShutdown{proxy}{ajp}: java.lang.RuntimeException: java.net.BindException: Address already in use: bind
	at io.undertow.Undertow.start(Undertow.java:177)
	at io.undertow.server.handlers.proxy.AbstractLoadBalancingProxyTestCase.testLoadSharedWithServerShutdown(AbstractLoadBalancingProxyTestCase.java:101)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:477)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:96)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:260)
Caused by: java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:444)
	at sun.nio.ch.Net.bind(Net.java:436)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:182)
	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
	at org.xnio.ssl.JsseXnioSsl.createSslConnectionServer(JsseXnioSsl.java:260)
	at io.undertow.Undertow.start(Undertow.java:168)
	at io.undertow.server.handlers.proxy.AbstractLoadBalancingProxyTestCase.testLoadSharedWithServerShutdown(AbstractLoadBalancingProxyTestCase.java:101)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:477)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:96)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:260)
------- Stdout: -------
{:version=[HTTP/1.1], x-forwarded-server=[localhost], :path=[/name], :host=[localhost:7777], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], :scheme=[https], x-forwarded-proto=[http], x-forwarded-port=[8888], x-forwarded-for=[127.0.0.1], content-length=[0], :method=[GET], x-forwarded-host=[localhost], Host=[localhost:7777]}


io.undertow.server.handlers.proxy.LoadBalancingProxySPDYTestCase.testDuplicateHeaders{proxy}{ajp}: java.lang.AssertionError: expected:<200> but was:<503>
	at io.undertow.server.handlers.proxy.AbstractLoadBalancingProxyTestCase.testDuplicateHeaders(AbstractLoadBalancingProxyTestCase.java:156)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:477)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:96)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:260)


io.undertow.server.ssl.ComplexSSLTestCase.testSslLotsOfData{proxy}{spdy}: java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:444)
	at sun.nio.ch.Net.bind(Net.java:436)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:182)
	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
	at org.xnio.ssl.JsseXnioSsl.createSslConnectionServer(JsseXnioSsl.java:260)
	at io.undertow.testutils.DefaultServer.startSSLServer(DefaultServer.java:649)
	at io.undertow.testutils.DefaultServer.startSSLServer(DefaultServer.java:629)
	at io.undertow.testutils.DefaultServer.startSSLServer(DefaultServer.java:618)
	at io.undertow.testutils.DefaultServer.startSSLServer(DefaultServer.java:567)
	at io.undertow.server.ssl.ComplexSSLTestCase.testSslLotsOfData(ComplexSSLTestCase.java:132)


io.undertow.server.handlers.proxy.LoadBalancingProxyAJPTestCase: java.lang.RuntimeException: java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:444)
	at sun.nio.ch.Net.bind(Net.java:436)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:182)
	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
	at io.undertow.Undertow.start(Undertow.java:131)
	at io.undertow.server.handlers.proxy.LoadBalancingProxyAJPTestCase.setup(LoadBalancingProxyAJPTestCase.java:78)java.lang.NullPointerException: null
	at io.undertow.Undertow.stop(Undertow.java:182)
	at io.undertow.server.handlers.proxy.AbstractLoadBalancingProxyTestCase.teardown(AbstractLoadBalancingProxyTestCase.java:57)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:260)
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:444)
	at sun.nio.ch.Net.bind(Net.java:436)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:182)
	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
	at io.undertow.Undertow.start(Undertow.java:131)
	at io.undertow.server.handlers.proxy.LoadBalancingProxyAJPTestCase.setup(LoadBalancingProxyAJPTestCase.java:78)java.lang.NullPointerException: null
	at io.undertow.Undertow.stop(Undertow.java:182)
	at io.undertow.server.handlers.proxy.AbstractLoadBalancingProxyTestCase.teardown(AbstractLoadBalancingProxyTestCase.java:57)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:260)


io.undertow.server.handlers.proxy.LoadBalancingProxySPDYTestCase.testLoadSharedWithServerShutdown{proxy}{spdy}: java.lang.RuntimeException: java.net.BindException: Address already in use: bind
	at io.undertow.Undertow.start(Undertow.java:177)
	at io.undertow.server.handlers.proxy.AbstractLoadBalancingProxyTestCase.testLoadSharedWithServerShutdown(AbstractLoadBalancingProxyTestCase.java:99)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:477)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:96)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:260)
Caused by: java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:444)
	at sun.nio.ch.Net.bind(Net.java:436)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:182)
	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
	at org.xnio.ssl.JsseXnioSsl.createSslConnectionServer(JsseXnioSsl.java:260)
	at io.undertow.Undertow.start(Undertow.java:168)
	at io.undertow.server.handlers.proxy.AbstractLoadBalancingProxyTestCase.testLoadSharedWithServerShutdown(AbstractLoadBalancingProxyTestCase.java:99)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:477)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:96)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:260)
------- Stdout: -------
{:version=[HTTP/1.1], :path=[/name], x-forwarded-server=[localhost], :host=[localhost:7777], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], :scheme=[https], x-forwarded-proto=[http], x-forwarded-port=[8888], x-forwarded-for=[127.0.0.1], :method=[GET], x-forwarded-host=[localhost], Host=[localhost:7777]}
{:version=[HTTP/1.1], :path=[/name], x-forwarded-server=[localhost], :host=[localhost:7777], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], :scheme=[https], x-forwarded-proto=[http], x-forwarded-port=[8888], x-forwarded-for=[127.0.0.1], :method=[GET], x-forwarded-host=[localhost], Host=[localhost:7777]}
{:version=[HTTP/1.1], :path=[/name], x-forwarded-server=[localhost], :host=[localhost:7777], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], :scheme=[https], x-forwarded-proto=[http], x-forwarded-port=[8888], x-forwarded-for=[127.0.0.1], :method=[GET], x-forwarded-host=[localhost], Host=[localhost:7777]}
{:version=[HTTP/1.1], :path=[/name], x-forwarded-server=[localhost], :host=[localhost:7777], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], :scheme=[https], x-forwarded-proto=[http], x-forwarded-port=[8888], x-forwarded-for=[127.0.0.1], :method=[GET], x-forwarded-host=[localhost], Host=[localhost:7777]}
{:version=[HTTP/1.1], :path=[/name], x-forwarded-server=[localhost], :host=[localhost:7777], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], :scheme=[https], x-forwarded-proto=[http], x-forwarded-port=[8888], x-forwarded-for=[127.0.0.1], :method=[GET], x-forwarded-host=[localhost], Host=[localhost:7777]}


io.undertow.server.handlers.proxy.LoadBalancingProxyAJPTestCase.testLoadSharedWithServerShutdown{proxy}{https}: java.lang.RuntimeException: java.net.BindException: Address already in use: bind
	at io.undertow.Undertow.start(Undertow.java:177)
	at io.undertow.server.handlers.proxy.AbstractLoadBalancingProxyTestCase.testLoadSharedWithServerShutdown(AbstractLoadBalancingProxyTestCase.java:99)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:477)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:96)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:260)
Caused by: java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:444)
	at sun.nio.ch.Net.bind(Net.java:436)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:182)
	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
	at io.undertow.Undertow.start(Undertow.java:131)
	at io.undertow.server.handlers.proxy.AbstractLoadBalancingProxyTestCase.testLoadSharedWithServerShutdown(AbstractLoadBalancingProxyTestCase.java:99)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:477)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:96)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:260)



##### there are 13 more failed tests, see build details
```

**Comment by stuartwdouglas** [comment]
Wildfly 8.x is only going to get critical security fixes at this point, so even if I did accept it it probably won't actually make it in anyway. If you really need this your best best is to just build it yourself with this fix.

**Comment by aldaris** [comment]
Are my chances any better with WildFly 9.x and undertow 1.2.x? Essentially I'm looking for an official release of WildFly which I can wholeheartedly support for [my product](https://bugster.forgerock.org/jira/browse/OPENAM-5072).

**Pull request closed without merging**
