### PR TITLE
UseAlias defaults to false, aligned with WFLY-4954

### PR DESCRIPTION
**Pull request by Karm**
See [wildfly/pull/7920](https://github.com/wildfly/wildfly/pull/7920) for explanation. This PR depends on [WFLY-4954](https://issues.jboss.org/browse/WFLY-4954).

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
Can one of the admins verify this patch?

**Comment by ctomc** [comment]
this is ok to test

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1216](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=64363&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 8ed215da0435ad6a3cf295b4f66d41de6aa7988e

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1508](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=64362&buildTypeId=UT_MASTER_LINUX) is now running using a merge of 8ed215da0435ad6a3cf295b4f66d41de6aa7988e

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1508](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=64362&buildTypeId=UT_MASTER_LINUX) outcome was **FAILURE** using a merge of 8ed215da0435ad6a3cf295b4f66d41de6aa7988e
Summary: Tests failed: 5 (1 new), passed: 2668, ignored: 306 Build time: 0:16:03
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.servlet.test.session.CrossContextServletSessionTestCase.testCrossContextSessionInvocation{proxy}{https}: <no details avaliable>

io.undertow.servlet.test.streams.ServletInputStreamEarlyCloseClientSideTestCase.testServletInputStreamEarlyClose{proxy}: <no details avaliable>

io.undertow.servlet.test.streams.ServletInputStreamDrainTestCase.testServletInputStreamEarlyClose{proxy}: <no details avaliable>

io.undertow.servlet.test.streams.ServletInputStreamEarlyCloseClientSideTestCase.testServletInputStreamEarlyClose{proxy}{https}: <no details avaliable>

io.undertow.servlet.test.response.contenttype.ContentTypeFilesTestCase.testFileContentType{proxy}{https}: <no details avaliable>

```

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1216](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=64363&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 8ed215da0435ad6a3cf295b4f66d41de6aa7988e
Summary: Tests failed: 9 (5 new), passed: 2587, ignored: 383 Build time: 0:16:53
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.handlers.proxy.LoadBalancingProxyTestCase.testStickySessions{proxy}{https}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxyTestCase.testLoadShared{proxy}{https}: <no details avaliable>

io.undertow.servlet.test.streams.ServletInputStreamDrainTestCase.testServletInputStreamEarlyClose{proxy}{spdy}: <no details avaliable>

io.undertow.servlet.test.streams.ServletInputStreamDrainTestCase.testServletInputStreamEarlyClose{proxy}{https}: <no details avaliable>

io.undertow.servlet.test.request.RequestPathTestCase.testRequestPaths{proxy}{https}: <no details avaliable>

io.undertow.server.handlers.ReceiverTestCase.testAsyncReceivePartialBytes: <no details avaliable>

io.undertow.servlet.test.streams.ServletInputStreamEarlyCloseClientSideTestCase.testServletInputStreamEarlyClose{proxy}: <no details avaliable>

io.undertow.servlet.test.session.CrossContextServletSessionTestCase.testCrossContextSessionInvocation{proxy}: <no details avaliable>

io.undertow.servlet.test.streams.ServletInputStreamEarlyCloseClientSideTestCase.testServletInputStreamEarlyClose{proxy}{https}: <no details avaliable>

```

**Pull request merged**
