### PR TITLE
[UNDERTOW-1786] handle IO properly for async context write

### PR DESCRIPTION
**Pull request by baranowb**
Issue: https://issues.redhat.com/browse/UNDERTOW-1786
2.0.x PR: https://github.com/undertow-io/undertow/pull/1088

### CODE REVIEW

**Review by fl4via — APPROVED** [review]

**Comment by fl4via** [comment]
@baranowb  it appears this PR has a new failure in an async test case

**Comment by baranowb** [comment]
You mean SenderTestCase.testAsyncTransfer ? Im fairly sure this should not fail. Change adds exchange purge in case stream has already failed - after IOE.

**Comment by fl4via** [comment]
@baranowb  I mean AsyncListenerOnErrorTest servlet Ubuntu JDK 8 run: https://github.com/undertow-io/undertow/pull/1086/checks?check_run_id=2863572486

**Comment by baranowb** [comment]
@fl4via  this seems to be a buffer leak, not related to changes.

**Comment by fl4via** [comment]
@baranowb  I commented out the problematic test in the proxy mode because the failure was not random, it is consistently failing. In fact, it is the memory leak we've been seeing often in the CI and it is not caused by this PR. I added a FIXME UNDERTOW-1523 to the commit so we can comment that out once we have dealt with that issue.

**Pull request merged**
