### PR TITLE
UNDERTOW-1346 Add clear methods for collection fields of DeploymentInfo

### PR DESCRIPTION
**Pull request by ppalaga**
https://issues.jboss.org/browse/UNDERTOW-1346

### CODE REVIEW

**Comment by ppalaga** [comment]
@stuartwdouglas could you please review?

**Comment by undertow-pull-request** [comment]
Can one of the admins verify this patch?

**Comment by stuartwdouglas** [comment]
I wonder if it would just be cleaner to remove the unmodifiable collection wrappers so you can just modify them directly.

**Comment by ppalaga** [comment]
We can live with both. If you prefer removing the unmodifiable wrappers I can modify the PR.

**Comment by stuartwdouglas** [comment]
Yea, I think that would be best. There is not really any practical reason they are unmodifiable, just undue caution on my part.

**Comment by ppalaga** [comment]
613fead removes the unmodifiable wrappers.

**Pull request merged**
