### PR TITLE
UNDERTOW-1196 match DUMP and INFO output of apache httpd mod_cluster

### PR DESCRIPTION
**Pull request by frapex**
The DUMP and INFO output of the undertow mod_cluster implementation contains formatting errors. This fix updates dump and info functions so that the output matches that of apache httpd mod_cluster.

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
Can one of the admins verify this patch?

**Comment by stuartwdouglas** [comment]
This is ok to test

**Comment by undertow-pull-request** [comment]
**Windows** [Build 2211](https://ci.wildfly.org/viewLog.html?buildId=76948&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 9a1f229e1164d1d473b20c81fa6d9fe250e12405
Summary: Tests passed: 2964, ignored: 613; exit code 1 Build time: 00:28:37

**Comment by frapex** [comment]
@stuartwdouglas JIRA issue added, commit message updated.

**Comment by undertow-pull-request** [comment]
**Windows** [Build 2214](https://ci.wildfly.org/viewLog.html?buildId=76997&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of fe1d62dc58ae8fd7d74f690bb48beee64fb86479
Summary: Tests passed: 2964, ignored: 613; exit code 1 Build time: 00:36:50

**Pull request merged**
