### PR TITLE
Added rewrite-host-header argument

### PR DESCRIPTION
**Pull request by lmineiro**
Added the argument so that requests could be made to upstream that required another Host header.
Also and made the proxy use a SimpleProxyClientProvider if theres only 1 host in the list of hosts

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
Can one of the admins verify this patch?

**Comment by ctomc** [comment]
this is ok to test

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1463](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=55051&buildTypeId=UT_MASTER_LINUX) is now running using a merge of e4a5ff62c5c37efe0e20a02328fa0e5cbf660485

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1182](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=55052&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of e4a5ff62c5c37efe0e20a02328fa0e5cbf660485

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1182](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=55052&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of e4a5ff62c5c37efe0e20a02328fa0e5cbf660485
Summary: Tests failed: 5 (2 new), passed: 2502, ignored: 375 Build time: 0:13:22
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.handlers.PredicatedHandlersProxyTestCase.testProxy{proxy}{spdy}: <no details avaliable>

io.undertow.servlet.test.multipart.MultiPartTestCase.testMultiPartRequestToLarge{proxy}{http2-clear}: <no details avaliable>

io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testDigestSuccess{proxy}{ajp}: <no details avaliable>

io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testDigestSuccess{proxy}{http2-clear}: <no details avaliable>

io.undertow.websockets.jsr.test.stress.WebsocketStressTestCase.webSocketStressTestCase: <no details avaliable>

```

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1463](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=55051&buildTypeId=UT_MASTER_LINUX) outcome was **FAILURE** using a merge of e4a5ff62c5c37efe0e20a02328fa0e5cbf660485
Summary: Tests failed: 1 (1 new), passed: 2583, ignored: 298 Build time: 0:15:10
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.handlers.PredicatedHandlersProxyTestCase.testProxy{proxy}{spdy}: <no details avaliable>

```

**Pull request merged**
