### PR TITLE
UNDERTOW-853 SPDY: SpdyClientConnection.sendRequest() shouldn't be synchronized

### PR DESCRIPTION
**Pull request by jwendell**
Revert "SPDY Connection: Make synchronized requests"

This reverts commit 595322a869494ba03610773b2e8084da8d4a8372.

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
Can one of the admins verify this patch?

**Comment by jwendell** [comment]
ping

**Comment by ctomc** [comment]
this is ok to test

**Comment by stuartwdouglas** [comment]
The issue is that without the sync the requests can be sent out of order which will break the connection. 

This really needs a fix similar to https://github.com/undertow-io/undertow/commit/91417fa220ccf9b58968b2505d0bb34086e2c622, however I am not sure when I will get time to look at it (SPDY is a dying protocol, so it is not high on my priority list)

**Comment by jwendell** [comment]
OK, let's close this one and track https://github.com/undertow-io/undertow/pull/512 instead.

**Pull request closed without merging**
