### PR TITLE
[UNDERTOW-1662] Add support for External HTTP authentication mechanis…

### PR DESCRIPTION
**Pull request by ashley-abdelsayed98**
…m with Elytron
https://issues.redhat.com/browse/UNDERTOW-1662
https://issues.redhat.com/browse/EAP7-1323

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
Can one of the admins verify this patch?

**Comment by fl4via** [comment]
This is ok to test

**Comment by fl4via** [comment]
This PR must be holded until the process for the EAP7 feature request is good to go

**Comment by fl4via** [comment]
I'm marking as waiting PR update since we are waiting updates on approval for other, related PRs, as well as an update in the EAP7 Jira

**Comment by fjuma** [comment]
@fl4via The RFE associated with this PR has now been pre-checked so this is now ready to be merged. Do you think we could get an Undertow 2.1.x release that includes this change in the next week or so?

**Review by fl4via — APPROVED** [review]

**Pull request merged**
