### PR TITLE
[UNDERTOW-1885] remove escape char from delimitered strings

### PR DESCRIPTION
**Pull request by baranowb**
Issue: https://issues.redhat.com/browse/UNDERTOW-1885

### CODE REVIEW

**Review by fl4via — CHANGES_REQUESTED** [review]
Can a test be added to this one?

**Comment by baranowb** [comment]
Which one?

**Comment by fl4via** [comment]
I'm marking this one as under verification for now. We discussed internally the impossibility of adding a test, but I want to revisit this issue carefully before merging it.

**Comment by ropalka** [comment]
Thanks @baranowb !

**Comment by ropalka** [comment]
After discussion with @baranowb and @rmartinc I reverted fix commit from this PR and left test commit merged in as https://issues.redhat.com/browse/UNDERTOW-2163 fixed this issue already.

**Pull request merged**
