### PR TITLE
[UNDERTOW-1883] Allow registering mod_cluster context in stopped or d…

### PR DESCRIPTION
**Pull request by spyrkob**
…isabled state

Issue: https://issues.redhat.com/browse/UNDERTOW-1883
2.0.x PR: #1263

### CODE REVIEW

**Comment by spyrkob** [comment]
@rhusar could you review please?

**Comment by spyrkob** [comment]
Is it possible to rerun the tests?

**Comment by gaol** [comment]
@fl4via would you please review and merge if it is OK for you? thanks :)

**Review by ropalka — APPROVED** [review]
LGTM

**Review by rhusar — APPROVED** [review]
@spyrkob Looks good, thanks!

**Pull request merged**
