### PR TITLE
Fix mod cluster advertise on windows

### PR DESCRIPTION
**Pull request by ctomc**

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1129](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=52078&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of f902c8fb1e18eb78de692dd2ed5bab709038c337

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1130](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=52080&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 56c8ea10f9bc7cb665a6c9a6a7230abbb9d11d1b

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1450](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=52081&buildTypeId=UT_MASTER_LINUX) is now running using a merge of 56c8ea10f9bc7cb665a6c9a6a7230abbb9d11d1b

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1129](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=52078&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 56c8ea10f9bc7cb665a6c9a6a7230abbb9d11d1b
Summary: Tests failed: 5 (4 new), passed: 2487, ignored: 369 Build time: 0:13:12
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testDigestSuccess: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxyHTTP2ViaUpgradeTestCase.testHeadersAreLowercase{proxy}{spdy}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxyHTTP2ViaUpgradeTestCase.testLoadShared{proxy}{spdy}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxyHTTP2ViaUpgradeTestCase.testLoadSharedWithServerShutdown{proxy}{spdy}: <no details avaliable>

io.undertow.websockets.jsr.test.stress.WebsocketStressTestCase.webSocketStressTestCase: <no details avaliable>

```

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1130](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=52080&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 56c8ea10f9bc7cb665a6c9a6a7230abbb9d11d1b
Summary: Tests failed: 1, passed: 2491, ignored: 369 Build time: 0:14:10
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.websockets.jsr.test.stress.WebsocketStressTestCase.webSocketStressTestCase: <no details avaliable>

```

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1450](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=52081&buildTypeId=UT_MASTER_LINUX) outcome was **SUCCESS** using a merge of 56c8ea10f9bc7cb665a6c9a6a7230abbb9d11d1b
Summary: Tests passed: 2569, ignored: 292 Build time: 0:12:23

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1132](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=52275&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 56c8ea10f9bc7cb665a6c9a6a7230abbb9d11d1b

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1132](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=52275&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 56c8ea10f9bc7cb665a6c9a6a7230abbb9d11d1b
Summary: Tests failed: 7 (6 new), passed: 2485, ignored: 369 Build time: 0:13:47
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testNonceCountReUse: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxyHTTP2ViaUpgradeTestCase.testHeadersAreLowercase{proxy}{spdy}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxyHTTP2ViaUpgradeTestCase.testLoadShared{proxy}{spdy}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxyHTTP2ViaUpgradeTestCase.testLoadSharedWithServerShutdown{proxy}{spdy}: <no details avaliable>

io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testDigestSuccess{proxy}{http2-clear}: <no details avaliable>

io.undertow.servlet.test.streams.ServletInputStreamTestCase.testAsyncServletInputStream{proxy}{http2-clear}: <no details avaliable>

io.undertow.websockets.jsr.test.stress.WebsocketStressTestCase.webSocketStressTestCase: <no details avaliable>

```

**Comment by stuartwdouglas** [comment]
merged, thanks

**Pull request closed without merging**
