### PR TITLE
UNDERTOW-238 Support OSGi.

### PR DESCRIPTION
**Pull request by hwellmann**
Added manifest headers.

Added package to generated "fakeclass", since bnd does not accept
classes in the default package.

Added an OSGi smoke test.

Depends on https://github.com/xnio/xnio/pull/57

### CODE REVIEW

**Comment by marcuskara** [comment]
Will this still be merged in Undertow?

**Comment by stuartwdouglas** [comment]
It depends on the XNIO PR that was never merged

**Comment by marcuskara** [comment]
@stuartwdouglas Thank you, I already asked there what the status is. Hope that it will be merged soon.

**Comment by undertow-pull-request** [comment]
Can one of the admins verify this patch?

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1461](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=54951&buildTypeId=UT_MASTER_LINUX) is now running using a merge of 8dccb245dddf514f97648ead7e361133d938f2f1

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1180](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=54952&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 8dccb245dddf514f97648ead7e361133d938f2f1

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1461](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=54951&buildTypeId=UT_MASTER_LINUX) outcome was **FAILURE** using a merge of 8dccb245dddf514f97648ead7e361133d938f2f1
Summary: Exit code 1 (new) Build time: 0:00:13
### Build problems:
Process exited with code 1

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1180](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=54952&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 8dccb245dddf514f97648ead7e361133d938f2f1
Summary: Exit code 1 (new) Build time: 0:00:42
### Build problems:
Process exited with code 1

**Comment by lostiniceland** [comment]
Any news about this PR? 
OSGI-Metadata for undertow would highly be appreciated.

**Comment by stuartwdouglas** [comment]
I think the real issue here is that because XNIO did not have OSGI metadata the tests failed, which was why it was never merged. I am closing this for now, but if another one was opened without failing tests I will consider it (although AFAIK XNIO would have to have OSGI added first for this to be useful).

**Comment by gnodet** [comment]
Superseded by #484

**Pull request closed without merging**
