### PR TITLE
UNDERTOW-1493: Fix TLS 1.3 half-close hang

### PR DESCRIPTION
**Pull request by lonemeow**
Fix infinite looping in `SslConduit` with Java 11 and TLS 1.3 half-close semantics.

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
Can one of the admins verify this patch?

**Comment by lonemeow** [comment]
I've updated the commit messages; would it be possible to get this reviewed?

We're hitting the issue in production and it would be preferable to update Undertow instead of adding workarounds.

**Comment by stuartwdouglas** [comment]
This is ok to test

**Comment by fjuma** [comment]
@fl4via Would it be possible to get this one reviewed and merged? It's also needed for [WFCORE-4172](https://issues.jboss.org/browse/WFCORE-4172).

**Pull request merged**
