### PR TITLE
Attempt to run CI with java 15

### PR DESCRIPTION
**Pull request by carterkozak**
This is prompted by https://issues.redhat.com/browse/UNDERTOW-1791
Hoping to illustrate failures on java 15 and validate that fixes resolve the failures.

### CODE REVIEW

**Comment by carterkozak** [comment]
CI results appear to match my own:

```
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    ForwardedHandlerTestCase.testForwardedHandler:86 expected:<google.com[]:80> but was:<google.com[/<unresolved>]:80>
Error:    ProxyHandlerXForwardedForTestCase.testXForwardedSsl:110 expected:<200> but was:<503>
Error:    ClientCertRenegotiationTestCase.testClientCertSuccessWithLargePostBody:140 expected:<200> but was:<403>
Error:    ClientCertRenegotiationTestCase.testClientCertSuccessWithPostBody:107 expected:<200> but was:<403>
Error:  Errors: 
Error:    ClientCertRenegotiationTestCase.testClientCertSuccess:85 » SSLHandshake Remote...
[INFO] 
Error:  Tests run: 649, Failures: 4, Errors: 1, Skipped: 6
```

**Comment by carterkozak** [comment]
The ClientCertRenegotiationTestCase tests pass when `jdk.tls.server.enableSessionTicketExtension` is `false`.
See https://www.oracle.com/java/technologies/javase/14-relnote-issues.html#JDK-8228396

ForwardedHandlerTestCase is fixed by #989

Client cert access is fixed by #988

**Comment by ropalka** [comment]
Hello @carterkozak thanks for your PR proposal but we're doing CI testing only for LTS Java releases, namely 8 and 11, see: 
https://en.wikipedia.org/wiki/Java_version_history

**Comment by carterkozak** [comment]
Will you accept fixes for bugs that prevent functionality on newer non-LTS releases?
I wouldn't suggest running java 15 tests forever, but running the latest java release in addition to LTS builds will catch issues before the next release.

**Comment by ropalka** [comment]
Sure we will accept fixes for bugs regardless if JDK is or isn't LTS @carterkozak

**Comment by carterkozak** [comment]
Fantastic, thanks @ropalka :-)
I'll close this out in favor of #988 and #989

**Pull request closed without merging**
