### PR TITLE
UNDERTOW-514 MCMPAdvertiseTask uses Locale.getDefault() instead of Lo…

### PR DESCRIPTION
**Pull request by rhusar**
…cale.US

Jira
https://issues.jboss.org/browse/UNDERTOW-514

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1504](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=64087&buildTypeId=UT_MASTER_LINUX) is now running using a merge of 0b187a11e0936de9beed8796c3a393e636c82651

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1212](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=64088&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 0b187a11e0936de9beed8796c3a393e636c82651

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1504](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=64087&buildTypeId=UT_MASTER_LINUX) outcome was **FAILURE** using a merge of 0b187a11e0936de9beed8796c3a393e636c82651
Summary: Tests failed: 5 (2 new), passed: 2668, ignored: 306 Build time: 0:16:01
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.servlet.test.streams.ServletInputStreamDrainTestCase.testServletInputStreamEarlyClose{proxy}: <no details avaliable>

io.undertow.servlet.test.streams.ServletInputStreamDrainTestCase.testServletInputStreamEarlyClose{proxy}{https}: <no details avaliable>

io.undertow.servlet.test.streams.ServletInputStreamEarlyCloseClientSideTestCase.testServletInputStreamEarlyClose{proxy}: <no details avaliable>

io.undertow.servlet.test.streams.ServletInputStreamEarlyCloseClientSideTestCase.testServletInputStreamEarlyClose{proxy}{https}: <no details avaliable>

io.undertow.servlet.test.request.RequestPathTestCase.testRequestPaths{proxy}{https}: <no details avaliable>

```

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1212](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=64088&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 0b187a11e0936de9beed8796c3a393e636c82651
Summary: Tests failed: 7 (4 new), passed: 2589, ignored: 383 Build time: 0:16:08
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.handlers.proxy.LoadBalancingProxyAJPTestCase.testStickySessions{proxy}{http2-clear}: <no details avaliable>

io.undertow.servlet.test.streams.ServletInputStreamDrainTestCase.testServletInputStreamEarlyClose{proxy}: <no details avaliable>

io.undertow.servlet.test.session.CrossContextServletSessionTestCase.testCrossContextSessionInvocation{proxy}{https}: <no details avaliable>

io.undertow.servlet.test.response.contenttype.ContentTypeFilesTestCase.testFileContentType{proxy}{https}: <no details avaliable>

io.undertow.server.handlers.ReceiverTestCase.testAsyncReceivePartialBytes: <no details avaliable>

io.undertow.servlet.test.streams.ServletInputStreamEarlyCloseClientSideTestCase.testServletInputStreamEarlyClose{proxy}: <no details avaliable>

io.undertow.servlet.test.streams.ServletInputStreamEarlyCloseClientSideTestCase.testServletInputStreamEarlyClose{proxy}{https}: <no details avaliable>

```

**Comment by rhusar** [comment]
Retest this please. All passing on my machine and neither I see how this would fail the tests.

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1505](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=64098&buildTypeId=UT_MASTER_LINUX) is now running using a merge of 0b187a11e0936de9beed8796c3a393e636c82651

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1213](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=64099&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 0b187a11e0936de9beed8796c3a393e636c82651

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1213](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=64099&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 0b187a11e0936de9beed8796c3a393e636c82651
Summary: Tests failed: 8 (1 new), passed: 2588, ignored: 383 Build time: 0:16:00
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.websockets.jsr.test.annotated.AnnotatedEndpointTest.testEncodingAndDecoding: <no details avaliable>

io.undertow.server.handlers.ReceiverTestCase.testAsyncReceivePartialBytes: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxyAJPTestCase.testStickySessions{proxy}{http2-clear}: <no details avaliable>

io.undertow.servlet.test.streams.ServletInputStreamEarlyCloseClientSideTestCase.testServletInputStreamEarlyClose{proxy}: <no details avaliable>

io.undertow.servlet.test.streams.ServletInputStreamDrainTestCase.testServletInputStreamEarlyClose{proxy}: <no details avaliable>

io.undertow.servlet.test.streams.ServletInputStreamEarlyCloseClientSideTestCase.testServletInputStreamEarlyClose{proxy}{https}: <no details avaliable>

io.undertow.servlet.test.session.CrossContextServletSessionTestCase.testCrossContextSessionInvocation{proxy}{https}: <no details avaliable>

io.undertow.servlet.test.response.contenttype.ContentTypeFilesTestCase.testFileContentType{proxy}{https}: <no details avaliable>

```

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1505](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=64098&buildTypeId=UT_MASTER_LINUX) outcome was **FAILURE** using a merge of 0b187a11e0936de9beed8796c3a393e636c82651
Summary: Tests failed: 5, passed: 2668, ignored: 306 Build time: 0:16:14
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.servlet.test.streams.ServletInputStreamEarlyCloseClientSideTestCase.testServletInputStreamEarlyClose{proxy}: <no details avaliable>

io.undertow.servlet.test.streams.ServletInputStreamDrainTestCase.testServletInputStreamEarlyClose{proxy}: <no details avaliable>

io.undertow.servlet.test.streams.ServletInputStreamEarlyCloseClientSideTestCase.testServletInputStreamEarlyClose{proxy}{https}: <no details avaliable>

io.undertow.servlet.test.streams.ServletInputStreamDrainTestCase.testServletInputStreamEarlyClose{proxy}{https}: <no details avaliable>

io.undertow.servlet.test.request.RequestPathTestCase.testRequestPaths{proxy}{https}: <no details avaliable>

```

**Comment by rhusar** [comment]
Retest this please.

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1506](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=64101&buildTypeId=UT_MASTER_LINUX) is now running using a merge of 0b187a11e0936de9beed8796c3a393e636c82651

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1214](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=64102&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 0b187a11e0936de9beed8796c3a393e636c82651

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1214](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=64102&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 0b187a11e0936de9beed8796c3a393e636c82651
Summary: Tests failed: 8 (4 new), passed: 2588, ignored: 383 Build time: 0:16:22
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.handlers.proxy.LoadBalancingProxyTestCase.testStickySessions{proxy}{spdy}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxyTestCase.testLoadShared{proxy}{spdy}: <no details avaliable>

io.undertow.servlet.test.streams.ServletInputStreamDrainTestCase.testServletInputStreamEarlyClose{proxy}{https}: <no details avaliable>

io.undertow.servlet.test.request.RequestPathTestCase.testRequestPaths{proxy}{https}: <no details avaliable>

io.undertow.server.handlers.ReceiverTestCase.testAsyncReceivePartialBytes: <no details avaliable>

io.undertow.servlet.test.streams.ServletInputStreamEarlyCloseClientSideTestCase.testServletInputStreamEarlyClose{proxy}: <no details avaliable>

io.undertow.servlet.test.streams.ServletInputStreamDrainTestCase.testServletInputStreamEarlyClose{proxy}: <no details avaliable>

io.undertow.servlet.test.streams.ServletInputStreamEarlyCloseClientSideTestCase.testServletInputStreamEarlyClose{proxy}{https}: <no details avaliable>

```

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1506](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=64101&buildTypeId=UT_MASTER_LINUX) outcome was **FAILURE** using a merge of 0b187a11e0936de9beed8796c3a393e636c82651
Summary: Tests failed: 5, passed: 2668, ignored: 306 Build time: 0:16:53
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.servlet.test.streams.ServletInputStreamEarlyCloseClientSideTestCase.testServletInputStreamEarlyClose{proxy}: <no details avaliable>

io.undertow.servlet.test.streams.ServletInputStreamDrainTestCase.testServletInputStreamEarlyClose{proxy}: <no details avaliable>

io.undertow.servlet.test.streams.ServletInputStreamEarlyCloseClientSideTestCase.testServletInputStreamEarlyClose{proxy}{https}: <no details avaliable>

io.undertow.servlet.test.streams.ServletInputStreamDrainTestCase.testServletInputStreamEarlyClose{proxy}{https}: <no details avaliable>

io.undertow.servlet.test.request.RequestPathTestCase.testRequestPaths{proxy}{https}: <no details avaliable>

```

**Comment by rhusar** [comment]
Merged along with fixes in other parts in 4188c0a35a642f7e3423974ed82107937a685ff2. Closing.

**Pull request closed without merging**
