### PR TITLE
use IO logger for IOException

### PR DESCRIPTION
**Pull request by christophsturm**
to make it possible to silence them by turning off logging for io.undertow.request.io

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
Can one of the admins verify this patch?

**Comment by ctomc** [comment]
this is ok to test

**Comment by undertow-pull-request** [comment]
**Linux** [Build 390](https://ci.wildfly.org/viewLog.html?buildId=63833&buildTypeId=UNDERTOW_14xLinux) outcome was **FAILURE** using a merge of 4db0802aa35f990cfaf163e00a664746f3745a38
Summary: Tests failed: 1, passed: 2846, ignored: 504 Build time: 00:21:58
### Failed tests
```
io.undertow.servlet.test.streams.ServletInputStreamEarlyCloseClientSideTestCase.testServletInputStreamEarlyClose[proxy][https]: java.lang.AssertionError
	at io.undertow.servlet.test.streams.ServletInputStreamEarlyCloseClientSideTestCase.testServletInputStreamEarlyClose(ServletInputStreamEarlyCloseClientSideTestCase.java:79)
------- Stderr: -------
04:51:33,246 DEBUG (XNIO-1 task-23) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate HttpServerExchange{ POST /servletContext/servlet request {X-Forwarded-Proto=[http], X-Forwarded-Port=[80], X-Forwarded-For=[127.0.0.1], X-Forwarded-Server=[localhost], Content-Length=[130000100], Host=[localhost], X-Forwarded-Host=[localhost]} response {}}, authentication required: false
04:51:33,247 DEBUG (XNIO-1 task-23) [io.undertow.request.security] <SecurityContextImpl.java:246> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@6ae75e for HttpServerExchange{ POST /servletContext/servlet request {X-Forwarded-Proto=[http], X-Forwarded-Port=[80], X-Forwarded-For=[127.0.0.1], X-Forwarded-Server=[localhost], Content-Length=[130000100], Host=[localhost], X-Forwarded-Host=[localhost]} response {}}
04:51:33,248 DEBUG (XNIO-1 task-23) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for HttpServerExchange{ POST /servletContext/servlet request {X-Forwarded-Proto=[http], X-Forwarded-Port=[80], X-Forwarded-For=[127.0.0.1], X-Forwarded-Server=[localhost], Content-Length=[130000100], Host=[localhost], X-Forwarded-Host=[localhost]} response {}}
04:51:33,258 DEBUG (XNIO-1 I/O-2) [io.undertow.client.http.HttpClientConnection] <HttpClientConnection.java:458> close called on connection to localhost/127.0.0.1:8888
04:51:33,259 DEBUG (XNIO-1 I/O-2) [io.undertow.client.http.HttpClientExchange] <HttpClientExchange.java:87> request terminated for request to localhost/127.0.0.1:8888 /servletContext/servlet
04:51:33,261 ERROR (XNIO-1 I/O-2) [io.undertow] <HttpServerExchange.java:1700> UT005085: Connection io.undertow.server.protocol.http.HttpServerConnection@93ae62 for exchange HttpServerExchange{ POST /servletContext/servlet request {Content-Length=[130000100], Host=[localhost]} response {Connection=[close], Content-Length=[0], Date=[Tue, 13 Jun 2017 11:51:33 GMT]}} was not closed cleanly, forcibly closing connection
04:51:33,262 DEBUG (XNIO-1 I/O-2) [io.undertow.client.http.HttpClientConnection] <HttpClientConnection.java:176> connection to localhost/127.0.0.1:8888 closed
04:51:33,263 ERROR (XNIO-1 I/O-2) [io.undertow.proxy] <ProxyHandler.java:642> UT005028: Proxy request to /servletContext/servlet failed: java.nio.channels.ClosedChannelException
	at io.undertow.client.http.HttpClientConnection$5.handleEvent(HttpClientConnection.java:194)
	at io.undertow.client.http.HttpClientConnection$5.handleEvent(HttpClientConnection.java:173)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.StreamConnection.invokeCloseListener(StreamConnection.java:80)
	at org.xnio.Connection.readClosed(Connection.java:94)
	at io.undertow.protocols.ssl.UndertowSslConnection.readClosed(UndertowSslConnection.java:140)
	at io.undertow.protocols.ssl.SslConduit.notifyReadClosed(SslConduit.java:609)
	at io.undertow.protocols.ssl.SslConduit.closed(SslConduit.java:984)
	at io.undertow.protocols.ssl.SslConduit.close(SslConduit.java:1079)
	at io.undertow.protocols.ssl.SslConduit.doWrap(SslConduit.java:902)
	at io.undertow.protocols.ssl.SslConduit.doUnwrap(SslConduit.java:669)
	at io.undertow.protocols.ssl.SslConduit.read(SslConduit.java:567)
	at org.xnio.conduits.PushBackStreamSourceConduit.read(PushBackStreamSourceConduit.java:52)
	at org.xnio.conduits.ConduitStreamSourceChannel.read(ConduitStreamSourceChannel.java:127)
	at io.undertow.util.ConnectionUtils$4.handleEvent(ConnectionUtils.java:110)
	at io.undertow.util.ConnectionUtils$4.handleEvent(ConnectionUtils.java:106)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at io.undertow.protocols.ssl.SslConduit$SslReadReadyHandler.readReady(SslConduit.java:1129)
	at io.undertow.protocols.ssl.SslConduit$SslWriteReadyHandler.writeReady(SslConduit.java:1206)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:93)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:559)

04:51:33,264 ERROR (XNIO-1 task-23) [io.undertow.request] <LoggingExceptionHandler.java:80> UT005023: Exception handling request to /servletContext/servlet: java.lang.NullPointerException
	at io.undertow.servlet.spec.ServletInputStreamImpl.readIntoBuffer(ServletInputStreamImpl.java:169)
	at io.undertow.servlet.spec.ServletInputStreamImpl.read(ServletInputStreamImpl.java:144)
	at io.undertow.servlet.spec.ServletInputStreamImpl.read(ServletInputStreamImpl.java:131)
	at io.undertow.servlet.test.streams.EarlyCloseClientServlet.doPost(EarlyCloseClientServlet.java:50)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)


```

**Comment by christophsturm** [comment]
that test failure looks random to me

**Comment by stuartwdouglas** [comment]
Merged, with change to the commit message to reference https://issues.jboss.org/browse/UNDERTOW-1104

**Pull request closed without merging**
