### PR TITLE
[UNDERTOW-2389] Use WeakHashMap in DefaultByteBufferPool to avoid leak for released threads

### PR DESCRIPTION
**Pull request by aogburn**
https://issues.redhat.com/browse/UNDERTOW-2389

### CODE REVIEW

**Comment by soul2zimate** [comment]
@favila could you review ? this is needed by downstream

**Comment by favila** [comment]
> @favila could you review ? this is needed by downstream

@soul2zimate did you mean `@fl4via`?

**Comment by soul2zimate** [comment]
> > @favila could you review ? this is needed by downstream
> 
> @soul2zimate did you mean `@fl4via`?

My apology

**Comment by rikcarve** [comment]
Seems like a duplicate of https://github.com/undertow-io/undertow/pull/1589

**Comment by fl4via** [comment]
I am closing this PR marking it as partially duplicate of #1589 and the fix is incorporated in #1599

**Pull request closed without merging**
