### PR TITLE
[UNDERTOW-1546] Upgrade jboss-parent pom version to 35

### PR DESCRIPTION
**Pull request by fl4via**
Jira: https://issues.jboss.org/browse/UNDERTOW-1546

### CODE REVIEW

**Comment by fl4via** [comment]
This is ok to test

**Comment by fl4via** [comment]
Retest this please

**Comment by fl4via** [comment]
Retest this please

**Comment by luck3y** [comment]
retest this please

**Comment by luck3y** [comment]
retest this please

**Comment by luck3y** [comment]
retest this please

**Comment by luck3y** [comment]
retest this please

**Comment by luck3y** [comment]
retest this please

**Comment by luck3y** [comment]
retest this please

**Pull request merged**
