### PR TITLE
[UNDERTOW-2325] change SecureCookieCommitListener to also look throug…

### PR DESCRIPTION
**Pull request by xjusko**
…h the response headers for any "set-cookie" headers
https://issues.redhat.com/browse/UNDERTOW-2325

### CODE REVIEW

**Comment by shizhenhua01** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by xjusko** [comment]
Hi @fl4via, can I get a review on this PR?

**Comment by xjusko** [comment]
Hi @fl4via , could you please review my PR? Thanks.

**Comment by baranowb** [comment]
Looks good.

**Review by ropalka — APPROVED** [review]

**Pull request merged**
