### PR TITLE
Fix getHostAndPort() to properly return 443 for https

### PR DESCRIPTION
**Pull request by ctomc**
needed for proper cors validation in wildfly-core

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
**Windows** [Build 977](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=36135&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 7638961312bdad12b5ab710ac0d80dbb7dcc152d

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1410](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=36139&buildTypeId=UT_MASTER_LINUX) is now running using a merge of 7638961312bdad12b5ab710ac0d80dbb7dcc152d

**Comment by undertow-pull-request** [comment]
**Windows** [Build 977](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=36135&buildTypeId=UNDERTOW_MasterWindows) outcome was **SUCCESS** using a merge of 7638961312bdad12b5ab710ac0d80dbb7dcc152d
Summary: Tests passed: 3146, ignored: 375 Build time: 0:12:52

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1410](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=36139&buildTypeId=UT_MASTER_LINUX) outcome was **SUCCESS** using a merge of 7638961312bdad12b5ab710ac0d80dbb7dcc152d
Summary: Tests passed: 3223, ignored: 298 Build time: 0:14:40

**Comment by undertow-pull-request** [comment]
**Windows** [Build 979](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=36141&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 7638961312bdad12b5ab710ac0d80dbb7dcc152d

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1412](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=36149&buildTypeId=UT_MASTER_LINUX) is now running using a merge of 7638961312bdad12b5ab710ac0d80dbb7dcc152d

**Comment by ctomc** [comment]
oh well

**Comment by undertow-pull-request** [comment]
**Windows** [Build 979](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=36141&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 7638961312bdad12b5ab710ac0d80dbb7dcc152d
Summary: Tests failed: 3 (1 new), passed: 3145, ignored: 375 Build time: 0:14:00
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.ssl.ComplexSSLTestCase.testSslLotsOfData{proxy}{http2-clear}: java.lang.AssertionError: expected:<200> but was:<503>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)

io.undertow.server.ssl.ComplexSSLTestCase.testSslLotsOfData{proxy}{http2-clear}: java.lang.RuntimeException: Buffer Leak io.undertow.server.ssl.ComplexSSLTestCase.testSslLotsOfData{proxy}{http2-clear}
	at io.undertow.testutils.DefaultServer$1.testFinished(DefaultServer.java:259)
	at org.junit.runner.notification.RunNotifier$7.notifyListener(RunNotifier.java:191)

io.undertow.server.ssl.ComplexSSLTestCase.testSslLotsOfData{proxy}{http2-clear}: java.lang.RuntimeException: Buffer Leak io.undertow.server.ssl.ComplexSSLTestCase.testSslLotsOfData{proxy}{http2-clear}
	at io.undertow.testutils.DefaultServer$1.testFinished(DefaultServer.java:259)
	at org.junit.runner.notification.RunNotifier$7.notifyListener(RunNotifier.java:191)

```

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1412](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=36149&buildTypeId=UT_MASTER_LINUX) outcome was **FAILURE** using a merge of 7638961312bdad12b5ab710ac0d80dbb7dcc152d
Summary: Tests failed: 6 (6 new), passed: 3221, ignored: 298 Build time: 0:18:36
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.servlet.test.streams.ServletInputStreamTestCase.testAsyncServletInputStream{proxy}{spdy}: java.lang.RuntimeException: test failed with i equal to 6
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:118)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:159)

io.undertow.servlet.test.streams.ServletInputStreamTestCase.testAsyncServletInputStream{proxy}{spdy}: java.lang.RuntimeException: Buffer Leak io.undertow.servlet.test.streams.ServletInputStreamTestCase.testAsyncServletInputStream{proxy}{spdy}
	at io.undertow.testutils.DefaultServer$1.testFinished(DefaultServer.java:259)
	at org.junit.runner.notification.RunNotifier$7.notifyListener(RunNotifier.java:191)

io.undertow.servlet.test.streams.ServletInputStreamTestCase.testAsyncServletInputStream{proxy}{spdy}: java.lang.RuntimeException: Buffer Leak io.undertow.servlet.test.streams.ServletInputStreamTestCase.testAsyncServletInputStream{proxy}{spdy}
	at io.undertow.testutils.DefaultServer$1.testFinished(DefaultServer.java:259)
	at org.junit.runner.notification.RunNotifier$7.notifyListener(RunNotifier.java:191)

io.undertow.servlet.test.streams.ServletInputStreamTestCase.testAsyncServletInputStream{proxy}{http2}: java.lang.RuntimeException: test failed with i equal to 8
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)

io.undertow.servlet.test.streams.ServletInputStreamTestCase.testAsyncServletInputStream{proxy}{http2}: java.lang.RuntimeException: Buffer Leak io.undertow.servlet.test.streams.ServletInputStreamTestCase.testAsyncServletInputStream{proxy}{http2}
	at io.undertow.testutils.DefaultServer$1.testFinished(DefaultServer.java:259)
	at org.junit.runner.notification.RunNotifier$7.notifyListener(RunNotifier.java:191)

io.undertow.servlet.test.streams.ServletInputStreamTestCase.testAsyncServletInputStream{proxy}{http2}: java.lang.RuntimeException: Buffer Leak io.undertow.servlet.test.streams.ServletInputStreamTestCase.testAsyncServletInputStream{proxy}{http2}
	at io.undertow.testutils.DefaultServer$1.testFinished(DefaultServer.java:259)
	at org.junit.runner.notification.RunNotifier$7.notifyListener(RunNotifier.java:191)

```

**Pull request closed without merging**
