### PR TITLE
UNDERTOW-1536: fixed client auth when using proxy protocol

### PR DESCRIPTION
**Pull request by uherberg**
When Proxy Protocol (both version v1 and v2) is enabled, client authentication doesn't work. During the TLS Handshake, the server hello doesn't include the Certificate Request, so the client never sends its certificates. With the same configuration but disabled proxy protocol, the server hello is correct (and the client sends its certs). I verified this running a local HAProxy with enabled proxy protocol. This fix sets the SSLEngine configuration to properly request the client certificates.

### CODE REVIEW

**Comment by uherberg** [comment]
Not sure why the Windows tests failed. Tests ran successfully on my local host. Linux tests pass.

**Comment by fl4via** [comment]
Retest this please

**Comment by uherberg** [comment]
Good catch. I’ll fix that

**Comment by uherberg** [comment]
@fl4via I fixed it, and also copied some code to set the cipher order (copied from UndertowAcceptingSslChannel).

**Comment by fl4via** [comment]
Retest this please

**Comment by uherberg** [comment]
@fl4via I squashed the two commits into a single one, as you suggested.

**Comment by uherberg** [comment]
@fl4via Any update when this can be merged and when Undertow 2.0.21 can be released? We can't use Undertow until this is fixed, since our services require mTLS.

**Pull request merged**
