### PR TITLE
[UNDERTOW-487] Bugfix: session would expire in a half time of actual session-timeout…

### PR DESCRIPTION
**Pull request by jstourac**
… set

With current implementation session timeouts in a half time of the real session timeout value that is set in the undertow configuration.

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
Can one of the admins verify this patch?

**Comment by ctomc** [comment]
this is ok to test

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1206](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=61128&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 160f3783d023810f26db264c38c1dff7d08b0850

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1498](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=61127&buildTypeId=UT_MASTER_LINUX) is now running using a merge of 160f3783d023810f26db264c38c1dff7d08b0850

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1206](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=61128&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 160f3783d023810f26db264c38c1dff7d08b0850
Summary: Tests failed: 5 (5 new), passed: 2524, ignored: 379 Build time: 0:14:05
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testDigestSuccess: <no details avaliable>

io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testDigestSuccess{proxy}{ajp}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxyHTTP2ViaUpgradeTestCase.testHeadersAreLowercase{proxy}{ajp}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxyHTTP2ViaUpgradeTestCase.testLoadShared{proxy}{ajp}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxyHTTP2ViaUpgradeTestCase.testLoadSharedWithServerShutdown{proxy}{ajp}: <no details avaliable>

```

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1498](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=61127&buildTypeId=UT_MASTER_LINUX) outcome was **SUCCESS** using a merge of 160f3783d023810f26db264c38c1dff7d08b0850
Summary: Tests passed: 2606, ignored: 302 Build time: 0:15:13

**Pull request merged**
