### PR TITLE
No changes

### PR DESCRIPTION
**Pull request by darranl**

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1188](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=55392&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 136f3bfed1e820e39a607704c8a04039e4a8483a

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1468](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=55391&buildTypeId=UT_MASTER_LINUX) is now running using a merge of 136f3bfed1e820e39a607704c8a04039e4a8483a

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1188](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=55392&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 136f3bfed1e820e39a607704c8a04039e4a8483a
Summary: Tests failed: 2 (1 new), passed: 2505, ignored: 375 Build time: 0:14:38
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.handlers.PredicatedHandlersProxyTestCase.testProxy{proxy}{spdy}: <no details avaliable>

io.undertow.websockets.jsr.test.stress.WebsocketStressTestCase.webSocketStressTestCase: <no details avaliable>

```

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1468](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=55391&buildTypeId=UT_MASTER_LINUX) outcome was **FAILURE** using a merge of 136f3bfed1e820e39a607704c8a04039e4a8483a
Summary: Tests failed: 1 (1 new), passed: 2583, ignored: 298 Build time: 0:14:41
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.handlers.PredicatedHandlersProxyTestCase.testProxy{proxy}{spdy}: <no details avaliable>

```

**Comment by stuartwdouglas** [comment]
The intermittent failures should be fixed now (I think).

**Pull request closed without merging**
