### PR TITLE
Remove the boilerplate method remove slashes

### PR DESCRIPTION
**Pull request by pgozdzikowski**

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1028](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=38220&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 76d41adc34f9d166e4cb9023b45629489f5844d1

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1028](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=38220&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 76d41adc34f9d166e4cb9023b45629489f5844d1
Summary: Tests failed: 4 (4 new), passed: 3171, ignored: 375 Build time: 0:12:54
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testDigestSuccess{proxy}: java.lang.AssertionError: expected:<200> but was:<401>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)

io.undertow.server.handlers.proxy.LoadBalancingProxyWithCustomHostSelectorTestCase.testDistributeLoadToGivenHost{proxy}: java.lang.AssertionError: expected:<200> but was:<500>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)

io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testDigestSuccess{proxy}{spdy}: java.lang.AssertionError: expected:<200> but was:<401>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)

io.undertow.server.handlers.proxy.LoadBalancingProxyWithCustomHostSelectorTestCase.testDistributeLoadToGivenHost{proxy}{spdy}: java.lang.AssertionError: expected:<200> but was:<500>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)

```

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1030](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=38226&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 76d41adc34f9d166e4cb9023b45629489f5844d1

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1030](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=38226&buildTypeId=UNDERTOW_MasterWindows) outcome was **SUCCESS** using a merge of 76d41adc34f9d166e4cb9023b45629489f5844d1
Summary: Tests passed: 3175, ignored: 375 Build time: 0:14:23

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1032](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=38244&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 76d41adc34f9d166e4cb9023b45629489f5844d1

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1032](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=38244&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 76d41adc34f9d166e4cb9023b45629489f5844d1
Summary: Tests failed: 6 (6 new), passed: 3169, ignored: 375 Build time: 0:13:04
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testDigestSuccess{proxy}{ajp}: java.lang.AssertionError: expected:<200> but was:<401>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)

io.undertow.server.handlers.proxy.LoadBalancingProxyHTTP2ViaUpgradeTestCase.testHeadersAreLowercase{proxy}{ajp}: java.lang.AssertionError: expected:<200> but was:<503>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)

io.undertow.server.handlers.proxy.LoadBalancingProxyHTTP2ViaUpgradeTestCase.testLoadShared{proxy}{ajp}: java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)

io.undertow.server.handlers.proxy.LoadBalancingProxyHTTP2ViaUpgradeTestCase.testLoadSharedWithServerShutdown{proxy}{ajp}: java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)

io.undertow.server.handlers.proxy.LoadBalancingProxyWithCustomHostSelectorTestCase.testDistributeLoadToGivenHost{proxy}{https}: java.lang.AssertionError: expected:<200> but was:<500>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)

io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testDigestSuccess{proxy}{http2-clear}: java.lang.AssertionError: expected:<200> but was:<401>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)

```

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1034](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=38257&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 76d41adc34f9d166e4cb9023b45629489f5844d1

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1034](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=38257&buildTypeId=UNDERTOW_MasterWindows) outcome was **SUCCESS** using a merge of 76d41adc34f9d166e4cb9023b45629489f5844d1
Summary: Tests passed: 3175, ignored: 375 Build time: 0:13:52

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1039](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=47977&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 76d41adc34f9d166e4cb9023b45629489f5844d1

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1039](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=47977&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 76d41adc34f9d166e4cb9023b45629489f5844d1
Summary: Tests failed: 9 (9 new), passed: 2464, ignored: 357 Build time: 0:12:53
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testDigestSuccess: <no details avaliable>

io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testDigestSuccess{proxy}: <no details avaliable>

io.undertow.servlet.test.defaultservlet.DefaultServletTestCase.testIfMoodifiedSince: <no details avaliable>

io.undertow.servlet.test.defaultservlet.DefaultServletTestCase.testIfMoodifiedSince{proxy}: <no details avaliable>

io.undertow.servlet.test.defaultservlet.DefaultServletTestCase.testIfMoodifiedSince{proxy}{ajp}: <no details avaliable>

io.undertow.servlet.test.defaultservlet.DefaultServletTestCase.testIfMoodifiedSince{proxy}{spdy}: <no details avaliable>

io.undertow.servlet.test.defaultservlet.DefaultServletTestCase.testIfMoodifiedSince{proxy}{https}: <no details avaliable>

io.undertow.servlet.test.defaultservlet.DefaultServletTestCase.testIfMoodifiedSince{proxy}{http2}: <no details avaliable>

io.undertow.servlet.test.defaultservlet.DefaultServletTestCase.testIfMoodifiedSince{proxy}{http2-clear}: <no details avaliable>

```

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1057](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=48438&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 76d41adc34f9d166e4cb9023b45629489f5844d1

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1057](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=48438&buildTypeId=UNDERTOW_MasterWindows) outcome was **SUCCESS** using a merge of 76d41adc34f9d166e4cb9023b45629489f5844d1
Summary: Tests passed: 2491, ignored: 369 Build time: 0:14:02

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1059](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=48512&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 76d41adc34f9d166e4cb9023b45629489f5844d1

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1059](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=48512&buildTypeId=UNDERTOW_MasterWindows) outcome was **SUCCESS** using a merge of 76d41adc34f9d166e4cb9023b45629489f5844d1
Summary: Tests passed: 2491, ignored: 369 Build time: 0:13:41

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1062](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=48831&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 76d41adc34f9d166e4cb9023b45629489f5844d1

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1062](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=48831&buildTypeId=UNDERTOW_MasterWindows) outcome was **SUCCESS** using a merge of 76d41adc34f9d166e4cb9023b45629489f5844d1
Summary: Tests passed: 2491, ignored: 369 Build time: 0:13:42

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1064](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=48858&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 76d41adc34f9d166e4cb9023b45629489f5844d1

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1064](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=48858&buildTypeId=UNDERTOW_MasterWindows) outcome was **SUCCESS** using a merge of 76d41adc34f9d166e4cb9023b45629489f5844d1
Summary: Tests passed: 2491, ignored: 369 Build time: 0:13:45

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1068](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=48960&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 76d41adc34f9d166e4cb9023b45629489f5844d1

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1068](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=48960&buildTypeId=UNDERTOW_MasterWindows) outcome was **SUCCESS** using a merge of 76d41adc34f9d166e4cb9023b45629489f5844d1
Summary: Tests passed: 2491, ignored: 369 Build time: 0:13:43

**Comment by stuartwdouglas** [comment]
I moved this method to the URLUtils class

**Pull request closed without merging**
