### PR TITLE
[UNDERTOW-1325] Servlet MultipartConfig attribute file-size-threshold…

### PR DESCRIPTION
**Pull request by spyrkob**
… not working

JIRA: https://issues.jboss.org/browse/UNDERTOW-1325

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
Can one of the admins verify this patch?

**Comment by stuartwdouglas** [comment]
You can't just store file data in a String, if the file contains non UTF-8 data everything will go haywire.

**Comment by spyrkob** [comment]
@stuartwdouglas sorry for delay, I was on PTO.

I pushed an updated version using a byte array to store the data

**Comment by spyrkob** [comment]
@stuartwdouglas did you have a chance to look into this? Is there anything I can do to help it along?

**Comment by spyrkob** [comment]
@fl4via looks like this was merged already in https://github.com/undertow-io/undertow/commit/3fc0c9d2f9e40c902569c34651d2ef6ec0386d7d 

I guess this PR can be closed?

**Comment by fl4via** [comment]
@spyrkob goot catch, I'm closing it

**Pull request closed without merging**
