### PR TITLE
UNDERTOW-1753 - Improve logging for Predicates

### PR DESCRIPTION
**Pull request by bdw429s**
This pull contains the implementation for this ticket:

https://issues.redhat.com/browse/UNDERTOW-1753

### CODE REVIEW

**Comment by bdw429s** [comment]
@stuartwdouglas @fl4via Here is the pull for https://issues.redhat.com/browse/UNDERTOW-1753 that we discussed on the mailing list.  There are a lot of files touched, but most of them are just adding `toString()` methods.  Please let me know if you have any questions or if you want to do a quick call to review the changes.

**Comment by stuartwdouglas** [comment]
This LGTM but I will wait for @fl4via to have a look as well.

**Comment by bdw429s** [comment]
Thanks for the review @stuartwdouglas !

**Comment by bdw429s** [comment]
@fl4via Thanks for reviewing this.  I just pushed an updated commit message.  How is that?

**Comment by bdw429s** [comment]
@fl4via @stuartwdouglas Anything else I can do here to help move this along?

**Comment by bdw429s** [comment]
@favila @stuartwdouglas  Hi guys, I have made the requested changes.  Is there anything else holding up this merge?

**Comment by fl4via** [comment]
@bdw429s Nope, I'll be soon reviewing the PRs, merging them, to release Undertow 2.2 within the next days. I'll keep you posted, and thanks again for your contribution to Undertow!

**Comment by bdw429s** [comment]
@fl4via Any update on this pull and the 2.2 release?  I've got a release of CommandBox CLI pending on this, waiting to be able to bump my Undertow version to get the latest.

**Comment by fl4via** [comment]
@bdw429s  the release will be done withing the next hours, you can count on this being released by Monday

**Comment by fl4via** [comment]
@bdw429s  I'm creating a new PR because the implementation must be applied to master branch instead of 2.0.x

**Comment by fl4via** [comment]
@bdw429s The new PR is this one: #952

**Review by fl4via — APPROVED** [review]
Approved with some minor things that needed changing, including the PR branch that should be master. See commits in #952 for more details.

**Comment by fl4via** [comment]
I'm closing this PR in favor of #952 (contains the same commit plus additional commits)

**Comment by bdw429s** [comment]
Thanks for merging @fl4via !  Should all future pulls be sent to the master branch as well?

**Pull request closed without merging**
