### PR TITLE
[UNDERTOW-1277] Clear XnioByteBufferPool.PooledByteBuffer pool when close() to avoid direct memory leaking

### PR DESCRIPTION
**Pull request by iweiss**
Issue: https://issues.jboss.org/browse/UNDERTOW-1277

DO NOT MERGE. This fix requires https://github.com/xnio/xnio/pull/142 to be merged first.

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
**Windows** [Build 2325](https://ci.wildfly.org/viewLog.html?buildId=87330&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of e0b6a051e7ce11bc945fac93f3285eb1e83fbcb5
Summary: Compilation error: Compiler (new) Build time: 00:00:14

**Comment by undertow-pull-request** [comment]
**Linux** [Build 2571](https://ci.wildfly.org/viewLog.html?buildId=87329&buildTypeId=UT_MASTER_LINUX) outcome was **FAILURE** using a merge of e0b6a051e7ce11bc945fac93f3285eb1e83fbcb5
Summary: Compilation error: Compiler (new) Build time: 00:00:19

**Comment by msfm** [comment]
This change clears all pooled ByteBuffers from a queue inside XNIO's `ByteBufferSlicePool` when `PooledByteBuffer#close()` is invoked. However, if I understand correctly, `PooledByteBuffer#close()` is invoked every time after the usage of a buffer. So, it looks to me that the change discards the pool every time (= this change detracts one of the benefits of XNIO's `ByteBufferSlicePool`).

Also, clearing pooled ByteBuffers from the queue does not mean clearing up direct buffer memory. If I understand correctly, DirectByteBuffers are different to normal memory, because they are collected by a finalizer. So, it is possible to run out of direct buffer memory even when there are heaps of DirectByteBuffers that are unreferenced and waiting to be reclaimed.

Please correct me if I'm wrong.

**Comment by iweiss** [comment]
This change uses a new method call from XNIO. The idea behind this is that `close()` by itself wasn't clearing up the direct memory allocations as expected since `close()` is not implemented, so `clean()` forcibly clears up the remaining caches, avoiding this particular use case.

**Comment by msfm** [comment]
If I understand correctly, `PooledByteBuffer#close()` just return a buffer to the pool (XNIO's `ByteBufferSlicePool` in this case) and the returned buffer will be reused from the pool in the next time. 

However, if the pool is cleared up at `PooledByteBuffer#close()` every time like your change, it means no buffer is pooled (= a new buffer needs to be allocated every request.)

That's why I think `clean()` (= clearing up the entire pool) should not be invoked in `PooledByteBuffer#close()`.

**Comment by iweiss** [comment]
The problem with this is that the buffer is allocating direct memory which is not being cleaned up on time, IIRC. It's been a while since I looked at this.

I don't know the performance impact of this change but, as far as I remember, there were no regressions.

**Comment by vvhungy** [comment]
The required PULL [xnio/xnio#142](https://github.com/xnio/xnio/pull/142) was already merged into XNIO 3.7.0. Please also merge this.

**Comment by fl4via** [comment]
Retest this please

**Comment by undertow-pull-request** [comment]
**Linux** [Build 2985](https://ci.wildfly.org/viewLog.html?buildId=145269&buildTypeId=UT_MASTER_LINUX) outcome was **FAILURE** using a merge of e0b6a051e7ce11bc945fac93f3285eb1e83fbcb5
Summary: Compilation error: Compiler (new) Build time: 00:00:22

**Comment by undertow-pull-request** [comment]
**Windows** [Build 2737](https://ci.wildfly.org/viewLog.html?buildId=145270&buildTypeId=UNDERTOW_MasterWindows) outcome was **UNKNOWN** using a merge of e0b6a051e7ce11bc945fac93f3285eb1e83fbcb5
Summary: Canceled (Error while applying patch; cannot find commit f3b08ac16a59bb3c31956d6883b50f9a20c13677 in the git://github.com/undertow-io/undertow.git repository, possible reason: refs/pull/604/merge branch was updated and the commit selected for the bui... Build time: 00:00:09

**Comment by fl4via** [comment]
@vvhungy @msfm @iweiss I'm afraid that the clean is cleaning more than necessary, I'm investigating this before merging

**Comment by fl4via** [comment]
I'm closing this PR as the fix is cleaning the pool at everytime the allocated buffer is freed.

**Pull request closed without merging**
