### PR TITLE
Websocket refator

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1558](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=69025&buildTypeId=UT_MASTER_LINUX) is now running using a merge of 7f46b6f5abbc265f9957bddb36deb24cc9e33cc3

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1256](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=69026&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 7f46b6f5abbc265f9957bddb36deb24cc9e33cc3

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1257](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=69028&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 7f46b6f5abbc265f9957bddb36deb24cc9e33cc3

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1559](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=69027&buildTypeId=UT_MASTER_LINUX) is now running using a merge of 7f46b6f5abbc265f9957bddb36deb24cc9e33cc3

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1560](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=69036&buildTypeId=UT_MASTER_LINUX) is now running using a merge of cea721e474e649b18b90f45ddf0bcea81b9256aa

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1258](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=69037&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of cea721e474e649b18b90f45ddf0bcea81b9256aa

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1558](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=69025&buildTypeId=UT_MASTER_LINUX) outcome was **FAILURE** using a merge of cea721e474e649b18b90f45ddf0bcea81b9256aa
Summary: Tests failed: 3 (3 new), passed: 2703, ignored: 322 Build time: 00:14:39
### Failed tests
```
io.undertow.websockets.extensions.WebSocketExtensionBasicTestCase.testExtensionsHeaders: java.lang.AssertionError: expected:<Hello, World!> but was:<null>
	at io.undertow.websockets.extensions.WebSocketExtensionBasicTestCase.testExtensionsHeaders(WebSocketExtensionBasicTestCase.java:329)
------- Stderr: -------
05:02:35,640 INFO  (main) [org.xnio] <Xnio.java:93> XNIO version 3.3.1.Final
05:02:35,813 INFO  (main) [org.xnio.nio] <NioXnio.java:55> XNIO NIO Implementation Version 3.3.1.Final
05:02:36,150 INFO  (XNIO-1 I/O-1) [io.undertow.websockets.core.extension] <WebSocketExtensionBasicTestCase.java:76> onConnect() 
05:02:36,151 INFO  (XNIO-1 I/O-1) [io.undertow.request.dump] <DebugExtensionsHeaderHandler.java:87> 
--- REQUEST ---
Sec-WebSocket-Extensions: permessage-deflate; client_no_context_takeover; client_max_window_bits

--- RESPONSE ---
Sec-WebSocket-Extensions: permessage-deflate; client_no_context_takeover

05:02:36,169 INFO  (XNIO-1 I/O-1) [io.undertow.websockets.core.extension] <DebugExtensionsListener.java:109> onError(): UT002044: Compressed message payload is corrupted


io.undertow.websockets.extensions.WebSocketExtensionBasicTestCase.testExtensionsHeaders{proxy}: java.lang.AssertionError: expected:<Hello, World!> but was:<null>
	at io.undertow.websockets.extensions.WebSocketExtensionBasicTestCase.testExtensionsHeaders(WebSocketExtensionBasicTestCase.java:329)
------- Stderr: -------
05:03:38,219 INFO  (main) [org.xnio] <Xnio.java:93> XNIO version 3.3.1.Final
05:03:38,282 INFO  (main) [org.xnio.nio] <NioXnio.java:55> XNIO NIO Implementation Version 3.3.1.Final
05:03:38,528 INFO  (XNIO-1 I/O-1) [io.undertow.websockets.core.extension] <WebSocketExtensionBasicTestCase.java:76> onConnect() 
05:03:38,530 INFO  (XNIO-1 I/O-1) [io.undertow.request.dump] <DebugExtensionsHeaderHandler.java:87> 
--- REQUEST ---
Sec-WebSocket-Extensions: permessage-deflate; client_no_context_takeover; client_max_window_bits

--- RESPONSE ---
Sec-WebSocket-Extensions: permessage-deflate; client_no_context_takeover

05:03:38,561 INFO  (XNIO-1 I/O-1) [io.undertow.websockets.core.extension] <DebugExtensionsListener.java:109> onError(): UT002044: Compressed message payload is corrupted


io.undertow.websockets.extensions.WebSocketExtensionBasicTestCase.testExtensionsHeaders{proxy}{https}: java.lang.AssertionError: expected:<Hello, World!> but was:<null>
	at io.undertow.websockets.extensions.WebSocketExtensionBasicTestCase.testExtensionsHeaders(WebSocketExtensionBasicTestCase.java:329)
------- Stderr: -------
05:06:12,546 INFO  (main) [org.xnio] <Xnio.java:93> XNIO version 3.3.1.Final
05:06:12,607 INFO  (main) [org.xnio.nio] <NioXnio.java:55> XNIO NIO Implementation Version 3.3.1.Final
05:06:13,176 INFO  (XNIO-1 I/O-1) [io.undertow.websockets.core.extension] <WebSocketExtensionBasicTestCase.java:76> onConnect() 
05:06:13,178 INFO  (XNIO-1 I/O-1) [io.undertow.request.dump] <DebugExtensionsHeaderHandler.java:87> 
--- REQUEST ---
Sec-WebSocket-Extensions: permessage-deflate; client_no_context_takeover; client_max_window_bits

--- RESPONSE ---
Sec-WebSocket-Extensions: permessage-deflate; client_no_context_takeover

05:06:13,206 INFO  (XNIO-1 I/O-1) [io.undertow.websockets.core.extension] <DebugExtensionsListener.java:109> onError(): UT002044: Compressed message payload is corrupted


```

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1256](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=69026&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of cea721e474e649b18b90f45ddf0bcea81b9256aa
Summary: Tests failed: 3 (3 new), passed: 2626, ignored: 399 Build time: 00:15:42
### Failed tests
```
io.undertow.websockets.extensions.WebSocketExtensionBasicTestCase.testExtensionsHeaders: java.lang.AssertionError: expected:<Hello, World!> but was:<null>
	at io.undertow.websockets.extensions.WebSocketExtensionBasicTestCase.testExtensionsHeaders(WebSocketExtensionBasicTestCase.java:329)
------- Stderr: -------
05:02:53,615 INFO  (main) [org.xnio] <Xnio.java:93> XNIO version 3.3.1.Final
05:02:53,686 INFO  (main) [org.xnio.nio] <NioXnio.java:55> XNIO NIO Implementation Version 3.3.1.Final
05:02:53,936 INFO  (XNIO-1 I/O-1) [io.undertow.websockets.core.extension] <WebSocketExtensionBasicTestCase.java:76> onConnect() 
05:02:53,937 INFO  (XNIO-1 I/O-1) [io.undertow.request.dump] <DebugExtensionsHeaderHandler.java:87> 
--- REQUEST ---
Sec-WebSocket-Extensions: permessage-deflate; client_no_context_takeover; client_max_window_bits

--- RESPONSE ---
Sec-WebSocket-Extensions: permessage-deflate; client_no_context_takeover

05:02:53,953 INFO  (XNIO-1 I/O-1) [io.undertow.websockets.core.extension] <DebugExtensionsListener.java:109> onError(): UT002044: Compressed message payload is corrupted


io.undertow.websockets.extensions.WebSocketExtensionBasicTestCase.testExtensionsHeaders{proxy}: java.lang.AssertionError: expected:<Hello, World!> but was:<null>
	at io.undertow.websockets.extensions.WebSocketExtensionBasicTestCase.testExtensionsHeaders(WebSocketExtensionBasicTestCase.java:329)
------- Stderr: -------
05:04:09,037 INFO  (main) [org.xnio] <Xnio.java:93> XNIO version 3.3.1.Final
05:04:09,108 INFO  (main) [org.xnio.nio] <NioXnio.java:55> XNIO NIO Implementation Version 3.3.1.Final
05:04:09,414 INFO  (XNIO-1 I/O-1) [io.undertow.websockets.core.extension] <WebSocketExtensionBasicTestCase.java:76> onConnect() 
05:04:09,416 INFO  (XNIO-1 I/O-1) [io.undertow.request.dump] <DebugExtensionsHeaderHandler.java:87> 
--- REQUEST ---
Sec-WebSocket-Extensions: permessage-deflate; client_no_context_takeover; client_max_window_bits

--- RESPONSE ---
Sec-WebSocket-Extensions: permessage-deflate; client_no_context_takeover

05:04:09,452 INFO  (XNIO-1 I/O-1) [io.undertow.websockets.core.extension] <DebugExtensionsListener.java:109> onError(): UT002044: Compressed message payload is corrupted


io.undertow.websockets.extensions.WebSocketExtensionBasicTestCase.testExtensionsHeaders{proxy}{https}: java.lang.AssertionError: expected:<Hello, World!> but was:<null>
	at io.undertow.websockets.extensions.WebSocketExtensionBasicTestCase.testExtensionsHeaders(WebSocketExtensionBasicTestCase.java:329)
------- Stderr: -------
05:07:13,101 INFO  (main) [org.xnio] <Xnio.java:93> XNIO version 3.3.1.Final
05:07:13,177 INFO  (main) [org.xnio.nio] <NioXnio.java:55> XNIO NIO Implementation Version 3.3.1.Final
05:07:13,728 INFO  (XNIO-1 I/O-1) [io.undertow.websockets.core.extension] <WebSocketExtensionBasicTestCase.java:76> onConnect() 
05:07:13,730 INFO  (XNIO-1 I/O-1) [io.undertow.request.dump] <DebugExtensionsHeaderHandler.java:87> 
--- REQUEST ---
Sec-WebSocket-Extensions: permessage-deflate; client_no_context_takeover; client_max_window_bits

--- RESPONSE ---
Sec-WebSocket-Extensions: permessage-deflate; client_no_context_takeover

05:07:13,766 INFO  (XNIO-1 I/O-1) [io.undertow.websockets.core.extension] <DebugExtensionsListener.java:109> onError(): UT002044: Compressed message payload is corrupted


```

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1559](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=69027&buildTypeId=UT_MASTER_LINUX) outcome was **FAILURE** using a merge of cea721e474e649b18b90f45ddf0bcea81b9256aa
Summary: Tests failed: 3, passed: 2703, ignored: 322 Build time: 00:15:49
### Failed tests
```
io.undertow.websockets.extensions.WebSocketExtensionBasicTestCase.testExtensionsHeaders: java.lang.AssertionError: expected:<Hello, World!> but was:<null>
	at io.undertow.websockets.extensions.WebSocketExtensionBasicTestCase.testExtensionsHeaders(WebSocketExtensionBasicTestCase.java:329)
------- Stderr: -------
05:00:34,327 INFO  (main) [org.xnio] <Xnio.java:93> XNIO version 3.3.1.Final
05:00:34,552 INFO  (main) [org.xnio.nio] <NioXnio.java:55> XNIO NIO Implementation Version 3.3.1.Final
05:00:34,873 INFO  (XNIO-1 I/O-1) [io.undertow.websockets.core.extension] <WebSocketExtensionBasicTestCase.java:76> onConnect() 
05:00:34,876 INFO  (XNIO-1 I/O-1) [io.undertow.request.dump] <DebugExtensionsHeaderHandler.java:87> 
--- REQUEST ---
Sec-WebSocket-Extensions: permessage-deflate; client_no_context_takeover; client_max_window_bits

--- RESPONSE ---
Sec-WebSocket-Extensions: permessage-deflate; client_no_context_takeover

05:00:34,904 INFO  (XNIO-1 I/O-1) [io.undertow.websockets.core.extension] <DebugExtensionsListener.java:109> onError(): UT002044: Compressed message payload is corrupted


io.undertow.websockets.extensions.WebSocketExtensionBasicTestCase.testExtensionsHeaders{proxy}: java.lang.AssertionError: expected:<Hello, World!> but was:<null>
	at io.undertow.websockets.extensions.WebSocketExtensionBasicTestCase.testExtensionsHeaders(WebSocketExtensionBasicTestCase.java:329)
------- Stderr: -------
05:01:36,842 INFO  (main) [org.xnio] <Xnio.java:93> XNIO version 3.3.1.Final
05:01:36,914 INFO  (main) [org.xnio.nio] <NioXnio.java:55> XNIO NIO Implementation Version 3.3.1.Final
05:01:37,177 INFO  (XNIO-1 I/O-1) [io.undertow.websockets.core.extension] <WebSocketExtensionBasicTestCase.java:76> onConnect() 
05:01:37,179 INFO  (XNIO-1 I/O-1) [io.undertow.request.dump] <DebugExtensionsHeaderHandler.java:87> 
--- REQUEST ---
Sec-WebSocket-Extensions: permessage-deflate; client_no_context_takeover; client_max_window_bits

--- RESPONSE ---
Sec-WebSocket-Extensions: permessage-deflate; client_no_context_takeover

05:01:37,212 INFO  (XNIO-1 I/O-1) [io.undertow.websockets.core.extension] <DebugExtensionsListener.java:109> onError(): UT002044: Compressed message payload is corrupted


io.undertow.websockets.extensions.WebSocketExtensionBasicTestCase.testExtensionsHeaders{proxy}{https}: java.lang.AssertionError: expected:<Hello, World!> but was:<null>
	at io.undertow.websockets.extensions.WebSocketExtensionBasicTestCase.testExtensionsHeaders(WebSocketExtensionBasicTestCase.java:329)
------- Stderr: -------
05:04:16,821 INFO  (main) [org.xnio] <Xnio.java:93> XNIO version 3.3.1.Final
05:04:16,883 INFO  (main) [org.xnio.nio] <NioXnio.java:55> XNIO NIO Implementation Version 3.3.1.Final
05:04:17,455 INFO  (XNIO-1 I/O-1) [io.undertow.websockets.core.extension] <WebSocketExtensionBasicTestCase.java:76> onConnect() 
05:04:17,457 INFO  (XNIO-1 I/O-1) [io.undertow.request.dump] <DebugExtensionsHeaderHandler.java:87> 
--- REQUEST ---
Sec-WebSocket-Extensions: permessage-deflate; client_no_context_takeover; client_max_window_bits

--- RESPONSE ---
Sec-WebSocket-Extensions: permessage-deflate; client_no_context_takeover

05:04:17,487 INFO  (XNIO-1 I/O-1) [io.undertow.websockets.core.extension] <DebugExtensionsListener.java:109> onError(): UT002044: Compressed message payload is corrupted


```

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1257](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=69028&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of cea721e474e649b18b90f45ddf0bcea81b9256aa
Summary: Tests failed: 3, passed: 2626, ignored: 399 Build time: 00:16:12
### Failed tests
```
io.undertow.websockets.extensions.WebSocketExtensionBasicTestCase.testExtensionsHeaders: java.lang.AssertionError: expected:<Hello, World!> but was:<null>
	at io.undertow.websockets.extensions.WebSocketExtensionBasicTestCase.testExtensionsHeaders(WebSocketExtensionBasicTestCase.java:329)
------- Stderr: -------
05:05:36,675 INFO  (main) [org.xnio] <Xnio.java:93> XNIO version 3.3.1.Final
05:05:37,127 INFO  (main) [org.xnio.nio] <NioXnio.java:55> XNIO NIO Implementation Version 3.3.1.Final
05:05:37,759 INFO  (XNIO-1 I/O-1) [io.undertow.websockets.core.extension] <WebSocketExtensionBasicTestCase.java:76> onConnect() 
05:05:37,760 INFO  (XNIO-1 I/O-1) [io.undertow.request.dump] <DebugExtensionsHeaderHandler.java:87> 
--- REQUEST ---
Sec-WebSocket-Extensions: permessage-deflate; client_no_context_takeover; client_max_window_bits

--- RESPONSE ---
Sec-WebSocket-Extensions: permessage-deflate; client_no_context_takeover

05:05:37,780 INFO  (XNIO-1 I/O-1) [io.undertow.websockets.core.extension] <DebugExtensionsListener.java:109> onError(): UT002044: Compressed message payload is corrupted


io.undertow.websockets.extensions.WebSocketExtensionBasicTestCase.testExtensionsHeaders{proxy}: java.lang.AssertionError: expected:<Hello, World!> but was:<null>
	at io.undertow.websockets.extensions.WebSocketExtensionBasicTestCase.testExtensionsHeaders(WebSocketExtensionBasicTestCase.java:329)
------- Stderr: -------
05:06:56,115 INFO  (main) [org.xnio] <Xnio.java:93> XNIO version 3.3.1.Final
05:06:56,188 INFO  (main) [org.xnio.nio] <NioXnio.java:55> XNIO NIO Implementation Version 3.3.1.Final
05:06:56,520 INFO  (XNIO-1 I/O-1) [io.undertow.websockets.core.extension] <WebSocketExtensionBasicTestCase.java:76> onConnect() 
05:06:56,524 INFO  (XNIO-1 I/O-1) [io.undertow.request.dump] <DebugExtensionsHeaderHandler.java:87> 
--- REQUEST ---
Sec-WebSocket-Extensions: permessage-deflate; client_no_context_takeover; client_max_window_bits

--- RESPONSE ---
Sec-WebSocket-Extensions: permessage-deflate; client_no_context_takeover

05:06:56,574 INFO  (XNIO-1 I/O-1) [io.undertow.websockets.core.extension] <DebugExtensionsListener.java:109> onError(): UT002044: Compressed message payload is corrupted


io.undertow.websockets.extensions.WebSocketExtensionBasicTestCase.testExtensionsHeaders{proxy}{https}: java.lang.AssertionError: expected:<Hello, World!> but was:<null>
	at io.undertow.websockets.extensions.WebSocketExtensionBasicTestCase.testExtensionsHeaders(WebSocketExtensionBasicTestCase.java:329)
------- Stderr: -------
05:10:02,456 INFO  (main) [org.xnio] <Xnio.java:93> XNIO version 3.3.1.Final
05:10:02,530 INFO  (main) [org.xnio.nio] <NioXnio.java:55> XNIO NIO Implementation Version 3.3.1.Final
05:10:03,084 INFO  (XNIO-1 I/O-1) [io.undertow.websockets.core.extension] <WebSocketExtensionBasicTestCase.java:76> onConnect() 
05:10:03,086 INFO  (XNIO-1 I/O-1) [io.undertow.request.dump] <DebugExtensionsHeaderHandler.java:87> 
--- REQUEST ---
Sec-WebSocket-Extensions: permessage-deflate; client_no_context_takeover; client_max_window_bits

--- RESPONSE ---
Sec-WebSocket-Extensions: permessage-deflate; client_no_context_takeover

05:10:03,119 INFO  (XNIO-1 I/O-1) [io.undertow.websockets.core.extension] <DebugExtensionsListener.java:109> onError(): UT002044: Compressed message payload is corrupted


```

**Comment by stuartwdouglas** [comment]
Retest this please

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1560](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=69036&buildTypeId=UT_MASTER_LINUX) outcome was **SUCCESS** using a merge of cea721e474e649b18b90f45ddf0bcea81b9256aa
Summary: Tests passed: 2706, ignored: 322 Build time: 00:14:55

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1258](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=69037&buildTypeId=UNDERTOW_MasterWindows) outcome was **SUCCESS** using a merge of cea721e474e649b18b90f45ddf0bcea81b9256aa
Summary: Tests passed: 2629, ignored: 399 Build time: 00:15:49

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1259](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=69039&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of cea721e474e649b18b90f45ddf0bcea81b9256aa

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1561](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=69038&buildTypeId=UT_MASTER_LINUX) is now running using a merge of cea721e474e649b18b90f45ddf0bcea81b9256aa

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1561](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=69038&buildTypeId=UT_MASTER_LINUX) outcome was **SUCCESS** using a merge of cea721e474e649b18b90f45ddf0bcea81b9256aa
Summary: Tests passed: 2706, ignored: 322 Build time: 00:14:10

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1259](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=69039&buildTypeId=UNDERTOW_MasterWindows) outcome was **SUCCESS** using a merge of cea721e474e649b18b90f45ddf0bcea81b9256aa
Summary: Tests passed: 2629, ignored: 399 Build time: 00:15:02

**Pull request merged**
