### PR TITLE
[UNDERTOW-2230] Add priority to HandlerBuilder to override internal h…

### PR DESCRIPTION
**Pull request by xjusko**
…andlers with predicate language
https://issues.redhat.com/browse/UNDERTOW-2230

### CODE REVIEW

**Comment by xjusko** [comment]
Hi @fl4via, can I get a review on this PR?

**Comment by xjusko** [comment]
Hi @fl4via , could you please review my PR? Thanks.

**Comment by baranowb** [comment]
Looks good, again, why 1 if existing impl has it set to 0

**Comment by xjusko** [comment]
As in the other PR, I probably misunderstood the issue description. Now it should be implemented as it was described in the jira issue.

**Pull request merged**
