### PR TITLE
UNDERTOW-958 ensure any jsessionid in URL is updated upon login

### PR DESCRIPTION
**Pull request by panossot**
[JBEAP-8386] : https://issues.jboss.org/browse/JBEAP-8386

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
**Linux** [Build 96](https://ci.wildfly.org/viewLog.html?buildId=43667&buildTypeId=UNDERTOW_13xLinux) outcome was **FAILURE** using a merge of 85110b48828be24f43833325d565dccc6638bbe5
Summary: Execution timeout; tests passed: 27, ignored: 1 Build time: 01:00:02

**Comment by panossot** [comment]
Retest this please.

**Comment by undertow-pull-request** [comment]
**Linux** [Build 97](https://ci.wildfly.org/viewLog.html?buildId=43681&buildTypeId=UNDERTOW_13xLinux) outcome was **FAILURE** using a merge of 85110b48828be24f43833325d565dccc6638bbe5
Summary: Execution timeout; tests passed: 27, ignored: 1 Build time: 01:00:12

**Comment by panossot** [comment]
Tests pass locally.

**Pull request merged**
