### PR TITLE
UNDERTOW-396 HttpServletResponseImpl#encodeURL() doesn't work

### PR DESCRIPTION
**Pull request by lbtc-xxx**

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
**Windows** [Build 992](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=36847&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 21e39f41650e9add259b50f96d5736655aeb1c1c

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1425](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=36851&buildTypeId=UT_MASTER_LINUX) is now running using a merge of 21e39f41650e9add259b50f96d5736655aeb1c1c

**Comment by undertow-pull-request** [comment]
**Windows** [Build 992](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=36847&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 21e39f41650e9add259b50f96d5736655aeb1c1c
Summary: Tests failed: 5 (5 new), passed: 3155, ignored: 375 Build time: 0:13:05
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testNonceCountReUse{proxy}{ajp}: java.lang.AssertionError: expected:<200> but was:<401>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)

io.undertow.server.security.DigestAuthenticationAuthTestCase.testDigestSuccess{proxy}{https}: java.lang.AssertionError: expected:<200> but was:<401>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)

io.undertow.server.security.DigestAuthenticationAuthTestCase.testNonceCountReUse{proxy}{https}: java.lang.AssertionError: expected:<200> but was:<401>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)

io.undertow.server.handlers.proxy.LoadBalancingProxyWithCustomHostSelectorTestCase.testDistributeLoadToGivenHost{proxy}{https}: java.lang.AssertionError: expected:<200> but was:<500>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)

io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testDigestSuccess{proxy}{http2-clear}: java.lang.AssertionError: expected:<200> but was:<401>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)

```

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1425](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=36851&buildTypeId=UT_MASTER_LINUX) outcome was **SUCCESS** using a merge of 21e39f41650e9add259b50f96d5736655aeb1c1c
Summary: Tests passed: 3237, ignored: 298 Build time: 0:15:19

**Comment by undertow-pull-request** [comment]
**Windows** [Build 993](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=36853&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 00a09a7438d3f8c84ed9d26293fbc6fdcb7200b6

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1426](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=36857&buildTypeId=UT_MASTER_LINUX) is now running using a merge of 00a09a7438d3f8c84ed9d26293fbc6fdcb7200b6

**Comment by undertow-pull-request** [comment]
**Windows** [Build 993](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=36853&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 00a09a7438d3f8c84ed9d26293fbc6fdcb7200b6
Summary: Tests failed: 9 (8 new), passed: 3151, ignored: 375 Build time: 0:12:47
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testNonceCountReUse: java.lang.AssertionError: expected:<200> but was:<401>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)

io.undertow.servlet.test.defaultservlet.DefaultServletTestCase.testIfMoodifiedSince: java.lang.AssertionError: expected:<304> but was:<200>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)

io.undertow.servlet.test.defaultservlet.DefaultServletTestCase.testIfMoodifiedSince{proxy}: java.lang.AssertionError: expected:<304> but was:<200>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)

io.undertow.servlet.test.defaultservlet.DefaultServletTestCase.testIfMoodifiedSince{proxy}{ajp}: java.lang.AssertionError: expected:<304> but was:<200>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)

io.undertow.servlet.test.defaultservlet.DefaultServletTestCase.testIfMoodifiedSince{proxy}{spdy}: java.lang.AssertionError: expected:<304> but was:<200>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)

io.undertow.servlet.test.defaultservlet.DefaultServletTestCase.testIfMoodifiedSince{proxy}{https}: java.lang.AssertionError: expected:<304> but was:<200>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)

io.undertow.servlet.test.defaultservlet.DefaultServletTestCase.testIfMoodifiedSince{proxy}{http2}: java.lang.AssertionError: expected:<304> but was:<200>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)

io.undertow.servlet.test.defaultservlet.DefaultServletTestCase.testIfMoodifiedSince{proxy}{http2-clear}: java.lang.AssertionError: expected:<304> but was:<200>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)

io.undertow.server.security.DigestAuthenticationAuthTestCase.testNonceCountReUse{proxy}{https}: java.lang.AssertionError: expected:<200> but was:<401>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)

```

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1426](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=36857&buildTypeId=UT_MASTER_LINUX) outcome was **FAILURE** using a merge of 00a09a7438d3f8c84ed9d26293fbc6fdcb7200b6
Summary: Tests failed: 1 (1 new), passed: 3236, ignored: 298 Build time: 0:15:16
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.websockets.jsr.test.BinaryEndpointTest.testBytesOnMessage: java.lang.AssertionError: actual array was null
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.internal.ComparisonCriteria.assertArraysAreSameLength(ComparisonCriteria.java:66)

```

**Comment by stuartwdouglas** [comment]
I have fixed this in a different way that does not require SPI changes. Can you verify that these changes fix the issue for you?

**Comment by lbtc-xxx** [comment]
Thanks, it solved the problem I reported.

But, I guess there is an another problem I just found.

I think HttpServletRequest#getCookies() should return null when there is no JSESSIONID in request, but Undertow returns newly created cookie for that. I guess invocation of getRequestCookies().put() in SessionCookieConfig#setSessionId() should be deleted. shall I open an new issue for that?

HttpServletRequest#getCookies() returns a cookie while there's no cookies. source of testing Servlet is here: https://github.com/lbtc-xxx/jsessionid/blob/master/src/main/java/hoge/SessionServlet.java

cookies

**Comment by lbtc-xxx** [comment]
p.s. my PR fixes the problem about HttpServletRequest#getCookies().

**Comment by stuartwdouglas** [comment]
This was fixed in a different way (the getCookies() issue was fixed in 33dda2a)

**Pull request closed without merging**
