### PR TITLE
UNDERTOW-1526 UndertowOutputStream.resetBuffer resets bytes written

### PR DESCRIPTION
**Pull request by carterkozak**

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
Can one of the admins verify this patch?

**Comment by stuartwdouglas** [comment]
This is ok to test

**Comment by undertow-pull-request** [comment]
**Linux** [Build 2994](https://ci.wildfly.org/viewLog.html?buildId=147435&buildTypeId=UT_MASTER_LINUX) outcome was **FAILURE** using a merge of 445fcf3d82cd1f9d5cbb75d49498a4a679b84c7e
Summary: Tests failed: 57 (35 new), passed: 3397, ignored: 623 Build time: 00:39:41
### Failed tests
```
io.undertow.server.NewlineInHeadersTestCase.testNewlineInHeaders[proxy]: java.lang.NoClassDefFoundError: io/undertow/server/NewlineInHeadersTestCase$1
	at io.undertow.server.NewlineInHeadersTestCase.testNewlineInHeaders(NewlineInHeadersTestCase.java:47)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:528)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:104)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:301)
Caused by: java.lang.ClassNotFoundException: io.undertow.server.NewlineInHeadersTestCase$1
	at java.net.URLClassLoader$1.run(URLClassLoader.java:370)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 38 more
Caused by: java.io.FileNotFoundException: /store/work/tc-work/b455211ade1ff869/core/target/test-classes/io/undertow/server/NewlineInHeadersTestCase$1.class (Too many open files)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at sun.misc.URLClassPath$FileLoader$1.getInputStream(URLClassPath.java:1288)
	at sun.misc.Resource.cachedInputStream(Resource.java:77)
	at sun.misc.Resource.getByteBuffer(Resource.java:160)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:454)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	... 44 more


io.undertow.protocols.http2.HpackSpecExamplesUnitTestCase.testExample_D_2_112: java.lang.NoClassDefFoundError: io/undertow/protocols/http2/HpackSpecExamplesUnitTestCase$HeaderMapEmitter
	at io.undertow.protocols.http2.HpackSpecExamplesUnitTestCase.testExample_D_2_112(HpackSpecExamplesUnitTestCase.java:380)


io.undertow.server.handlers.AllowedMethodsTestCase.testDisallowedMethods[proxy]: java.lang.NoClassDefFoundError: io/undertow/server/handlers/DisallowedMethodsHandler
	at io.undertow.server.handlers.AllowedMethodsTestCase.testDisallowedMethods(AllowedMethodsTestCase.java:70)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:528)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:104)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:301)
Caused by: java.lang.ClassNotFoundException: io.undertow.server.handlers.DisallowedMethodsHandler
	at java.net.URLClassLoader$1.run(URLClassLoader.java:370)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 38 more
Caused by: java.io.FileNotFoundException: /store/work/tc-work/b455211ade1ff869/core/target/classes/io/undertow/server/handlers/DisallowedMethodsHandler.class (Too many open files)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at sun.misc.URLClassPath$FileLoader$1.getInputStream(URLClassPath.java:1288)
	at sun.misc.Resource.cachedInputStream(Resource.java:77)
	at sun.misc.Resource.getByteBuffer(Resource.java:160)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:454)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	... 44 more


io.undertow.protocols.http2.HpackSpecExamplesUnitTestCase.testExample_D_2_3: java.lang.NoClassDefFoundError: io/undertow/protocols/http2/HpackSpecExamplesUnitTestCase$HeaderMapEmitter
	at io.undertow.protocols.http2.HpackSpecExamplesUnitTestCase.testExample_D_2_3(HpackSpecExamplesUnitTestCase.java:75)


io.undertow.server.handlers.JDBCLogDatabaseTestCase.testSingleLogMessageToDatabase[proxy]: java.lang.NoClassDefFoundError: io/undertow/server/handlers/JDBCLogDatabaseTestCase$1
	at io.undertow.server.handlers.JDBCLogDatabaseTestCase.<clinit>(JDBCLogDatabaseTestCase.java:61)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:528)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:104)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:301)
Caused by: java.lang.ClassNotFoundException: io.undertow.server.handlers.JDBCLogDatabaseTestCase$1
	at java.net.URLClassLoader$1.run(URLClassLoader.java:370)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 37 more
Caused by: java.io.FileNotFoundException: /store/work/tc-work/b455211ade1ff869/core/target/test-classes/io/undertow/server/handlers/JDBCLogDatabaseTestCase$1.class (Too many open files)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at sun.misc.URLClassPath$FileLoader$1.getInputStream(URLClassPath.java:1288)
	at sun.misc.Resource.cachedInputStream(Resource.java:77)
	at sun.misc.Resource.getByteBuffer(Resource.java:160)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:454)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	... 43 more


io.undertow.protocols.http2.HpackSpecExamplesUnitTestCase.testExample_D_3: java.lang.NoClassDefFoundError: io/undertow/protocols/http2/HpackSpecExamplesUnitTestCase$HeaderMapEmitter
	at io.undertow.protocols.http2.HpackSpecExamplesUnitTestCase.testExample_D_3(HpackSpecExamplesUnitTestCase.java:103)


io.undertow.server.handlers.IPAddressAccessControlHandlerUnitTestCase.testIPv4ExactMatch: java.lang.NoClassDefFoundError: io/undertow/server/handlers/IPAddressAccessControlHandler$ExactIpV4PeerMatch
	at io.undertow.server.handlers.IPAddressAccessControlHandler.addIpV4ExactMatch(IPAddressAccessControlHandler.java:305)
	at io.undertow.server.handlers.IPAddressAccessControlHandler.addRule(IPAddressAccessControlHandler.java:195)
	at io.undertow.server.handlers.IPAddressAccessControlHandler.addAllow(IPAddressAccessControlHandler.java:166)
	at io.undertow.server.handlers.IPAddressAccessControlHandlerUnitTestCase.testIPv4ExactMatch(IPAddressAccessControlHandlerUnitTestCase.java:43)
Caused by: java.lang.ClassNotFoundException: io.undertow.server.handlers.IPAddressAccessControlHandler$ExactIpV4PeerMatch
	at java.net.URLClassLoader$1.run(URLClassLoader.java:370)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 more
Caused by: java.io.FileNotFoundException: /store/work/tc-work/b455211ade1ff869/core/target/classes/io/undertow/server/handlers/IPAddressAccessControlHandler$ExactIpV4PeerMatch.class (Too many open files)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at sun.misc.URLClassPath$FileLoader$1.getInputStream(URLClassPath.java:1288)
	at sun.misc.Resource.cachedInputStream(Resource.java:77)
	at sun.misc.Resource.getByteBuffer(Resource.java:160)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:454)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	... 45 more


io.undertow.protocols.http2.HpackSpecExamplesUnitTestCase.testExample_D_5: java.lang.NoClassDefFoundError: io/undertow/protocols/http2/HpackSpecExamplesUnitTestCase$HeaderMapEmitter
	at io.undertow.protocols.http2.HpackSpecExamplesUnitTestCase.testExample_D_5(HpackSpecExamplesUnitTestCase.java:216)


io.undertow.predicate.PredicateParsingTestCase.testPredicateContextVariable: java.util.ServiceConfigurationError: io.undertow.predicate.PredicateBuilder: Error reading configuration file
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.parse(ServiceLoader.java:309)
	at java.util.ServiceLoader.access$200(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:357)
	at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393)
	at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474)
	at io.undertow.server.handlers.builder.PredicatedHandlersParser.loadPredicateBuilders(PredicatedHandlersParser.java:295)
	at io.undertow.server.handlers.builder.PredicatedHandlersParser.parsePredicate(PredicatedHandlersParser.java:98)
	at io.undertow.predicate.PredicateParser.parse(PredicateParser.java:53)
	at io.undertow.predicate.PredicateParsingTestCase.testPredicateContextVariable(PredicateParsingTestCase.java:68)
Caused by: java.io.FileNotFoundException: /store/work/tc-work/b455211ade1ff869/core/target/classes/META-INF/services/io.undertow.predicate.PredicateBuilder (Too many open files)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at java.net.URL.openStream(URL.java:1045)
	at java.util.ServiceLoader.parse(ServiceLoader.java:304)
	... 43 more
------- Stderr: -------
15:54:19,313 WARN  (main) [io.undertow] <PredicatedHandlersParser.java:460> UT005060: Predicate regex[pattern="/publicdb/(.*?)/.*", value="%R", full-match=false] and equals[%{i,username}, ${1}] uses old style square braces to define predicates, which will be removed in a future release. predicate[value] should be changed to predicate(value)
15:54:19,313 WARN  (main) [io.undertow] <PredicatedHandlersParser.java:460> UT005060: Predicate regex[pattern="/publicdb/(.*?)/.*", value="%R", full-match=false] and equals[%{i,username}, ${1}] uses old style square braces to define predicates, which will be removed in a future release. predicate[value] should be changed to predicate(value)


io.undertow.server.handlers.IPAddressAccessControlHandlerUnitTestCase.testIPv6SlashMatch: java.lang.NoClassDefFoundError: io/undertow/server/handlers/IPAddressAccessControlHandler$ExactIpV6PeerMatch
	at io.undertow.server.handlers.IPAddressAccessControlHandler.addIpV6ExactMatch(IPAddressAccessControlHandler.java:299)
	at io.undertow.server.handlers.IPAddressAccessControlHandler.addRule(IPAddressAccessControlHandler.java:201)
	at io.undertow.server.handlers.IPAddressAccessControlHandler.addAllow(IPAddressAccessControlHandler.java:166)
	at io.undertow.server.handlers.IPAddressAccessControlHandlerUnitTestCase.testIPv6SlashMatch(IPAddressAccessControlHandlerUnitTestCase.java:106)


io.undertow.server.handlers.LotsOfHeadersRequestTestCase.testLotsOfHeadersInRequest_Default_Ok[proxy]: java.net.SocketException: Too many open files
	at java.net.Socket.createImpl(Socket.java:460)
	at java.net.Socket.getImpl(Socket.java:520)
	at java.net.Socket.setSoTimeout(Socket.java:1141)
	at org.apache.http.conn.scheme.PlainSocketFactory.connectSocket(PlainSocketFactory.java:120)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:326)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at io.undertow.server.handlers.LotsOfHeadersRequestTestCase.testLotsOfHeadersInRequest_Default_Ok(LotsOfHeadersRequestTestCase.java:109)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:528)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:104)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:301)



##### there are 47 more failed tests, see build details
```

**Comment by undertow-pull-request** [comment]
**Windows** [Build 2746](https://ci.wildfly.org/viewLog.html?buildId=147436&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 445fcf3d82cd1f9d5cbb75d49498a4a679b84c7e
Summary: Tests failed: 1, passed: 3384, ignored: 710 Build time: 00:44:00
### Failed tests
```
io.undertow.server.handlers.ReceiverTestCase.testAsyncReceiveWholeBytesFailed[proxy][http2]: java.lang.AssertionError
	at io.undertow.server.handlers.ReceiverTestCase.testAsyncReceiveWholeBytesFailed(ReceiverTestCase.java:194)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:528)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:104)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:301)
------- Stderr: -------
16:03:34,525 DEBUG (XNIO-1 I/O-7) [io.undertow.server.handlers.proxy] <ProxyHandler.java:549> Sending request ClientRequest{path='/fullbytes', method=POST, protocol=HTTP/1.1} to target localhost/127.0.0.1:8888 for exchange HttpServerExchange{ POST /fullbytes}
16:03:34,525 DEBUG (XNIO-1 I/O-7) [io.undertow.server.handlers.proxy] <ProxyHandler.java:566> Sent request ClientRequest{path='/fullbytes', method=POST, protocol=HTTP/1.1} to target 127.0.0.1 for exchange HttpServerExchange{ POST /fullbytes}
16:03:34,569 ERROR (XNIO-1 I/O-7) [io.undertow.proxy] <ProxyHandler.java:662> UT005028: Proxy request to /fullbytes failed: java.nio.channels.ClosedChannelException
	at io.undertow.client.http2.Http2ClientConnection$1.handleEvent(Http2ClientConnection.java:107)
	at io.undertow.client.http2.Http2ClientConnection$1.handleEvent(Http2ClientConnection.java:99)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameCloseListener.handleEvent(AbstractFramedChannel.java:1061)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameCloseListener.handleEvent(AbstractFramedChannel.java:975)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at io.undertow.protocols.ssl.SslConduit$SslReadReadyHandler.terminated(SslConduit.java:1214)
	at org.xnio.nio.NioSocketConduit.readTerminated(NioSocketConduit.java:360)
	at org.xnio.nio.NioSocketStreamConnection.notifyReadClosed(NioSocketStreamConnection.java:148)
	at org.xnio.Connection.close(Connection.java:139)
	at org.xnio.IoUtils.safeClose(IoUtils.java:134)
	at io.undertow.protocols.ssl.SslConduit.closed(SslConduit.java:1046)
	at io.undertow.protocols.ssl.SslConduit.close(SslConduit.java:1117)
	at io.undertow.protocols.ssl.UndertowSslConnection.closeAction(UndertowSslConnection.java:149)
	at org.xnio.Connection.close(Connection.java:132)
	at org.xnio.IoUtils.safeClose(IoUtils.java:134)
	at io.undertow.server.protocol.framed.AbstractFramedChannel.close(AbstractFramedChannel.java:816)
	at org.xnio.IoUtils.safeClose(IoUtils.java:134)
	at io.undertow.protocols.http2.Http2Channel.sendGoAway(Http2Channel.java:832)
	at io.undertow.protocols.http2.Http2Channel.sendGoAway(Http2Channel.java:809)
	at io.undertow.client.http2.Http2ClientConnection.close(Http2ClientConnection.java:303)
	at org.xnio.IoUtils.safeClose(IoUtils.java:134)
	at io.undertow.server.handlers.proxy.ProxyHandler$IoExceptionHandler.handleException(ProxyHandler.java:790)
	at org.xnio.ChannelListeners.invokeChannelExceptionHandler(ChannelListeners.java:126)
	at io.undertow.util.Transfer$TransferListener.handleEvent(Transfer.java:218)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at io.undertow.server.protocol.framed.AbstractFramedStreamSinkChannel$1.run(AbstractFramedStreamSinkChannel.java:214)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:935)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:929)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at io.undertow.protocols.ssl.SslConduit$SslReadReadyHandler.readReady(SslConduit.java:1175)
	at io.undertow.protocols.ssl.SslConduit$1.run(SslConduit.java:168)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:582)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:466)

16:03:34,569 DEBUG (XNIO-1 I/O-7) [io.undertow.request.error-response] <DelegatingBasicLogger.java:424> Setting error code 503 for exchange HttpServerExchange{ POST /fullbytes}: java.lang.RuntimeException
	at io.undertow.server.HttpServerExchange.setStatusCode(HttpServerExchange.java:1410)
	at io.undertow.server.handlers.proxy.ProxyHandler.handleFailure(ProxyHandler.java:668)
	at io.undertow.server.handlers.proxy.ProxyHandler$ResponseCallback.failed(ProxyHandler.java:727)
	at io.undertow.client.http2.Http2ClientExchange.failed(Http2ClientExchange.java:125)
	at io.undertow.client.http2.Http2ClientConnection$1.handleEvent(Http2ClientConnection.java:107)


```

**Comment by fl4via** [comment]
Retest this please

**Pull request merged**
