### PR TITLE
[Undertow 1702] SameSiteCookieHandler can throw NPE if request doesn't contain user-agent header

### PR DESCRIPTION
**Pull request by jstourac**
https://issues.redhat.com/browse/UNDERTOW-1702

### CODE REVIEW

**Comment by msfm** [comment]
Sorry that I forgot to add a null check in SameSiteNoneIncompatibleClientChecker.

This PR looks good, but it could be better to add a null check in SameSiteNoneIncompatibleClientChecker. As the root cause exists there.

```diff
diff --git a/core/src/main/java/io/undertow/util/SameSiteNoneIncompatibleClientChecker.java b/core/src/main/java/io/undertow/util/SameSiteNoneIncompatibleClientChecker.java
index 6bcf775..8c91f07 100644
--- a/core/src/main/java/io/undertow/util/SameSiteNoneIncompatibleClientChecker.java
+++ b/core/src/main/java/io/undertow/util/SameSiteNoneIncompatibleClientChecker.java
@@ -65,6 +65,9 @@ public final class SameSiteNoneIncompatibleClientChecker {
 
     // browsers known to be incompatible.
     public static boolean isSameSiteNoneIncompatible(String useragent) {
+        if (useragent == null || useragent.isEmpty()) {
+            return false;
+        }
         return hasWebKitSameSiteBug(useragent) ||
             dropsUnrecognizedSameSiteCookies(useragent);
     }
```

**Comment by jstourac** [comment]
Hi @msfm, thanks for review. You are right!

Looking at the code and tests in `SameSiteNoneIncompatibleClientCheckerTestCase`, there are also `hasWebKitSameSiteBug` and `dropsUnrecognizedSameSiteCookies` methods tested separately. This would mean to put null check into these two methods to make tests happy. 

I'm thinking of removing two tests for those two methods and also make all methods in the `SameSiteNoneIncompatibleClientChecker` private except the two that are marked as public alreday. Currently there is `package-scope` used for rest of the methods... I think it is not necessary. What do you think?

**Comment by msfm** [comment]
Hi @jstourac. Sorry to late response.

> I'm thinking of removing two tests for those two methods and also make all methods in the SameSiteNoneIncompatibleClientChecker private except the two that are marked as public already. Currently there is package-scope used for rest of the methods... I think it is not necessary. What do you think?

I agree with your thought. We can test just public methods only and can change other package-scope methods to private.

**Comment by jstourac** [comment]
@msfm thank you, I've just updated this one

**Comment by jstourac** [comment]
CI test failures don't seem to be related to changes in this MR.

**Pull request merged**
