### PR TITLE
[UNDERTOW-421] Deprecate the getIdentityManager method on the SecurityContext

### PR DESCRIPTION
**Pull request by darranl**
Whilst all current mechanisms make use of this it should not be seen as an exclusive way to access identities and accounts.

The next step for Elytron is going to be to adjust the mechanisms to make use of the Elytron domains and realms directly.

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1089](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=50260&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 643a3b273549aa0f2356c1f660981eb424657d23

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1089](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=50260&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 643a3b273549aa0f2356c1f660981eb424657d23
Summary: Exit code 1 Build time: 0:00:20
### Build problems:
Process exited with code 1

**Comment by darranl** [comment]
This build failure is due to the existing code in Undertow not compiling, this PR does not touch on the affected code.

**Comment by stuartwdouglas** [comment]
Oops, I only tested some new code against JDK8 and it did not build under 7. 

I am thinking that it may be best to hold off on this until after 1.2.0.Final, which should be released early next week.

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1093](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=50293&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 643a3b273549aa0f2356c1f660981eb424657d23

**Comment by stuartwdouglas** [comment]
On second thoughts as this does not break compatibility it makes sense to include this in 1.2, so that existing code can start to change to the new model.

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1093](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=50293&buildTypeId=UNDERTOW_MasterWindows) outcome was **SUCCESS** using a merge of 643a3b273549aa0f2356c1f660981eb424657d23
Summary: Tests passed: 2492, ignored: 369 Build time: 0:14:00

**Comment by darranl** [comment]
Thanks @stuartwdouglas - yeah that was my thinking on this one - get the message out it is deprecated without actually forcing anyone to do anything just yet,

**Pull request merged**
