### PR TITLE
Prevent "Could not find message parameter on method" for methods with generic parameters

### PR DESCRIPTION
**Pull request by rinokadijk**
Shadow synthetic bridge methods are generated with annotations as of JDK8. This causes the bridged method with the @OnMessage annotation to be scanned by the AnnotatedEndpointFactory. The bridged method has an Object parameter which causes the exception:

javax.websocket.DeploymentException: UT003029: Could not find message parameter on method ....... onMessage(java.lang.Object)

The fix is to not scan bridged methods. This works fine in JDK7 and JDK8. Similar problem in myBatis: https://github.com/mybatis/mybatis-3/issues/237

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
Can one of the admins verify this patch?

**Comment by ctomc** [comment]
this is ok to test

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1204](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=57747&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of f87dbf9fac3216f5b45ce63ab6e23810798b7d20

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1496](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=57746&buildTypeId=UT_MASTER_LINUX) is now running using a merge of f87dbf9fac3216f5b45ce63ab6e23810798b7d20

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1204](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=57747&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of f87dbf9fac3216f5b45ce63ab6e23810798b7d20
Summary: Tests failed: 2 (2 new), passed: 2516, ignored: 379 Build time: 0:13:10
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testDigestSuccess{proxy}: <no details avaliable>

io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testDigestSuccess{proxy}{ajp}: <no details avaliable>

```

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1496](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=57746&buildTypeId=UT_MASTER_LINUX) outcome was **SUCCESS** using a merge of f87dbf9fac3216f5b45ce63ab6e23810798b7d20
Summary: Tests passed: 2595, ignored: 302 Build time: 0:13:46

**Comment by rinokadijk** [comment]
Failed tests also failed on the windows build of the last pull request. I don't think the tests of Build 1204  fail because of the changes in this pull request.

**Pull request merged**
