### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by emag**

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1004](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=37343&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 9f00a92539da71e420395b30f2234e314fe169e0

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1437](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=37351&buildTypeId=UT_MASTER_LINUX) is now running using a merge of 9f00a92539da71e420395b30f2234e314fe169e0

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1004](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=37343&buildTypeId=UNDERTOW_MasterWindows) outcome was **SUCCESS** using a merge of 9f00a92539da71e420395b30f2234e314fe169e0
Summary: Tests passed: 3167, ignored: 375 Build time: 0:13:39

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1437](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=37351&buildTypeId=UT_MASTER_LINUX) outcome was **SUCCESS** using a merge of 9f00a92539da71e420395b30f2234e314fe169e0
Summary: Tests passed: 3244, ignored: 298 Build time: 0:14:33

**Comment by stuartwdouglas** [comment]
Oops, I forgot to code this. Rather than renaming (which would break compatibility if people are using the misspelled one), I deprecated the existing one.

**Pull request closed without merging**
