### PR TITLE
[UNDERTOW-1091] Invalid response code for empty host value in request

### PR DESCRIPTION
**Pull request by iweiss**
Issue: https://issues.jboss.org/browse/UNDERTOW-1091

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
**Linux** [Build 388](https://ci.wildfly.org/viewLog.html?buildId=62794&buildTypeId=UNDERTOW_14xLinux) outcome was **FAILURE** using a merge of 1fba4a020859df446902e893cebd4c058ca122c5
Summary: Tests failed: 1, passed: 2846, ignored: 504 Build time: 00:17:36
### Failed tests
```
io.undertow.servlet.test.streams.ServletInputStreamEarlyCloseClientSideTestCase.testServletInputStreamEarlyClose[proxy][https]: java.lang.AssertionError
	at io.undertow.servlet.test.streams.ServletInputStreamEarlyCloseClientSideTestCase.testServletInputStreamEarlyClose(ServletInputStreamEarlyCloseClientSideTestCase.java:79)
------- Stderr: -------
07:09:54,351 DEBUG (XNIO-1 task-25) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate HttpServerExchange{ POST /servletContext/servlet request {X-Forwarded-Proto=[http], X-Forwarded-Port=[80], X-Forwarded-For=[127.0.0.1], X-Forwarded-Server=[localhost], Content-Length=[130000100], Host=[localhost], X-Forwarded-Host=[localhost]} response {}}, authentication required: false
07:09:54,351 DEBUG (XNIO-1 task-25) [io.undertow.request.security] <SecurityContextImpl.java:246> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@1217ea8 for HttpServerExchange{ POST /servletContext/servlet request {X-Forwarded-Proto=[http], X-Forwarded-Port=[80], X-Forwarded-For=[127.0.0.1], X-Forwarded-Server=[localhost], Content-Length=[130000100], Host=[localhost], X-Forwarded-Host=[localhost]} response {}}
07:09:54,351 DEBUG (XNIO-1 task-25) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for HttpServerExchange{ POST /servletContext/servlet request {X-Forwarded-Proto=[http], X-Forwarded-Port=[80], X-Forwarded-For=[127.0.0.1], X-Forwarded-Server=[localhost], Content-Length=[130000100], Host=[localhost], X-Forwarded-Host=[localhost]} response {}}
07:09:54,356 DEBUG (XNIO-1 I/O-8) [io.undertow.client.http.HttpClientConnection] <HttpClientConnection.java:458> close called on connection to localhost/127.0.0.1:8888
07:09:54,357 DEBUG (XNIO-1 I/O-8) [io.undertow.client.http.HttpClientExchange] <HttpClientExchange.java:87> request terminated for request to localhost/127.0.0.1:8888 /servletContext/servlet
07:09:54,357 DEBUG (XNIO-1 I/O-8) [io.undertow.client.http.HttpClientConnection] <HttpClientConnection.java:176> connection to localhost/127.0.0.1:8888 closed
07:09:54,358 ERROR (XNIO-1 task-25) [io.undertow.request] <LoggingExceptionHandler.java:80> UT005023: Exception handling request to /servletContext/servlet: java.lang.NullPointerException
	at io.undertow.servlet.spec.ServletInputStreamImpl.readIntoBuffer(ServletInputStreamImpl.java:169)
	at io.undertow.servlet.spec.ServletInputStreamImpl.read(ServletInputStreamImpl.java:144)
	at io.undertow.servlet.spec.ServletInputStreamImpl.read(ServletInputStreamImpl.java:131)
	at io.undertow.servlet.test.streams.EarlyCloseClientServlet.doPost(EarlyCloseClientServlet.java:50)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:211)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:809)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

07:09:54,358 ERROR (XNIO-1 I/O-8) [io.undertow.proxy] <ProxyHandler.java:642> UT005028: Proxy request to /servletContext/servlet failed: java.nio.channels.ClosedChannelException
	at io.undertow.client.http.HttpClientConnection$5.handleEvent(HttpClientConnection.java:194)
	at io.undertow.client.http.HttpClientConnection$5.handleEvent(HttpClientConnection.java:173)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.StreamConnection.invokeCloseListener(StreamConnection.java:80)
	at org.xnio.Connection.readClosed(Connection.java:94)
	at io.undertow.protocols.ssl.UndertowSslConnection.readClosed(UndertowSslConnection.java:140)


```

**Comment by fl4via** [comment]
Retest this please

**Comment by undertow-pull-request** [comment]
**Linux** [Build 662](https://ci.wildfly.org/viewLog.html?buildId=140286&buildTypeId=UNDERTOW_14xLinux) outcome was **FAILURE** using a merge of 1fba4a020859df446902e893cebd4c058ca122c5
Summary: Tests failed: 1 (1 new), passed: 3316, ignored: 602 Build time: 00:37:08
### Failed tests
```
io.undertow.servlet.test.dispatcher.DispatcherForwardTestCase.testPathBasedInclude[proxy][http2-clear-upgrade]: java.lang.AssertionError
	at io.undertow.servlet.test.dispatcher.DispatcherForwardTestCase.testPathBasedInclude(DispatcherForwardTestCase.java:120)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:503)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:98)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:276)


```

**Comment by fl4via** [comment]
Retest this please

**Comment by undertow-pull-request** [comment]
**Linux** [Build 663](https://ci.wildfly.org/viewLog.html?buildId=140323&buildTypeId=UNDERTOW_14xLinux) outcome was **FAILURE** using a merge of 1fba4a020859df446902e893cebd4c058ca122c5
Summary: Tests failed: 3 (2 new), passed: 3314, ignored: 602 Build time: 00:52:48
### Failed tests
```
io.undertow.servlet.test.streams.ServletInputStreamRequestBufferingTestCase.testAsyncServletInputStreamInParallelOffIoThread[proxy][http2-clear-upgrade]: 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at io.undertow.servlet.test.streams.AbstractServletInputStreamTestCase.runTestParallel(AbstractServletInputStreamTestCase.java:292)
	at io.undertow.servlet.test.streams.AbstractServletInputStreamTestCase.testAsyncServletInputStreamInParallelOffIoThread(AbstractServletInputStreamTestCase.java:129)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:503)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:98)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:276)
	at io.undertow.servlet.test.streams.AbstractServletInputStreamTestCase$1.call(AbstractServletInputStreamTestCase.java:279)
	at io.undertow.servlet.test.streams.AbstractServletInputStreamTestCase$1.call(AbstractServletInputStreamTestCase.java:260)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
------- Stderr: -------
13:49:32,206 DEBUG (XNIO-1 task-8) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
13:49:32,207 DEBUG (XNIO-1 task-8) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@ebcfca for /servletContext/asyncInput
13:49:32,207 DEBUG (XNIO-1 task-8) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
13:49:32,207 DEBUG (XNIO-1 task-8) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
13:49:32,207 DEBUG (XNIO-1 task-8) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@ebcfca for /servletContext/asyncInput
13:49:32,207 DEBUG (XNIO-1 task-8) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
13:49:32,208 DEBUG (XNIO-1 task-8) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
13:49:32,208 DEBUG (XNIO-1 task-8) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@ebcfca for /servletContext/asyncInput
13:49:32,208 DEBUG (XNIO-1 task-8) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
13:49:32,214 DEBUG (XNIO-1 task-6) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
13:49:32,214 DEBUG (XNIO-1 task-6) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@ebcfca for /servletContext/asyncInput
13:49:32,214 DEBUG (XNIO-1 task-6) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
13:49:32,218 DEBUG (XNIO-1 task-15) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
13:49:32,218 DEBUG (XNIO-1 task-15) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@ebcfca for /servletContext/asyncInput
13:49:32,218 DEBUG (XNIO-1 task-15) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
13:49:32,225 DEBUG (XNIO-1 task-24) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
13:49:32,226 DEBUG (XNIO-1 task-24) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@ebcfca for /servletContext/asyncInput
13:49:32,226 DEBUG (XNIO-1 task-24) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
13:49:32,227 DEBUG (XNIO-1 task-26) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
13:49:32,227 DEBUG (XNIO-1 task-26) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@ebcfca for /servletContext/asyncInput
13:49:32,227 DEBUG (XNIO-1 task-26) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
13:49:32,234 DEBUG (XNIO-1 task-27) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
13:49:32,234 DEBUG (XNIO-1 task-20) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
13:49:32,235 DEBUG (XNIO-1 task-20) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@ebcfca for /servletContext/asyncInput
13:49:32,235 DEBUG (XNIO-1 task-27) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@ebcfca for /servletContext/asyncInput
13:49:32,235 DEBUG (XNIO-1 task-20) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
13:49:32,235 DEBUG (XNIO-1 task-27) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
13:49:32,246 DEBUG (XNIO-1 task-8) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
13:49:32,246 DEBUG (XNIO-1 task-8) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@ebcfca for /servletContext/asyncInput
13:49:32,246 DEBUG (XNIO-1 task-8) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
13:49:32,246 DEBUG (XNIO-1 task-5) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
13:49:32,249 DEBUG (XNIO-1 task-5) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@ebcfca for /servletContext/asyncInput
13:49:32,249 DEBUG (XNIO-1 task-5) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
13:49:32,249 DEBUG (XNIO-1 task-5) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
13:49:32,250 DEBUG (XNIO-1 task-5) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@ebcfca for /servletContext/asyncInput
13:49:32,250 DEBUG (XNIO-1 task-5) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
13:49:32,255 DEBUG (XNIO-1 task-27) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false


io.undertow.servlet.test.streams.ServletInputStreamRequestBufferingTestCase.testAsyncServletInputStreamInParallel[proxy][http2-clear-upgrade]: 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at io.undertow.servlet.test.streams.AbstractServletInputStreamTestCase.runTestParallel(AbstractServletInputStreamTestCase.java:292)
	at io.undertow.servlet.test.streams.AbstractServletInputStreamTestCase.testAsyncServletInputStreamInParallel(AbstractServletInputStreamTestCase.java:119)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:503)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:98)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:276)
	at io.undertow.servlet.test.streams.AbstractServletInputStreamTestCase$1.call(AbstractServletInputStreamTestCase.java:279)
	at io.undertow.servlet.test.streams.AbstractServletInputStreamTestCase$1.call(AbstractServletInputStreamTestCase.java:260)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
------- Stderr: -------
13:49:09,494 DEBUG (XNIO-1 task-17) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
13:49:09,495 DEBUG (XNIO-1 task-17) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@ebcfca for /servletContext/asyncInput
13:49:09,495 DEBUG (XNIO-1 task-17) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
13:49:09,499 DEBUG (XNIO-1 task-13) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
13:49:09,500 DEBUG (XNIO-1 task-13) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@ebcfca for /servletContext/asyncInput
13:49:09,500 DEBUG (XNIO-1 task-13) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
13:49:09,506 DEBUG (XNIO-1 task-27) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
13:49:09,507 DEBUG (XNIO-1 task-27) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@ebcfca for /servletContext/asyncInput
13:49:09,507 DEBUG (XNIO-1 task-27) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
13:49:09,507 DEBUG (XNIO-1 task-27) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
13:49:09,507 DEBUG (XNIO-1 task-27) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@ebcfca for /servletContext/asyncInput
13:49:09,507 DEBUG (XNIO-1 task-27) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
13:49:09,508 DEBUG (XNIO-1 task-27) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
13:49:09,508 DEBUG (XNIO-1 task-27) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@ebcfca for /servletContext/asyncInput
13:49:09,508 DEBUG (XNIO-1 task-27) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
13:49:09,508 DEBUG (XNIO-1 task-27) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
13:49:09,509 DEBUG (XNIO-1 task-27) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@ebcfca for /servletContext/asyncInput
13:49:09,509 DEBUG (XNIO-1 task-27) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
13:49:09,509 DEBUG (XNIO-1 task-27) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
13:49:09,509 DEBUG (XNIO-1 task-27) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@ebcfca for /servletContext/asyncInput
13:49:09,509 DEBUG (XNIO-1 task-27) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
13:49:09,510 DEBUG (XNIO-1 task-27) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
13:49:09,510 DEBUG (XNIO-1 task-27) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@ebcfca for /servletContext/asyncInput
13:49:09,510 DEBUG (XNIO-1 task-27) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
13:49:09,512 DEBUG (XNIO-1 task-3) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
13:49:09,512 DEBUG (XNIO-1 task-3) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@ebcfca for /servletContext/asyncInput
13:49:09,512 DEBUG (XNIO-1 task-3) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
13:49:09,514 DEBUG (XNIO-1 task-10) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
13:49:09,515 DEBUG (XNIO-1 task-10) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@ebcfca for /servletContext/asyncInput
13:49:09,515 DEBUG (XNIO-1 task-10) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
13:49:09,520 DEBUG (XNIO-1 task-8) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
13:49:09,521 DEBUG (XNIO-1 task-8) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@ebcfca for /servletContext/asyncInput
13:49:09,521 DEBUG (XNIO-1 task-8) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
13:49:09,526 DEBUG (XNIO-1 task-13) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
13:49:09,527 DEBUG (XNIO-1 task-13) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@ebcfca for /servletContext/asyncInput
13:49:09,527 DEBUG (XNIO-1 task-13) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
13:49:09,527 DEBUG (XNIO-1 task-13) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false


io.undertow.servlet.test.dispatcher.DispatcherForwardTestCase.testPathBasedInclude[proxy][http2-clear-upgrade]: java.lang.AssertionError
	at io.undertow.servlet.test.dispatcher.DispatcherForwardTestCase.testPathBasedInclude(DispatcherForwardTestCase.java:120)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:503)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:98)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:276)


```

**Comment by fl4via** [comment]
I'm closing this as I think we wont have more releases in that branch

**Comment by undertow-pull-request** [comment]
**Linux** [Build 664](https://ci.wildfly.org/viewLog.html?buildId=159656&buildTypeId=UNDERTOW_14xLinux) outcome was **FAILURE** using a merge of 1fba4a020859df446902e893cebd4c058ca122c5
Summary: Tests failed: 1, passed: 3316, ignored: 602 Build time: 00:38:21
### Failed tests
```
io.undertow.servlet.test.dispatcher.DispatcherForwardTestCase.testPathBasedInclude[proxy][http2-clear-upgrade]: java.lang.AssertionError
	at io.undertow.servlet.test.dispatcher.DispatcherForwardTestCase.testPathBasedInclude(DispatcherForwardTestCase.java:120)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:503)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:98)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:276)


```

**Pull request closed without merging**
