### PR TITLE
Backport fixes for 1.4.x branch

### PR DESCRIPTION
**Pull request by mibo**
Backport of below PRs (from master to 1.4.x branch):
- https://github.com/undertow-io/undertow/pull/736
- https://github.com/undertow-io/undertow/pull/794

to fix related vulnerabilites (CVEs).

@fl4via it would be really nice if you could provide a new 1.4.x release which includes those fixes. Thanks 🙂

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
Can one of the admins verify this patch?

**Comment by stuartwdouglas** [comment]
This is ok to test

**Comment by undertow-pull-request** [comment]
**Linux** [Build 665](https://ci.wildfly.org/viewLog.html?buildId=170041&buildTypeId=UNDERTOW_14xLinux) outcome was **FAILURE** using a merge of cf4c04f2c1cd902d5f5a850c9791f22cab7b31df
Summary: Tests failed: 1, passed: 3328, ignored: 602 Build time: 00:39:16
### Failed tests
```
io.undertow.servlet.test.dispatcher.DispatcherForwardTestCase.testPathBasedInclude[proxy][http2-clear-upgrade]: java.lang.AssertionError
	at io.undertow.servlet.test.dispatcher.DispatcherForwardTestCase.testPathBasedInclude(DispatcherForwardTestCase.java:120)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:503)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:98)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:276)


```

**Comment by mibo** [comment]
Hi @stuartwdouglas,

can the test be run again please.
At least on my maschine with OpenJDK 9 it all tests are successful (via Maven and IDE).

Regards, Michael

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Undertow 1.4.28.Final-SNAPSHOT:
[INFO]
[INFO] Undertow ........................................... SUCCESS [  1.074 s]
[INFO] Undertow Parser Generator .......................... SUCCESS [  1.089 s]
[INFO] Undertow Core ...................................... SUCCESS [01:42 min]
[INFO] Undertow Servlet ................................... SUCCESS [01:51 min]
[INFO] Undertow WebSockets JSR356 implementations ......... SUCCESS [ 25.020 s]
[INFO] Undertow Examples .................................. SUCCESS [  2.072 s]
[INFO] Undertow Karaf Features ............................ SUCCESS [  2.064 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:05 min
[INFO] Finished at: 2019-10-01T07:03:49+02:00
[INFO] ------------------------------------------------------------------------
```

**Comment by undertow-pull-request** [comment]
**Linux** [Build 666](https://ci.wildfly.org/viewLog.html?buildId=170063&buildTypeId=UNDERTOW_14xLinux) outcome was **FAILURE** using a merge of cf4c04f2c1cd902d5f5a850c9791f22cab7b31df
Summary: Tests failed: 2 (1 new), passed: 3328, ignored: 598 Build time: 00:39:32
### Failed tests
```
io.undertow.server.handlers.proxy.mod_cluster.BasicMCMPUnitTestCase: java.lang.RuntimeException: java.net.BindException: Address already in use
	at io.undertow.Undertow.start(Undertow.java:248)
	at io.undertow.server.handlers.proxy.mod_cluster.AbstractModClusterTestBase.startServers(AbstractModClusterTestBase.java:210)
	at io.undertow.server.handlers.proxy.mod_cluster.BasicMCMPUnitTestCase.setup(BasicMCMPUnitTestCase.java:56)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:276)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:190)
	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
	at io.undertow.Undertow.start(Undertow.java:193)
	... 31 more


io.undertow.servlet.test.dispatcher.DispatcherForwardTestCase.testPathBasedInclude[proxy][http2-clear-upgrade]: java.lang.AssertionError
	at io.undertow.servlet.test.dispatcher.DispatcherForwardTestCase.testPathBasedInclude(DispatcherForwardTestCase.java:120)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:503)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:98)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:276)


```

**Comment by fl4via** [comment]
@mibo thanks for the PR! I'll rerun the test soon

**Comment by mibo** [comment]
@fl4via any update on this or something where I can support you?

**Comment by undertow-pull-request** [comment]
**Linux** [Build 667](https://ci.wildfly.org/viewLog.html?buildId=173663&buildTypeId=UNDERTOW_14xLinux) outcome was **UNKNOWN** using a merge of cf4c04f2c1cd902d5f5a850c9791f22cab7b31df
Summary: Canceled (Tests failed: 1 (1 new), passed: 367, ignored: 2) Build time: 00:01:44
### Failed tests
```
io.undertow.server.security.ClientCertRenegotiationTestCase: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:190)
	at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
	at io.undertow.protocols.ssl.UndertowXnioSsl.createSslConnectionServer(UndertowXnioSsl.java:301)
	at io.undertow.testutils.DefaultServer.startSSLServer(DefaultServer.java:665)
	at io.undertow.testutils.DefaultServer.startSSLServer(DefaultServer.java:645)
	at io.undertow.testutils.DefaultServer.startSSLServer(DefaultServer.java:623)
	at io.undertow.testutils.DefaultServer.startSSLServer(DefaultServer.java:611)
	at io.undertow.server.security.ClientCertRenegotiationTestCase.startSSL(ClientCertRenegotiationTestCase.java:70)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:276)


```

**Comment by undertow-pull-request** [comment]
**Linux** [Build 668](https://ci.wildfly.org/viewLog.html?buildId=173664&buildTypeId=UNDERTOW_14xLinux) outcome was **FAILURE** using a merge of cf4c04f2c1cd902d5f5a850c9791f22cab7b31df
Summary: Tests failed: 3 (2 new), passed: 3326, ignored: 602 Build time: 00:37:31
### Failed tests
```
io.undertow.servlet.test.streams.ServletInputStreamRequestBufferingTestCase.testAsyncServletInputStreamInParallelOffIoThread[proxy][http2-clear-upgrade]: 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at io.undertow.servlet.test.streams.AbstractServletInputStreamTestCase.runTestParallel(AbstractServletInputStreamTestCase.java:292)
	at io.undertow.servlet.test.streams.AbstractServletInputStreamTestCase.testAsyncServletInputStreamInParallelOffIoThread(AbstractServletInputStreamTestCase.java:129)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:503)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:98)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:276)
	at io.undertow.servlet.test.streams.AbstractServletInputStreamTestCase$1.call(AbstractServletInputStreamTestCase.java:279)
	at io.undertow.servlet.test.streams.AbstractServletInputStreamTestCase$1.call(AbstractServletInputStreamTestCase.java:260)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
------- Stderr: -------
01:19:27,492 DEBUG (XNIO-1 task-6) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
01:19:27,492 DEBUG (XNIO-1 task-6) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@15a41ca for /servletContext/asyncInput
01:19:27,493 DEBUG (XNIO-1 task-6) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
01:19:27,493 DEBUG (XNIO-1 task-6) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
01:19:27,493 DEBUG (XNIO-1 task-6) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@15a41ca for /servletContext/asyncInput
01:19:27,493 DEBUG (XNIO-1 task-6) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
01:19:27,495 DEBUG (XNIO-1 task-30) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
01:19:27,495 DEBUG (XNIO-1 task-3) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
01:19:27,495 DEBUG (XNIO-1 task-30) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@15a41ca for /servletContext/asyncInput
01:19:27,495 DEBUG (XNIO-1 task-3) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@15a41ca for /servletContext/asyncInput
01:19:27,495 DEBUG (XNIO-1 task-30) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
01:19:27,495 DEBUG (XNIO-1 task-3) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
01:19:27,498 DEBUG (XNIO-1 task-24) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
01:19:27,498 DEBUG (XNIO-1 task-24) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@15a41ca for /servletContext/asyncInput
01:19:27,498 DEBUG (XNIO-1 task-24) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
01:19:27,499 DEBUG (XNIO-1 task-21) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
01:19:27,499 DEBUG (XNIO-1 task-21) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@15a41ca for /servletContext/asyncInput
01:19:27,499 DEBUG (XNIO-1 task-21) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
01:19:27,500 DEBUG (XNIO-1 task-11) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
01:19:27,500 DEBUG (XNIO-1 task-11) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@15a41ca for /servletContext/asyncInput
01:19:27,500 DEBUG (XNIO-1 task-11) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
01:19:27,504 DEBUG (XNIO-1 task-21) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
01:19:27,504 DEBUG (XNIO-1 task-21) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@15a41ca for /servletContext/asyncInput
01:19:27,504 DEBUG (XNIO-1 task-21) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
01:19:27,505 DEBUG (XNIO-1 task-21) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
01:19:27,505 DEBUG (XNIO-1 task-21) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@15a41ca for /servletContext/asyncInput
01:19:27,505 DEBUG (XNIO-1 task-21) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
01:19:27,506 DEBUG (XNIO-1 task-21) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
01:19:27,507 DEBUG (XNIO-1 task-21) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@15a41ca for /servletContext/asyncInput
01:19:27,507 DEBUG (XNIO-1 task-21) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
01:19:27,507 DEBUG (XNIO-1 task-21) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
01:19:27,507 DEBUG (XNIO-1 task-21) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@15a41ca for /servletContext/asyncInput
01:19:27,507 DEBUG (XNIO-1 task-21) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
01:19:27,515 DEBUG (XNIO-1 task-26) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
01:19:27,515 DEBUG (XNIO-1 task-26) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@15a41ca for /servletContext/asyncInput
01:19:27,515 DEBUG (XNIO-1 task-26) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
01:19:27,516 DEBUG (XNIO-1 task-4) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false


io.undertow.servlet.test.streams.ServletInputStreamRequestBufferingTestCase.testAsyncServletInputStreamInParallel[proxy][http2-clear-upgrade]: 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at io.undertow.servlet.test.streams.AbstractServletInputStreamTestCase.runTestParallel(AbstractServletInputStreamTestCase.java:292)
	at io.undertow.servlet.test.streams.AbstractServletInputStreamTestCase.testAsyncServletInputStreamInParallel(AbstractServletInputStreamTestCase.java:119)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:503)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:98)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:276)
	at io.undertow.servlet.test.streams.AbstractServletInputStreamTestCase$1.call(AbstractServletInputStreamTestCase.java:279)
	at io.undertow.servlet.test.streams.AbstractServletInputStreamTestCase$1.call(AbstractServletInputStreamTestCase.java:260)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
------- Stderr: -------
01:19:05,576 DEBUG (XNIO-1 task-3) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
01:19:05,576 DEBUG (XNIO-1 task-8) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
01:19:05,576 DEBUG (XNIO-1 task-3) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@15a41ca for /servletContext/asyncInput
01:19:05,576 DEBUG (XNIO-1 task-8) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@15a41ca for /servletContext/asyncInput
01:19:05,576 DEBUG (XNIO-1 task-3) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
01:19:05,576 DEBUG (XNIO-1 task-8) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
01:19:05,576 DEBUG (XNIO-1 task-30) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
01:19:05,576 DEBUG (XNIO-1 task-30) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@15a41ca for /servletContext/asyncInput
01:19:05,576 DEBUG (XNIO-1 task-30) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
01:19:05,577 DEBUG (XNIO-1 task-22) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
01:19:05,577 DEBUG (XNIO-1 task-22) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@15a41ca for /servletContext/asyncInput
01:19:05,577 DEBUG (XNIO-1 task-22) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
01:19:05,579 DEBUG (XNIO-1 task-28) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
01:19:05,579 DEBUG (XNIO-1 task-28) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@15a41ca for /servletContext/asyncInput
01:19:05,579 DEBUG (XNIO-1 task-28) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
01:19:05,581 DEBUG (XNIO-1 task-21) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
01:19:05,581 DEBUG (XNIO-1 task-29) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
01:19:05,581 DEBUG (XNIO-1 task-21) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@15a41ca for /servletContext/asyncInput
01:19:05,581 DEBUG (XNIO-1 task-21) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
01:19:05,581 DEBUG (XNIO-1 task-29) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@15a41ca for /servletContext/asyncInput
01:19:05,581 DEBUG (XNIO-1 task-29) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
01:19:05,583 DEBUG (XNIO-1 task-19) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
01:19:05,583 DEBUG (XNIO-1 task-19) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@15a41ca for /servletContext/asyncInput
01:19:05,583 DEBUG (XNIO-1 task-19) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
01:19:05,592 DEBUG (XNIO-1 task-5) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
01:19:05,592 DEBUG (XNIO-1 task-5) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@15a41ca for /servletContext/asyncInput
01:19:05,592 DEBUG (XNIO-1 task-5) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
01:19:05,608 DEBUG (XNIO-1 task-6) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
01:19:05,608 DEBUG (XNIO-1 task-6) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@15a41ca for /servletContext/asyncInput
01:19:05,609 DEBUG (XNIO-1 task-6) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
01:19:05,611 DEBUG (XNIO-1 task-23) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
01:19:05,611 DEBUG (XNIO-1 task-3) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false
01:19:05,611 DEBUG (XNIO-1 task-23) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@15a41ca for /servletContext/asyncInput
01:19:05,611 DEBUG (XNIO-1 task-3) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@15a41ca for /servletContext/asyncInput
01:19:05,611 DEBUG (XNIO-1 task-23) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
01:19:05,611 DEBUG (XNIO-1 task-3) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/asyncInput
01:19:05,612 DEBUG (XNIO-1 task-20) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/asyncInput, authentication required: false


io.undertow.servlet.test.dispatcher.DispatcherForwardTestCase.testPathBasedInclude[proxy][http2-clear-upgrade]: java.lang.AssertionError
	at io.undertow.servlet.test.dispatcher.DispatcherForwardTestCase.testPathBasedInclude(DispatcherForwardTestCase.java:120)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:503)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:98)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:276)


```

**Comment by fl4via** [comment]
I'm currently investigating why we are seeing some tests broken, specially DispatcherForwardTestCase.

**Comment by mibo** [comment]
Hi @fl4via,

Thanks for investigating. 
As written before I tested it locally with OpenJDK 9 it all tests are successful (via Maven and IDE).

Regards, Michael

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Undertow 1.4.28.Final-SNAPSHOT:
[INFO]
[INFO] Undertow ........................................... SUCCESS [  1.074 s]
[INFO] Undertow Parser Generator .......................... SUCCESS [  1.089 s]
[INFO] Undertow Core ...................................... SUCCESS [01:42 min]
[INFO] Undertow Servlet ................................... SUCCESS [01:51 min]
[INFO] Undertow WebSockets JSR356 implementations ......... SUCCESS [ 25.020 s]
[INFO] Undertow Examples .................................. SUCCESS [  2.072 s]
[INFO] Undertow Karaf Features ............................ SUCCESS [  2.064 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

**Comment by fl4via** [comment]
@mibo I see what's up. The test fails with -Pproxy parameter only

**Comment by fl4via** [comment]
Retest this please

**Comment by mibo** [comment]
Hi @fl4via , Thanks for your time and effort to fix the failing tests 🙂

**Comment by fl4via** [comment]
Np @mibo :-) hopefully we will be able to merge this one and tag a new release pretty soon.

**Comment by mibo** [comment]
Merged 👍  🙂

**Pull request merged**
