### PR TITLE
[1.3.x] Fix UNDERTOW-981 - Filter default ports of a scheme in ProxyPeerAddressHandler 

### PR DESCRIPTION
**Pull request by n1hility**

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
**Linux** [Build 99](https://ci.wildfly.org/viewLog.html?buildId=43920&buildTypeId=UNDERTOW_13xLinux) outcome was **FAILURE** using a merge of 7c76e1845c4114873cb54ac81adefa44a6af3cf2
Summary: Execution timeout; tests passed: 27, ignored: 1 Build time: 01:00:04

**Comment by n1hility** [comment]
retest this please

**Comment by undertow-pull-request** [comment]
**Linux** [Build 100](https://ci.wildfly.org/viewLog.html?buildId=43926&buildTypeId=UNDERTOW_13xLinux) outcome was **FAILURE** using a merge of 7c76e1845c4114873cb54ac81adefa44a6af3cf2
Summary: Execution timeout; tests passed: 27, ignored: 1 Build time: 01:00:02

**Comment by undertow-pull-request** [comment]
**Linux** [Build 101](https://ci.wildfly.org/viewLog.html?buildId=43938&buildTypeId=UNDERTOW_13xLinux) outcome was **UNKNOWN** using a merge of 7c76e1845c4114873cb54ac81adefa44a6af3cf2
Summary: Canceled (Tests passed: 27, ignored: 1; exit code 137) Build time: 00:00:39

**Comment by undertow-pull-request** [comment]
**Linux** [Build 103](https://ci.wildfly.org/viewLog.html?buildId=43942&buildTypeId=UNDERTOW_13xLinux) outcome was **FAILURE** using a merge of 7c76e1845c4114873cb54ac81adefa44a6af3cf2
Summary: Execution timeout (new); tests passed: 27, ignored: 1 Build time: 01:00:02

**Pull request merged**
