### PR TITLE
UNDERTOW-1677 cross context request issue with shared session managers

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by fl4via** [comment]
Jira: https://issues.redhat.com/browse/UNDERTOW-1677

**Comment by fl4via** [comment]
All CI failures are unrelated... merging

**Comment by ksiczek** [comment]
Thank you @stuartwdouglas for taking care. We impatiently wait for a fix so I had a look at your changes. I do not fully understand them but I noticed that you had changed and tested an InMemorySessionManager while our stack trace leads to DistributableSessionManager. Was it intentional? Is the InMemorySessionManager used by DistributableSessionManager somehow internally? We do not use <distributable /> directive and InMemorySessionManager seems a better choice for us but we could not switch to it anyhow.

**Comment by stuartwdouglas** [comment]
DistributableSessionManager is part of WildFly, it can't be used to test in the Undertow repo. This test emulates the WildFly issue by using the same session manager for each context (the issue is caused by the use of shared session managers, not because it is distributable).

**Comment by r-tock** [comment]
We are seeing this illegal state exceptions sporadically after we pushed 2.1.0. it has happened 4/1M requests, it's annoying but small enough not to warrant a rollback yet.

What's the best way to figure out what we are doing wrong?

**Pull request merged**
