### PR TITLE
UNDERTOW-1440 Support non-default file systems in PathResourceManager

### PR DESCRIPTION
**Pull request by michaelhixson**
https://issues.jboss.org/browse/UNDERTOW-1440

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
Can one of the admins verify this patch?

**Comment by stuartwdouglas** [comment]
This is ok to test

**Comment by undertow-pull-request** [comment]
**Linux** [Build 2856](https://ci.wildfly.org/viewLog.html?buildId=131479&buildTypeId=UT_MASTER_LINUX) outcome was **UNKNOWN** using a merge of 057f63b7ad804b46eb48767c931e5169a53158b6
Summary: Canceled (Error while applying patch; cannot find commit 498c0fc9e8fafe2c444629a5ed6114fe8e14896d in the git://github.com/undertow-io/undertow.git repository, possible reason: refs/pull/692/merge branch was updated and the commit selected for the bui... Build time: 00:00:08

**Comment by undertow-pull-request** [comment]
**Windows** [Build 2607](https://ci.wildfly.org/viewLog.html?buildId=131480&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 057f63b7ad804b46eb48767c931e5169a53158b6
Summary: Tests failed: 2 (2 new), passed: 3328, ignored: 709 Build time: 00:42:14
### Failed tests
```
io.undertow.server.ssl.SimpleSSLTestCase.parallel[proxy]: java.lang.RuntimeException: Buffer Leak io.undertow.server.ssl.SimpleSSLTestCase.parallel[proxy]
	at io.undertow.testutils.DefaultServer$2.testFinished(DefaultServer.java:289)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:524)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:104)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:297)
Caused by: java.lang.RuntimeException: java.nio.DirectByteBuffer[pos=0 lim=17408 cap=17408] NO: 271097 [NO_CONTEXT]
	at io.undertow.testutils.DebuggingSlicePool$DebuggingBuffer.<init>(DebuggingSlicePool.java:84)
	at io.undertow.testutils.DebuggingSlicePool.allocate(DebuggingSlicePool.java:45)
	at io.undertow.protocols.ssl.SslConduit.doWrap(SslConduit.java:894)
	at io.undertow.protocols.ssl.SslConduit.doUnwrap(SslConduit.java:671)
	at io.undertow.protocols.ssl.SslConduit.read(SslConduit.java:567)
	at org.xnio.conduits.ConduitStreamSourceChannel.read(ConduitStreamSourceChannel.java:127)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:158)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at io.undertow.protocols.ssl.SslConduit$SslReadReadyHandler.readReady(SslConduit.java:1175)
	at io.undertow.protocols.ssl.SslConduit$SslWriteReadyHandler.writeReady(SslConduit.java:1250)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:93)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:561)
------- Stderr: -------
20:54:37,943 DEBUG (XNIO-1 I/O-8) [io.undertow.request.io] <HttpReadListener.java:160> Error reading request: java.nio.channels.ClosedChannelException
	at sun.nio.ch.SocketChannelImpl.shutdownOutput(SocketChannelImpl.java:797)
	at org.xnio.nio.NioSocketConduit.write(NioSocketConduit.java:170)
	at io.undertow.protocols.ssl.SslConduit.doWrap(SslConduit.java:917)
	at io.undertow.protocols.ssl.SslConduit.doUnwrap(SslConduit.java:671)
	at io.undertow.protocols.ssl.SslConduit.read(SslConduit.java:567)
	at org.xnio.conduits.ConduitStreamSourceChannel.read(ConduitStreamSourceChannel.java:127)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:158)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at io.undertow.protocols.ssl.SslConduit$SslReadReadyHandler.readReady(SslConduit.java:1175)
	at io.undertow.protocols.ssl.SslConduit$SslWriteReadyHandler.writeReady(SslConduit.java:1250)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:93)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:561)
	Suppressed: java.nio.channels.ClosedChannelException
		at sun.nio.ch.SocketChannelImpl.ensureWriteOpen(SocketChannelImpl.java:270)
		at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:461)
		at org.xnio.nio.NioSocketConduit.write(NioSocketConduit.java:164)
		... 13 more

java.lang.RuntimeException: java.nio.DirectByteBuffer[pos=0 lim=17408 cap=17408] NO: 271097 [NO_CONTEXT]
	at io.undertow.testutils.DebuggingSlicePool$DebuggingBuffer.<init>(DebuggingSlicePool.java:84)
	at io.undertow.testutils.DebuggingSlicePool.allocate(DebuggingSlicePool.java:45)
	at io.undertow.protocols.ssl.SslConduit.doWrap(SslConduit.java:894)
	at io.undertow.protocols.ssl.SslConduit.doUnwrap(SslConduit.java:671)
	at io.undertow.protocols.ssl.SslConduit.read(SslConduit.java:567)
	at org.xnio.conduits.ConduitStreamSourceChannel.read(ConduitStreamSourceChannel.java:127)


io.undertow.websockets.jsr.test.annotated.AnnotatedEndpointTest.testEncodingAndDecodingBinary: java.lang.IllegalStateException: ChannelPipeline does not contain a HttpRequestEncoder or HttpClientCodec
	at io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker$1.operationComplete(WebSocketClientHandshaker.java:182)
	at io.netty.handler.codec.http.websocketx.WebSocketClientHandshaker$1.operationComplete(WebSocketClientHandshaker.java:172)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.netty.util.concurrent.DefaultPromise.access$000(DefaultPromise.java:34)
	at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:431)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)
------- Stderr: -------
21:32:19,461 DEBUG (XNIO-1 task-29) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /ws/encoding/Stuart, authentication required: false
21:32:19,462 DEBUG (XNIO-1 task-29) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@6dadca29 for /ws/encoding/Stuart
21:32:19,462 DEBUG (XNIO-1 task-29) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /ws/encoding/Stuart


```

**Pull request merged**
