### PR TITLE
test 2

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
**Windows** [Build 2242](https://ci.wildfly.org/viewLog.html?buildId=78521&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 797106f1a4640f945741688da91ae6f4fee49e47
Summary: Tests passed: 2974, ignored: 631; exit code 1 Build time: 00:37:03

**Comment by undertow-pull-request** [comment]
**Windows** [Build 2245](https://ci.wildfly.org/viewLog.html?buildId=78528&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 797106f1a4640f945741688da91ae6f4fee49e47
Summary: Tests failed: 1 (1 new), passed: 2973, ignored: 631 Build time: 00:35:54
### Failed tests
```
io.undertow.server.handlers.proxy.LoadBalancingProxyHTTP2ViaUpgradeTestCase.testLoadShared[proxy][http2]: java.lang.AssertionError
------- Stdout: -------
server1 {accept-encoding=[gzip,deflate], x-disable-push=[true], x-forwarded-server=[localhost], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], x-forwarded-proto=[http], x-forwarded-port=[7777], x-forwarded-for=[127.0.0.1], x-forwarded-host=[localhost], Host=[localhost:7777]}
server1 {accept-encoding=[gzip,deflate], x-disable-push=[true], x-forwarded-server=[localhost], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], x-forwarded-proto=[http], x-forwarded-port=[7777], x-forwarded-for=[127.0.0.1], x-forwarded-host=[localhost], Host=[localhost:7777]}
server1 {accept-encoding=[gzip,deflate], x-disable-push=[true], x-forwarded-server=[localhost], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], x-forwarded-proto=[http], x-forwarded-port=[7777], x-forwarded-for=[127.0.0.1], x-forwarded-host=[localhost], Host=[localhost:7777]}
server1 {accept-encoding=[gzip,deflate], x-disable-push=[true], x-forwarded-server=[localhost], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], x-forwarded-proto=[http], x-forwarded-port=[7777], x-forwarded-for=[127.0.0.1], x-forwarded-host=[localhost], Host=[localhost:7777]}
server1 {accept-encoding=[gzip,deflate], x-disable-push=[true], x-forwarded-server=[localhost], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], x-forwarded-proto=[http], x-forwarded-port=[7777], x-forwarded-for=[127.0.0.1], x-forwarded-host=[localhost], Host=[localhost:7777]}
server1 {accept-encoding=[gzip,deflate], x-disable-push=[true], x-forwarded-server=[localhost], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], x-forwarded-proto=[http], x-forwarded-port=[7777], x-forwarded-for=[127.0.0.1], x-forwarded-host=[localhost], Host=[localhost:7777]}
------- Stderr: -------
02:32:36,699 DEBUG (XNIO-1 I/O-3) [io.undertow.server.handlers.proxy] <ProxyHandler.java:547> Sending request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} to target localhost/127.0.0.1:8888 for exchange HttpServerExchange{ GET /name request {Connection=[Keep-Alive], Accept-Encoding=[gzip,deflate], User-Agent=[Apache-HttpClient/4.2.6 (java 1.5)], Host=[localhost:7777]} response {}}
02:32:36,702 DEBUG (XNIO-1 I/O-3) [io.undertow.server.handlers.proxy] <ProxyHandler.java:564> Sent request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} to target 127.0.0.1 for exchange HttpServerExchange{ GET /name request {Connection=[Keep-Alive], Accept-Encoding=[gzip,deflate], User-Agent=[Apache-HttpClient/4.2.6 (java 1.5)], Host=[localhost:7777]} response {}}
02:32:36,707 DEBUG (XNIO-1 I/O-5) [io.undertow.server.handlers.proxy] <ProxyHandler.java:547> Sending request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} to target localhost/127.0.0.1:7778 for exchange HttpServerExchange{ GET /name request {accept-encoding=[gzip,deflate], x-disable-push=[true], x-forwarded-server=[localhost], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], x-forwarded-proto=[http], x-forwarded-port=[7777], x-forwarded-for=[127.0.0.1], x-forwarded-host=[localhost], Host=[localhost:7777]} response {}}
02:32:36,711 DEBUG (XNIO-1 I/O-5) [io.undertow.server.handlers.proxy] <ProxyHandler.java:564> Sent request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} to target 127.0.0.1 for exchange HttpServerExchange{ GET /name request {accept-encoding=[gzip,deflate], x-disable-push=[true], x-forwarded-server=[localhost], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], x-forwarded-proto=[http], x-forwarded-port=[7777], x-forwarded-for=[127.0.0.1], x-forwarded-host=[localhost], Host=[localhost:7777]} response {}}
02:32:36,715 DEBUG (XNIO-1 I/O-5) [io.undertow.server.handlers.proxy] <ProxyHandler.java:689> Received response ClientResponse{responseHeaders={x-custom-header=[foo], content-length=[7], date=[Mon, 30 Oct 2017 09:32:16 GMT]}, responseCode=200, status='', protocol=HTTP/2.0} for request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} for exchange HttpServerExchange{ GET /name request {accept-encoding=[gzip,deflate], x-disable-push=[true], x-forwarded-server=[localhost], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], x-forwarded-proto=[http], x-forwarded-port=[7777], x-forwarded-for=[127.0.0.1], x-forwarded-host=[localhost], Host=[localhost:7777]} response {}}
02:32:36,721 DEBUG (XNIO-1 I/O-3) [io.undertow.server.handlers.proxy] <ProxyHandler.java:689> Received response ClientResponse{responseHeaders={x-custom-header=[foo], content-length=[7], date=[Mon, 30 Oct 2017 09:32:16 GMT]}, responseCode=200, status='', protocol=HTTP/2.0} for request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} for exchange HttpServerExchange{ GET /name request {Connection=[Keep-Alive], Accept-Encoding=[gzip,deflate], User-Agent=[Apache-HttpClient/4.2.6 (java 1.5)], Host=[localhost:7777]} response {}}
02:32:36,731 DEBUG (XNIO-1 I/O-4) [io.undertow.server.handlers.proxy] <ProxyHandler.java:547> Sending request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} to target localhost/127.0.0.1:8888 for exchange HttpServerExchange{ GET /name request {Connection=[Keep-Alive], Accept-Encoding=[gzip,deflate], User-Agent=[Apache-HttpClient/4.2.6 (java 1.5)], Host=[localhost:7777]} response {}}
02:32:36,733 DEBUG (XNIO-1 I/O-4) [io.undertow.server.handlers.proxy] <ProxyHandler.java:564> Sent request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} to target 127.0.0.1 for exchange HttpServerExchange{ GET /name request {Connection=[Keep-Alive], Accept-Encoding=[gzip,deflate], User-Agent=[Apache-HttpClient/4.2.6 (java 1.5)], Host=[localhost:7777]} response {}}
02:32:36,737 DEBUG (XNIO-1 I/O-6) [io.undertow.server.handlers.proxy] <ProxyHandler.java:547> Sending request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} to target localhost/127.0.0.1:7778 for exchange HttpServerExchange{ GET /name request {accept-encoding=[gzip,deflate], x-disable-push=[true], x-forwarded-server=[localhost], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], x-forwarded-proto=[http], x-forwarded-port=[7777], x-forwarded-for=[127.0.0.1], x-forwarded-host=[localhost], Host=[localhost:7777]} response {}}
02:32:36,741 DEBUG (XNIO-1 I/O-6) [io.undertow.server.handlers.proxy] <ProxyHandler.java:564> Sent request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} to target 127.0.0.1 for exchange HttpServerExchange{ GET /name request {accept-encoding=[gzip,deflate], x-disable-push=[true], x-forwarded-server=[localhost], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], x-forwarded-proto=[http], x-forwarded-port=[7777], x-forwarded-for=[127.0.0.1], x-forwarded-host=[localhost], Host=[localhost:7777]} response {}}
02:32:36,745 DEBUG (XNIO-1 I/O-6) [io.undertow.server.handlers.proxy] <ProxyHandler.java:689> Received response ClientResponse{responseHeaders={x-custom-header=[foo], content-length=[7], date=[Mon, 30 Oct 2017 09:32:16 GMT]}, responseCode=200, status='', protocol=HTTP/2.0} for request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} for exchange HttpServerExchange{ GET /name request {accept-encoding=[gzip,deflate], x-disable-push=[true], x-forwarded-server=[localhost], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], x-forwarded-proto=[http], x-forwarded-port=[7777], x-forwarded-for=[127.0.0.1], x-forwarded-host=[localhost], Host=[localhost:7777]} response {}}
02:32:36,751 DEBUG (XNIO-1 I/O-4) [io.undertow.server.handlers.proxy] <ProxyHandler.java:689> Received response ClientResponse{responseHeaders={x-custom-header=[foo], content-length=[7], date=[Mon, 30 Oct 2017 09:32:16 GMT]}, responseCode=200, status='', protocol=HTTP/2.0} for request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} for exchange HttpServerExchange{ GET /name request {Connection=[Keep-Alive], Accept-Encoding=[gzip,deflate], User-Agent=[Apache-HttpClient/4.2.6 (java 1.5)], Host=[localhost:7777]} response {}}
02:32:36,759 DEBUG (XNIO-1 I/O-5) [io.undertow.server.handlers.proxy] <ProxyHandler.java:547> Sending request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} to target localhost/127.0.0.1:8888 for exchange HttpServerExchange{ GET /name request {Connection=[Keep-Alive], Accept-Encoding=[gzip,deflate], User-Agent=[Apache-HttpClient/4.2.6 (java 1.5)], Host=[localhost:7777]} response {}}
02:32:36,763 DEBUG (XNIO-1 I/O-5) [io.undertow.server.handlers.proxy] <ProxyHandler.java:564> Sent request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} to target 127.0.0.1 for exchange HttpServerExchange{ GET /name request {Connection=[Keep-Alive], Accept-Encoding=[gzip,deflate], User-Agent=[Apache-HttpClient/4.2.6 (java 1.5)], Host=[localhost:7777]} response {}}
02:32:36,766 DEBUG (XNIO-1 I/O-8) [io.undertow.server.handlers.proxy] <ProxyHandler.java:547> Sending request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} to target localhost/127.0.0.1:7778 for exchange HttpServerExchange{ GET /name request {accept-encoding=[gzip,deflate], x-disable-push=[true], x-forwarded-server=[localhost], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], x-forwarded-proto=[http], x-forwarded-port=[7777], x-forwarded-for=[127.0.0.1], x-forwarded-host=[localhost], Host=[localhost:7777]} response {}}
02:32:36,769 DEBUG (XNIO-1 I/O-8) [io.undertow.server.handlers.proxy] <ProxyHandler.java:564> Sent request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} to target 127.0.0.1 for exchange HttpServerExchange{ GET /name request {accept-encoding=[gzip,deflate], x-disable-push=[true], x-forwarded-server=[localhost], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], x-forwarded-proto=[http], x-forwarded-port=[7777], x-forwarded-for=[127.0.0.1], x-forwarded-host=[localhost], Host=[localhost:7777]} response {}}
02:32:36,774 DEBUG (XNIO-1 I/O-8) [io.undertow.server.handlers.proxy] <ProxyHandler.java:689> Received response ClientResponse{responseHeaders={x-custom-header=[foo], content-length=[7], date=[Mon, 30 Oct 2017 09:32:16 GMT]}, responseCode=200, status='', protocol=HTTP/2.0} for request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} for exchange HttpServerExchange{ GET /name request {accept-encoding=[gzip,deflate], x-disable-push=[true], x-forwarded-server=[localhost], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], x-forwarded-proto=[http], x-forwarded-port=[7777], x-forwarded-for=[127.0.0.1], x-forwarded-host=[localhost], Host=[localhost:7777]} response {}}
02:32:36,780 DEBUG (XNIO-1 I/O-5) [io.undertow.server.handlers.proxy] <ProxyHandler.java:689> Received response ClientResponse{responseHeaders={x-custom-header=[foo], content-length=[7], date=[Mon, 30 Oct 2017 09:32:16 GMT]}, responseCode=200, status='', protocol=HTTP/2.0} for request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} for exchange HttpServerExchange{ GET /name request {Connection=[Keep-Alive], Accept-Encoding=[gzip,deflate], User-Agent=[Apache-HttpClient/4.2.6 (java 1.5)], Host=[localhost:7777]} response {}}
02:32:36,788 DEBUG (XNIO-1 I/O-6) [io.undertow.server.handlers.proxy] <ProxyHandler.java:547> Sending request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} to target localhost/127.0.0.1:8888 for exchange HttpServerExchange{ GET /name request {Connection=[Keep-Alive], Accept-Encoding=[gzip,deflate], User-Agent=[Apache-HttpClient/4.2.6 (java 1.5)], Host=[localhost:7777]} response {}}
02:32:36,791 DEBUG (XNIO-1 I/O-6) [io.undertow.server.handlers.proxy] <ProxyHandler.java:564> Sent request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} to target 127.0.0.1 for exchange HttpServerExchange{ GET /name request {Connection=[Keep-Alive], Accept-Encoding=[gzip,deflate], User-Agent=[Apache-HttpClient/4.2.6 (java 1.5)], Host=[localhost:7777]} response {}}
02:32:36,794 DEBUG (XNIO-1 I/O-8) [io.undertow.server.handlers.proxy] <ProxyHandler.java:547> Sending request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} to target localhost/127.0.0.1:7778 for exchange HttpServerExchange{ GET /name request {accept-encoding=[gzip,deflate], x-disable-push=[true], x-forwarded-server=[localhost], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], x-forwarded-proto=[http], x-forwarded-port=[7777], x-forwarded-for=[127.0.0.1], x-forwarded-host=[localhost], Host=[localhost:7777]} response {}}
02:32:36,799 DEBUG (XNIO-1 I/O-8) [io.undertow.server.handlers.proxy] <ProxyHandler.java:564> Sent request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} to target 127.0.0.1 for exchange HttpServerExchange{ GET /name request {accept-encoding=[gzip,deflate], x-disable-push=[true], x-forwarded-server=[localhost], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], x-forwarded-proto=[http], x-forwarded-port=[7777], x-forwarded-for=[127.0.0.1], x-forwarded-host=[localhost], Host=[localhost:7777]} response {}}
02:32:36,803 DEBUG (XNIO-1 I/O-8) [io.undertow.server.handlers.proxy] <ProxyHandler.java:689> Received response ClientResponse{responseHeaders={x-custom-header=[foo], content-length=[7], date=[Mon, 30 Oct 2017 09:32:16 GMT]}, responseCode=200, status='', protocol=HTTP/2.0} for request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} for exchange HttpServerExchange{ GET /name request {accept-encoding=[gzip,deflate], x-disable-push=[true], x-forwarded-server=[localhost], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], x-forwarded-proto=[http], x-forwarded-port=[7777], x-forwarded-for=[127.0.0.1], x-forwarded-host=[localhost], Host=[localhost:7777]} response {}}
02:32:36,808 DEBUG (XNIO-1 I/O-6) [io.undertow.server.handlers.proxy] <ProxyHandler.java:689> Received response ClientResponse{responseHeaders={x-custom-header=[foo], content-length=[7], date=[Mon, 30 Oct 2017 09:32:16 GMT]}, responseCode=200, status='', protocol=HTTP/2.0} for request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} for exchange HttpServerExchange{ GET /name request {Connection=[Keep-Alive], Accept-Encoding=[gzip,deflate], User-Agent=[Apache-HttpClient/4.2.6 (java 1.5)], Host=[localhost:7777]} response {}}
02:32:36,817 DEBUG (XNIO-1 I/O-7) [io.undertow.server.handlers.proxy] <ProxyHandler.java:547> Sending request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} to target localhost/127.0.0.1:8888 for exchange HttpServerExchange{ GET /name request {Connection=[Keep-Alive], Accept-Encoding=[gzip,deflate], User-Agent=[Apache-HttpClient/4.2.6 (java 1.5)], Host=[localhost:7777]} response {}}
02:32:36,821 DEBUG (XNIO-1 I/O-7) [io.undertow.server.handlers.proxy] <ProxyHandler.java:564> Sent request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} to target 127.0.0.1 for exchange HttpServerExchange{ GET /name request {Connection=[Keep-Alive], Accept-Encoding=[gzip,deflate], User-Agent=[Apache-HttpClient/4.2.6 (java 1.5)], Host=[localhost:7777]} response {}}
02:32:36,824 DEBUG (XNIO-1 I/O-2) [io.undertow.server.handlers.proxy] <ProxyHandler.java:547> Sending request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} to target localhost/127.0.0.1:7778 for exchange HttpServerExchange{ GET /name request {accept-encoding=[gzip,deflate], x-disable-push=[true], x-forwarded-server=[localhost], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], x-forwarded-proto=[http], x-forwarded-port=[7777], x-forwarded-for=[127.0.0.1], x-forwarded-host=[localhost], Host=[localhost:7777]} response {}}
02:32:36,828 DEBUG (XNIO-1 I/O-2) [io.undertow.server.handlers.proxy] <ProxyHandler.java:564> Sent request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} to target 127.0.0.1 for exchange HttpServerExchange{ GET /name request {accept-encoding=[gzip,deflate], x-disable-push=[true], x-forwarded-server=[localhost], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], x-forwarded-proto=[http], x-forwarded-port=[7777], x-forwarded-for=[127.0.0.1], x-forwarded-host=[localhost], Host=[localhost:7777]} response {}}
02:32:36,833 DEBUG (XNIO-1 I/O-2) [io.undertow.server.handlers.proxy] <ProxyHandler.java:689> Received response ClientResponse{responseHeaders={x-custom-header=[foo], content-length=[7], date=[Mon, 30 Oct 2017 09:32:16 GMT]}, responseCode=200, status='', protocol=HTTP/2.0} for request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} for exchange HttpServerExchange{ GET /name request {accept-encoding=[gzip,deflate], x-disable-push=[true], x-forwarded-server=[localhost], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], x-forwarded-proto=[http], x-forwarded-port=[7777], x-forwarded-for=[127.0.0.1], x-forwarded-host=[localhost], Host=[localhost:7777]} response {}}
02:32:36,839 DEBUG (XNIO-1 I/O-7) [io.undertow.server.handlers.proxy] <ProxyHandler.java:689> Received response ClientResponse{responseHeaders={x-custom-header=[foo], content-length=[7], date=[Mon, 30 Oct 2017 09:32:16 GMT]}, responseCode=200, status='', protocol=HTTP/2.0} for request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} for exchange HttpServerExchange{ GET /name request {Connection=[Keep-Alive], Accept-Encoding=[gzip,deflate], User-Agent=[Apache-HttpClient/4.2.6 (java 1.5)], Host=[localhost:7777]} response {}}
02:32:36,848 DEBUG (XNIO-1 I/O-8) [io.undertow.server.handlers.proxy] <ProxyHandler.java:547> Sending request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} to target localhost/127.0.0.1:8888 for exchange HttpServerExchange{ GET /name request {Connection=[Keep-Alive], Accept-Encoding=[gzip,deflate], User-Agent=[Apache-HttpClient/4.2.6 (java 1.5)], Host=[localhost:7777]} response {}}
02:32:36,851 DEBUG (XNIO-1 I/O-8) [io.undertow.server.handlers.proxy] <ProxyHandler.java:564> Sent request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} to target 127.0.0.1 for exchange HttpServerExchange{ GET /name request {Connection=[Keep-Alive], Accept-Encoding=[gzip,deflate], User-Agent=[Apache-HttpClient/4.2.6 (java 1.5)], Host=[localhost:7777]} response {}}
02:32:36,855 DEBUG (XNIO-1 I/O-2) [io.undertow.server.handlers.proxy] <ProxyHandler.java:547> Sending request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} to target localhost/127.0.0.1:7778 for exchange HttpServerExchange{ GET /name request {accept-encoding=[gzip,deflate], x-disable-push=[true], x-forwarded-server=[localhost], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], x-forwarded-proto=[http], x-forwarded-port=[7777], x-forwarded-for=[127.0.0.1], x-forwarded-host=[localhost], Host=[localhost:7777]} response {}}
02:32:36,858 DEBUG (XNIO-1 I/O-2) [io.undertow.server.handlers.proxy] <ProxyHandler.java:564> Sent request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} to target 127.0.0.1 for exchange HttpServerExchange{ GET /name request {accept-encoding=[gzip,deflate], x-disable-push=[true], x-forwarded-server=[localhost], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], x-forwarded-proto=[http], x-forwarded-port=[7777], x-forwarded-for=[127.0.0.1], x-forwarded-host=[localhost], Host=[localhost:7777]} response {}}
02:32:36,862 DEBUG (XNIO-1 I/O-2) [io.undertow.server.handlers.proxy] <ProxyHandler.java:689> Received response ClientResponse{responseHeaders={x-custom-header=[foo], content-length=[7], date=[Mon, 30 Oct 2017 09:32:16 GMT]}, responseCode=200, status='', protocol=HTTP/2.0} for request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} for exchange HttpServerExchange{ GET /name request {accept-encoding=[gzip,deflate], x-disable-push=[true], x-forwarded-server=[localhost], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], x-forwarded-proto=[http], x-forwarded-port=[7777], x-forwarded-for=[127.0.0.1], x-forwarded-host=[localhost], Host=[localhost:7777]} response {}}
02:32:36,867 DEBUG (XNIO-1 I/O-8) [io.undertow.server.handlers.proxy] <ProxyHandler.java:689> Received response ClientResponse{responseHeaders={x-custom-header=[foo], content-length=[7], date=[Mon, 30 Oct 2017 09:32:16 GMT]}, responseCode=200, status='', protocol=HTTP/2.0} for request ClientRequest{path='/name', method=GET, protocol=HTTP/1.1} for exchange HttpServerExchange{ GET /name request {Connection=[Keep-Alive], Accept-Encoding=[gzip,deflate], User-Agent=[Apache-HttpClient/4.2.6 (java 1.5)], Host=[localhost:7777]} response {}}


```

**Comment by stuartwdouglas** [comment]
Retest this please

**Comment by undertow-pull-request** [comment]
**Windows** [Build 2249](https://ci.wildfly.org/viewLog.html?buildId=78537&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 797106f1a4640f945741688da91ae6f4fee49e47
Summary: Tests failed: 2 (2 new), passed: 2972, ignored: 631 Build time: 00:36:01
### Failed tests
```
io.undertow.server.handlers.proxy.LoadBalancingProxyHTTP2TestCase.testMaxRetries[proxy][https]: java.lang.RuntimeException: Buffer Leak io.undertow.server.handlers.proxy.LoadBalancingProxyHTTP2TestCase.testMaxRetries[proxy][https]
Caused by: java.lang.RuntimeException: java.nio.DirectByteBuffer[pos=0 lim=8192 cap=8192] NO: 40704 [NO_CONTEXT]
------- Stderr: -------
lientExchange] <HttpClientExchange.java:103> response terminated for request to localhost/127.0.0.1:8888 /fail
04:10:56,494 DEBUG (XNIO-1 I/O-6) [io.undertow.client.http.HttpClientConnection] <HttpClientConnection.java:479> exchange complete in connection to localhost/127.0.0.1:8888
java.lang.RuntimeException: java.nio.DirectByteBuffer[pos=0 lim=8192 cap=8192] NO: 40704 [NO_CONTEXT]
	at io.undertow.testutils.DebuggingSlicePool$DebuggingBuffer.<init>(DebuggingSlicePool.java:84)
	at io.undertow.testutils.DebuggingSlicePool.allocate(DebuggingSlicePool.java:45)
	at io.undertow.client.http2.Http2ClearClientProvider.createSettingsFrame(Http2ClearClientProvider.java:147)
	at io.undertow.client.http2.Http2ClearClientProvider.createHeaders(Http2ClearClientProvider.java:137)
	at io.undertow.client.http2.Http2ClearClientProvider.access$000(Http2ClearClientProvider.java:65)
	at io.undertow.client.http2.Http2ClearClientProvider$3.handleEvent(Http2ClearClientProvider.java:122)
	at io.undertow.client.http2.Http2ClearClientProvider$3.handleEvent(Http2ClearClientProvider.java:119)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.nio.WorkerThread$ConnectHandle.handleReady(WorkerThread.java:326)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:561)
04:10:56,696 DEBUG (XNIO-88 I/O-3) [io.undertow.request.io] <AlpnOpenListener.java:367> UT005013: An IOException occurred: javax.net.ssl.SSLHandshakeException: UT000140: Initial SSL/TLS data is not a handshake record
	at io.undertow.protocols.ssl.ALPNHackClientHelloExplorer.exploreClientHello(ALPNHackClientHelloExplorer.java:84)
	at io.undertow.protocols.ssl.ALPNHackSSLEngine.unwrap(ALPNHackSSLEngine.java:205)
	at io.undertow.server.protocol.http.ALPNLimitingSSLEngine.unwrap(ALPNLimitingSSLEngine.java:151)
	at io.undertow.protocols.ssl.SslConduit.doUnwrap(SslConduit.java:732)
	at io.undertow.protocols.ssl.SslConduit.read(SslConduit.java:567)
	at org.xnio.conduits.ConduitStreamSourceChannel.read(ConduitStreamSourceChannel.java:127)
	at io.undertow.server.protocol.http.AlpnOpenListener$AlpnConnectionListener.handleEvent(AlpnOpenListener.java:325)
	at io.undertow.server.protocol.http.AlpnOpenListener.handleEvent(AlpnOpenListener.java:280)
	at io.undertow.server.protocol.http.AlpnOpenListener.handleEvent(AlpnOpenListener.java:60)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.ChannelListeners$DelegatingChannelListener.handleEvent(ChannelListeners.java:1092)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.nio.QueuedNioTcpServer$1.run(QueuedNioTcpServer.java:129)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:582)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:466)


io.undertow.server.handlers.proxy.LoadBalancingProxyAJPTestCase.testOldBackend[proxy][https]: java.lang.RuntimeException: Buffer Leak io.undertow.server.handlers.proxy.LoadBalancingProxyAJPTestCase.testOldBackend[proxy][https]
Caused by: java.lang.RuntimeException: java.nio.DirectByteBuffer[pos=0 lim=17408 cap=17408] NO: 42384 [NO_CONTEXT]
------- Stderr: -------
04:11:15,307 DEBUG (XNIO-101 I/O-4) [io.undertow.request.io] <AjpReadListener.java:260> UT005014: Failed to parse request: io.undertow.util.BadRequestException: java.io.IOException: UT000066: Incorrect magic number 18245 for AJP packet header
	at io.undertow.server.protocol.ajp.AjpRequestParser.parse(AjpRequestParser.java:197)
	at io.undertow.server.protocol.ajp.AjpReadListener.handleEvent(AjpReadListener.java:169)
	at io.undertow.server.protocol.ajp.AjpOpenListener.handleEvent(AjpOpenListener.java:143)
	at io.undertow.server.protocol.ajp.AjpOpenListener.handleEvent(AjpOpenListener.java:52)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.nio.QueuedNioTcpServer$1.run(QueuedNioTcpServer.java:129)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:582)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:466)
Caused by: java.io.IOException: UT000066: Incorrect magic number 18245 for AJP packet header
	... 11 more

04:11:15,431 DEBUG (XNIO-101 I/O-1) [io.undertow.request.io] <AjpReadListener.java:260> UT005014: Failed to parse request: io.undertow.util.BadRequestException: java.io.IOException: UT000066: Incorrect magic number 5635 for AJP packet header
	at io.undertow.server.protocol.ajp.AjpRequestParser.parse(AjpRequestParser.java:197)
	at io.undertow.server.protocol.ajp.AjpReadListener.handleEvent(AjpReadListener.java:169)
	at io.undertow.server.protocol.ajp.AjpReadListener.handleEvent(AjpReadListener.java:56)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:561)
Caused by: java.io.IOException: UT000066: Incorrect magic number 5635 for AJP packet header
	... 7 more

java.lang.RuntimeException: java.nio.DirectByteBuffer[pos=0 lim=17408 cap=17408] NO: 42384 [NO_CONTEXT]
	at io.undertow.testutils.DebuggingSlicePool$DebuggingBuffer.<init>(DebuggingSlicePool.java:84)
	at io.undertow.testutils.DebuggingSlicePool.allocate(DebuggingSlicePool.java:45)
	at io.undertow.protocols.ssl.SslConduit.doUnwrap(SslConduit.java:699)
	at io.undertow.protocols.ssl.SslConduit.doHandshake(SslConduit.java:648)
	at io.undertow.protocols.ssl.SslConduit.access$900(SslConduit.java:63)
	at io.undertow.protocols.ssl.SslConduit$SslReadReadyHandler.readReady(SslConduit.java:1111)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:561)


```

**Comment by undertow-pull-request** [comment]
**Linux** [Build 2510](https://ci.wildfly.org/viewLog.html?buildId=78992&buildTypeId=UT_MASTER_LINUX) outcome was **FAILURE** using a merge of 797106f1a4640f945741688da91ae6f4fee49e47
Summary: Compilation error: Compiler (new) Build time: 00:00:13

**Comment by undertow-pull-request** [comment]
**Windows** [Build 2264](https://ci.wildfly.org/viewLog.html?buildId=78993&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 797106f1a4640f945741688da91ae6f4fee49e47
Summary: Compilation error: Compiler (new) Build time: 00:00:42

**Pull request closed without merging**
