### PR TITLE
[UNDERTOW-2254] Included the HttpServerExchange in the HostSelector.

### PR DESCRIPTION
**Pull request by jeham**
This allows for advanced routing based on eg. header values or attributes.
Jira: https://issues.redhat.com/browse/UNDERTOW-2254

### CODE REVIEW

**Review by fl4via — CHANGES_REQUESTED** [review]
I'm approving this for Undertow 2.4.0.Final (because of the changes in signatures.
However, we will want to keep the old HostSelector .selectHost methods and mark them as deprecated with forRemoval set to true. 
I'll also ask you to add the [UNDERTOW-2254] prefix to the commit message.
Thank you for your PR!

**Comment by fl4via** [comment]
Also, please rebase it because the test failures we are seeing are supposed to have been fixed in master (UNDERTOW-2252), so hopefully after rebase they will be gone.

**Comment by fl4via** [comment]
> Thanks for the feedback @fl4via ! I updated the code and the commit message. I tried to rebase but got conflicts in all POM files though.

@jeham do you mind if I do the rebase then? I can pull a rebased version and kick off CI.
There is one thing that is calling my attention, though, and when I first reviewed this I didn't take notice. The PR should be done against master.
Do you need this feature specifically for 2.2.x?

**Comment by jeham** [comment]
Thanks for the reply @fl4via - I'll create a new PR from master.

**Pull request closed without merging**
