### PR TITLE
[UNDERTOW-463] Deprecate the SecurityContextFactory.

### PR DESCRIPTION
**Pull request by darranl**
Instead a new AbstractSecurityContextAssociationHandler can be extended to provide custom implementations.

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1464](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=55259&buildTypeId=UT_MASTER_LINUX) is now running using a merge of 6fb41d1119a43f89ad4a2cabb671ee2d0a22d709

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1183](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=55260&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 6fb41d1119a43f89ad4a2cabb671ee2d0a22d709

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1183](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=55260&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 6fb41d1119a43f89ad4a2cabb671ee2d0a22d709
Summary: Tests failed: 13 (10 new), passed: 2494, ignored: 375 Build time: 0:13:41
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.handlers.PredicatedHandlersProxyTestCase.testProxy{proxy}{spdy}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxyHTTP2TestCase.testHeadersAreLowercase{proxy}{http2}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxySPDYTestCase.testStickySessions{proxy}{http2-clear}: <no details avaliable>

io.undertow.servlet.test.defaultservlet.DefaultServletTestCase.testIfMoodifiedSince: <no details avaliable>

io.undertow.servlet.test.defaultservlet.DefaultServletTestCase.testIfMoodifiedSince{proxy}: <no details avaliable>

io.undertow.servlet.test.defaultservlet.DefaultServletTestCase.testIfMoodifiedSince{proxy}{ajp}: <no details avaliable>

io.undertow.servlet.test.defaultservlet.DefaultServletTestCase.testIfMoodifiedSince{proxy}{spdy}: <no details avaliable>

io.undertow.servlet.test.defaultservlet.DefaultServletTestCase.testIfMoodifiedSince{proxy}{https}: <no details avaliable>

io.undertow.servlet.test.defaultservlet.DefaultServletTestCase.testIfMoodifiedSince{proxy}{http2}: <no details avaliable>

io.undertow.servlet.test.defaultservlet.DefaultServletTestCase.testIfMoodifiedSince{proxy}{http2-clear}: <no details avaliable>

io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testDigestSuccess{proxy}{ajp}: <no details avaliable>


##### there are 3 more failed tests, see build details
```

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1464](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=55259&buildTypeId=UT_MASTER_LINUX) outcome was **FAILURE** using a merge of 6fb41d1119a43f89ad4a2cabb671ee2d0a22d709
Summary: Tests failed: 1 (1 new), passed: 2583, ignored: 298 Build time: 0:15:56
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.handlers.PredicatedHandlersProxyTestCase.testProxy{proxy}{spdy}: <no details avaliable>

```

**Comment by darranl** [comment]
Retest this please

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1465](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=55369&buildTypeId=UT_MASTER_LINUX) is now running using a merge of 6fb41d1119a43f89ad4a2cabb671ee2d0a22d709

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1184](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=55370&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 6fb41d1119a43f89ad4a2cabb671ee2d0a22d709

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1184](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=55370&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 140c40da72507ab56532c83f792ce7c676b8d8a2
Summary: Tests failed: 9 (6 new), passed: 2498, ignored: 375 Build time: 0:13:24
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testDigestSuccess{proxy}: <no details avaliable>

io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testNonceCountReUse{proxy}: <no details avaliable>

io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testNonceCountReUse{proxy}{ajp}: <no details avaliable>

io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testDigestSuccess{proxy}{https}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxyHTTP2ViaUpgradeTestCase.testHeadersAreLowercase{proxy}{http2}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxyHTTP2ViaUpgradeTestCase.testStickySessions{proxy}{http2}: <no details avaliable>

io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testDigestSuccess{proxy}{ajp}: <no details avaliable>

io.undertow.server.handlers.PredicatedHandlersProxyTestCase.testProxy{proxy}{spdy}: <no details avaliable>

io.undertow.websockets.jsr.test.stress.WebsocketStressTestCase.webSocketStressTestCase: <no details avaliable>

```

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1465](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=55369&buildTypeId=UT_MASTER_LINUX) outcome was **FAILURE** using a merge of 140c40da72507ab56532c83f792ce7c676b8d8a2
Summary: Tests failed: 1, passed: 2583, ignored: 298 Build time: 0:14:40
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.handlers.PredicatedHandlersProxyTestCase.testProxy{proxy}{spdy}: <no details avaliable>

```

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1185](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=55379&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 140c40da72507ab56532c83f792ce7c676b8d8a2

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1466](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=55378&buildTypeId=UT_MASTER_LINUX) is now running using a merge of 140c40da72507ab56532c83f792ce7c676b8d8a2

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1185](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=55379&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 140c40da72507ab56532c83f792ce7c676b8d8a2
Summary: Tests failed: 6 (3 new), passed: 2501, ignored: 375 Build time: 0:14:05
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testDigestSuccess: <no details avaliable>

io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testNonceCountReUse: <no details avaliable>

io.undertow.server.handlers.blocking.SimpleBlockingServerTestCase.testLargeRequest{proxy}{http2-clear}: <no details avaliable>

io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testDigestSuccess{proxy}{ajp}: <no details avaliable>

io.undertow.server.handlers.PredicatedHandlersProxyTestCase.testProxy{proxy}{spdy}: <no details avaliable>

io.undertow.websockets.jsr.test.stress.WebsocketStressTestCase.webSocketStressTestCase: <no details avaliable>

```

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1466](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=55378&buildTypeId=UT_MASTER_LINUX) outcome was **FAILURE** using a merge of 140c40da72507ab56532c83f792ce7c676b8d8a2
Summary: Tests failed: 1, passed: 2583, ignored: 298 Build time: 0:14:39
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.handlers.PredicatedHandlersProxyTestCase.testProxy{proxy}{spdy}: <no details avaliable>

```

**Pull request merged**
