### PR TITLE
Fix for checkstyle plugin configuration for jdk9 profile wrt update t…

### PR DESCRIPTION
**Pull request by jstourac**
…o new version.

Fix for commit 3cbae78af439e253f6f1bac731c5a362f71f5480.

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
**Windows** [Build 2440](https://ci.wildfly.org/viewLog.html?buildId=101582&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of bc06441e8922482d46d2f45bd36a66f55e2e19ab
Summary: Execution timeout (new); tests passed: 2972, ignored: 690 Build time: 00:45:20

**Comment by jstourac** [comment]
retest this please

**Comment by undertow-pull-request** [comment]
**Windows** [Build 2443](https://ci.wildfly.org/viewLog.html?buildId=102629&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of bc06441e8922482d46d2f45bd36a66f55e2e19ab
Summary: Tests failed: 1 (1 new), passed: 3047, ignored: 690 Build time: 00:23:33
### Failed tests
```
io.undertow.server.handlers.ReceiverTestCase.testAsyncReceiveWholeBytesFailed[proxy][http2]: java.lang.AssertionError
	at io.undertow.server.handlers.ReceiverTestCase.testAsyncReceiveWholeBytesFailed(ReceiverTestCase.java:194)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:503)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:98)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:276)
------- Stderr: -------
10:45:00,617 DEBUG (XNIO-1 I/O-5) [io.undertow.server.handlers.proxy] <ProxyHandler.java:549> Sending request ClientRequest{path='/fullbytes', method=POST, protocol=HTTP/1.1} to target localhost/127.0.0.1:8888 for exchange HttpServerExchange{ POST /fullbytes request {Content-Length=[130000100], Host=[localhost]} response {}}
10:45:00,618 DEBUG (XNIO-1 I/O-5) [io.undertow.server.handlers.proxy] <ProxyHandler.java:566> Sent request ClientRequest{path='/fullbytes', method=POST, protocol=HTTP/1.1} to target 127.0.0.1 for exchange HttpServerExchange{ POST /fullbytes request {Content-Length=[130000100], Host=[localhost]} response {}}
10:45:00,631 ERROR (XNIO-1 I/O-5) [io.undertow.proxy] <ProxyHandler.java:662> UT005028: Proxy request to /fullbytes failed: java.nio.channels.ClosedChannelException
	at io.undertow.client.http2.Http2ClientConnection$1.handleEvent(Http2ClientConnection.java:107)
	at io.undertow.client.http2.Http2ClientConnection$1.handleEvent(Http2ClientConnection.java:99)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameCloseListener.handleEvent(AbstractFramedChannel.java:1061)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameCloseListener.handleEvent(AbstractFramedChannel.java:975)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at io.undertow.protocols.ssl.SslConduit$SslReadReadyHandler.terminated(SslConduit.java:1202)
	at org.xnio.nio.NioSocketConduit.readTerminated(NioSocketConduit.java:360)
	at org.xnio.nio.NioSocketStreamConnection.notifyReadClosed(NioSocketStreamConnection.java:148)
	at org.xnio.Connection.close(Connection.java:139)
	at org.xnio.IoUtils.safeClose(IoUtils.java:134)
	at io.undertow.protocols.ssl.SslConduit.closed(SslConduit.java:1037)
	at io.undertow.protocols.ssl.SslConduit.close(SslConduit.java:1108)
	at io.undertow.protocols.ssl.UndertowSslConnection.closeAction(UndertowSslConnection.java:149)
	at org.xnio.Connection.close(Connection.java:132)
	at org.xnio.IoUtils.safeClose(IoUtils.java:134)
	at io.undertow.server.protocol.framed.AbstractFramedChannel.close(AbstractFramedChannel.java:816)
	at org.xnio.IoUtils.safeClose(IoUtils.java:134)
	at io.undertow.protocols.http2.Http2Channel.sendGoAway(Http2Channel.java:832)
	at io.undertow.protocols.http2.Http2Channel.sendGoAway(Http2Channel.java:809)
	at io.undertow.client.http2.Http2ClientConnection.close(Http2ClientConnection.java:303)
	at org.xnio.IoUtils.safeClose(IoUtils.java:134)
	at io.undertow.server.handlers.proxy.ProxyHandler$IoExceptionHandler.handleException(ProxyHandler.java:790)
	at org.xnio.ChannelListeners.invokeChannelExceptionHandler(ChannelListeners.java:126)
	at io.undertow.util.Transfer$TransferListener.handleEvent(Transfer.java:218)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at io.undertow.server.protocol.framed.AbstractFramedStreamSinkChannel$1.run(AbstractFramedStreamSinkChannel.java:214)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$1.run(AbstractFramedChannel.java:137)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:582)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:466)

10:45:00,632 DEBUG (XNIO-1 I/O-7) [io.undertow.request.io] <AbstractFramedChannel.java:840> Marking reads broken on channel Http2Channel peer /127.0.0.1:65406 local 0.0.0.0/0.0.0.0:8888[ No Receiver [] -- [] -- []]: java.nio.channels.ClosedChannelException
	at io.undertow.server.protocol.framed.AbstractFramedChannel.markReadsBroken(AbstractFramedChannel.java:840)
	at io.undertow.server.protocol.framed.AbstractFramedChannel.receive(AbstractFramedChannel.java:476)
	at io.undertow.server.protocol.http2.Http2ReceiveListener.handleEvent(Http2ReceiveListener.java:112)
	at io.undertow.server.protocol.http2.Http2ReceiveListener.handleEvent(Http2ReceiveListener.java:61)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:948)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:929)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at io.undertow.protocols.ssl.SslConduit$SslReadReadyHandler.readReady(SslConduit.java:1161)


```

**Comment by undertow-pull-request** [comment]
**Windows** [Build 2444](https://ci.wildfly.org/viewLog.html?buildId=102635&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of bc06441e8922482d46d2f45bd36a66f55e2e19ab
Summary: Tests failed: 1 (1 new), passed: 3047, ignored: 690 Build time: 00:23:26
### Failed tests
```
io.undertow.server.handlers.HttpContinueAcceptingHandlerTestCase.testHttpContinueRejected[proxy][http2-clear-upgrade]: java.lang.AssertionError: expected:<417> but was:<200>
	at io.undertow.server.handlers.HttpContinueAcceptingHandlerTestCase.testHttpContinueRejected(HttpContinueAcceptingHandlerTestCase.java:104)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:503)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:98)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:276)
------- Stderr: -------
11:39:13,639 DEBUG (XNIO-1 I/O-1) [io.undertow.server.handlers.proxy] <ProxyHandler.java:549> Sending request ClientRequest{path='/path', method=POST, protocol=HTTP/1.1} to target localhost/127.0.0.1:8888 for exchange HttpServerExchange{ POST /path request {Connection=[Keep-Alive], Expect=[100-continue], Content-Length=[16], Content-Type=[text/plain; charset=ISO-8859-1], Host=[localhost:7777]} response {}}
11:39:13,640 DEBUG (XNIO-1 I/O-1) [io.undertow.server.handlers.proxy] <ProxyHandler.java:566> Sent request ClientRequest{path='/path', method=POST, protocol=HTTP/1.1} to target 127.0.0.1 for exchange HttpServerExchange{ POST /path request {Connection=[Keep-Alive], Expect=[100-continue], Content-Length=[16], Content-Type=[text/plain; charset=ISO-8859-1], Host=[localhost:7777]} response {}}
11:39:13,642 DEBUG (XNIO-1 I/O-1) [io.undertow.server.handlers.proxy] <ProxyHandler.java:576> Received continue response to request ClientRequest{path='/path', method=POST, protocol=HTTP/1.1} to target localhost/127.0.0.1:8888 for exchange HttpServerExchange{ POST /path request {Connection=[Keep-Alive], Expect=[100-continue], Content-Length=[16], Content-Type=[text/plain; charset=ISO-8859-1], Host=[localhost:7777]} response {}}
11:39:13,643 DEBUG (XNIO-1 I/O-1) [io.undertow.client.http.HttpClientExchange] <HttpClientExchange.java:87> request terminated for request to localhost/127.0.0.1:8888 /path
11:39:13,644 DEBUG (XNIO-1 I/O-1) [io.undertow.client.http.HttpClientConnection] <HttpClientConnection.java:447> connection to localhost/127.0.0.1:8888 is being upgraded
11:39:13,644 DEBUG (XNIO-1 I/O-1) [io.undertow.server.handlers.proxy] <ProxyHandler.java:691> Received response ClientResponse{responseHeaders={content-length=[16], date=[Mon, 07 May 2018 18:37:34 GMT]}, responseCode=200, status='', protocol=HTTP/2.0} for request ClientRequest{path='/path', method=POST, protocol=HTTP/1.1} for exchange HttpServerExchange{ POST /path request {Connection=[Keep-Alive], Expect=[100-continue], Content-Length=[16], Content-Type=[text/plain; charset=ISO-8859-1], Host=[localhost:7777]} response {}}


```

**Comment by undertow-pull-request** [comment]
**Linux** [Build 2691](https://ci.wildfly.org/viewLog.html?buildId=102634&buildTypeId=UT_MASTER_LINUX) outcome was **FAILURE** using a merge of bc06441e8922482d46d2f45bd36a66f55e2e19ab
Summary: Tests failed: 1 (1 new), passed: 3125, ignored: 612 Build time: 00:23:35
### Failed tests
```
io.undertow.servlet.test.session.CrossContextServletSessionTestCase.testSharedSessionCookieMultipleDeployments[proxy][https]: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:166)
	at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:90)
	at org.apache.http.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:281)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:92)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:61)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:254)
	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:289)
	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:252)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.receiveResponseHeader(ManagedClientConnectionImpl.java:191)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:300)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:127)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:715)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:520)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:906)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:805)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:784)
	at io.undertow.servlet.test.session.CrossContextServletSessionTestCase.testSharedSessionCookieMultipleDeployments(CrossContextServletSessionTestCase.java:129)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:503)
	at io.undertow.testutils.DefaultServer.runChild(DefaultServer.java:98)
	at io.undertow.testutils.DefaultServer.run(DefaultServer.java:276)
------- Stderr: -------
04:40:16,390 DEBUG (XNIO-1 I/O-6) [io.undertow.client.http.HttpClientExchange] <HttpClientExchange.java:87> request terminated for request to localhost/127.0.0.1:8888 /1/servlet
04:40:16,390 DEBUG (XNIO-1 task-26) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /1/servlet, authentication required: false
04:40:16,390 DEBUG (XNIO-1 task-26) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@15b4d68 for /1/servlet
04:40:16,391 DEBUG (XNIO-1 task-26) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /1/servlet
04:40:16,392 DEBUG (XNIO-1 I/O-6) [io.undertow.client.http.HttpClientExchange] <HttpClientExchange.java:103> response terminated for request to localhost/127.0.0.1:8888 /1/servlet
04:40:16,392 DEBUG (XNIO-1 I/O-6) [io.undertow.client.http.HttpClientConnection] <HttpClientConnection.java:475> exchange complete in connection to localhost/127.0.0.1:8888
04:40:16,393 DEBUG (XNIO-1 I/O-6) [io.undertow.client.http.HttpClientExchange] <HttpClientExchange.java:87> request terminated for request to localhost/127.0.0.1:8888 /1/servlet
04:40:16,394 DEBUG (XNIO-1 task-4) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /1/servlet, authentication required: false
04:40:16,394 DEBUG (XNIO-1 task-4) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@15b4d68 for /1/servlet
04:40:16,395 DEBUG (XNIO-1 task-4) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /1/servlet
04:40:16,395 DEBUG (XNIO-1 I/O-6) [io.undertow.client.http.HttpClientExchange] <HttpClientExchange.java:103> response terminated for request to localhost/127.0.0.1:8888 /1/servlet
04:40:16,395 DEBUG (XNIO-1 I/O-6) [io.undertow.client.http.HttpClientConnection] <HttpClientConnection.java:475> exchange complete in connection to localhost/127.0.0.1:8888
04:40:16,397 DEBUG (XNIO-1 I/O-6) [io.undertow.client.http.HttpClientExchange] <HttpClientExchange.java:87> request terminated for request to localhost/127.0.0.1:8888 /2/servlet
04:40:16,397 DEBUG (XNIO-1 task-5) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /2/servlet, authentication required: false
04:40:16,397 DEBUG (XNIO-1 task-5) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@ca60cb for /2/servlet
04:40:16,397 DEBUG (XNIO-1 task-5) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /2/servlet
04:40:16,398 DEBUG (XNIO-1 I/O-6) [io.undertow.client.http.HttpClientExchange] <HttpClientExchange.java:103> response terminated for request to localhost/127.0.0.1:8888 /2/servlet
04:40:16,399 DEBUG (XNIO-1 I/O-6) [io.undertow.client.http.HttpClientConnection] <HttpClientConnection.java:475> exchange complete in connection to localhost/127.0.0.1:8888
04:40:16,400 DEBUG (XNIO-1 I/O-6) [io.undertow.client.http.HttpClientExchange] <HttpClientExchange.java:87> request terminated for request to localhost/127.0.0.1:8888 /2/servlet
04:40:16,401 DEBUG (XNIO-1 task-2) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /2/servlet, authentication required: false
04:40:16,401 DEBUG (XNIO-1 task-2) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@ca60cb for /2/servlet
04:40:16,402 DEBUG (XNIO-1 task-2) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /2/servlet
04:40:16,402 DEBUG (XNIO-1 I/O-6) [io.undertow.client.http.HttpClientExchange] <HttpClientExchange.java:103> response terminated for request to localhost/127.0.0.1:8888 /2/servlet
04:40:16,403 DEBUG (XNIO-1 I/O-6) [io.undertow.client.http.HttpClientConnection] <HttpClientConnection.java:475> exchange complete in connection to localhost/127.0.0.1:8888
04:40:16,404 DEBUG (XNIO-1 I/O-6) [io.undertow.client.http.HttpClientExchange] <HttpClientExchange.java:87> request terminated for request to localhost/127.0.0.1:8888 /1/servlet


```

**Pull request merged**
