### PR TITLE
[UNDERTOW-1879] Utilize o.w.common.Assert class for Null-Checks

### PR DESCRIPTION
**Pull request by boris-unckel**
Fixes https://issues.redhat.com/browse/UNDERTOW-1879

### CODE REVIEW

**Comment by boris-unckel** [comment]
@ropalka @fl4via Could you please have a look at this? I don't think the failed checks are related, because other pulls fail with the same errors. Thanks in advance for any feedback or approval/merge.

**Comment by boris-unckel** [comment]
@fl4via Could you please give this PR a chance and review it? I have rebased the PR, now the CI is not available and the retest is open.

**Comment by boris-unckel** [comment]
Hello @fl4via could you review and approve this PR, please? It's rebased on master, tests passed.

**Review by ropalka — APPROVED** [review]

**Comment by fl4via** [comment]
@boris-unckel  and @ropalka , because of the changes in the dependency of module in Undertow in WF and this is a minor release, I'm reverting this change and we will submit it again for 2.3.0.Final after hearing back feedback from @bstansberry on the impact this will have in WF. Se more info here: https://issues.redhat.com/browse/UNDERTOW-1879?focusedCommentId=19344919&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-19344919

As soon as we have merged all PRs in the line, we will have a new policy where master does not contain minor releases anymore, and this will make life easier. For now, the only solution is reverting and resubmitting the PR. I appreciate your understanding @boris-unckel  and I also appreciate your contribution to the Undertow project!

**Pull request merged**
