### PR TITLE
change defaultEncoding value form 'ISO-8859-1' to 'UTF-8'

### PR DESCRIPTION
**Pull request by qiuxiaoj**
If Chinese characters are not displayed properly，when i try submit a form.

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1876](https://ci.wildfly.org/viewLog.html?buildId=14163&buildTypeId=UT_MASTER_LINUX) outcome was **FAILURE** using a merge of 814d2b158291d2e049a659b30b3801f3123b9a3b
Summary: Tests failed: 15 (15 new), passed: 2917, ignored: 507 Build time: 00:21:24
### Failed tests
```
io.undertow.server.handlers.ReceiverTestCase.testBlockingReceivePartialString{proxy}{http2}: java.lang.RuntimeException: test failed with i equal to 9
	at io.undertow.server.handlers.ReceiverTestCase.doTest(ReceiverTestCase.java:197)
	at io.undertow.server.handlers.ReceiverTestCase.testBlockingReceivePartialString(ReceiverTestCase.java:174)
Caused by: java.net.SocketTimeoutException: Read timed out
	at io.undertow.server.handlers.ReceiverTestCase.runTest(ReceiverTestCase.java:208)
	at io.undertow.server.handlers.ReceiverTestCase.doTest(ReceiverTestCase.java:195)
	at io.undertow.server.handlers.ReceiverTestCase.testBlockingReceivePartialString(ReceiverTestCase.java:174)java.lang.RuntimeException: Buffer Leak io.undertow.server.handlers.ReceiverTestCase.testBlockingReceivePartialString{proxy}{http2}
Caused by: java.lang.RuntimeException: java.nio.DirectByteBuffer[pos=0 lim=8192 cap=8192] NO: 178970 [NO_CONTEXT]
------- Stderr: -------
java.lang.RuntimeException: java.nio.DirectByteBuffer[pos=0 lim=8192 cap=8192] NO: 178970 [NO_CONTEXT]
	at io.undertow.testutils.DebuggingSlicePool$DebuggingBuffer.<init>(DebuggingSlicePool.java:67)
	at io.undertow.testutils.DebuggingSlicePool.allocate(DebuggingSlicePool.java:38)
	at io.undertow.server.protocol.framed.AbstractFramedStreamSinkChannel.write(AbstractFramedStreamSinkChannel.java:401)
	at io.undertow.util.Transfer$TransferListener.handleEvent(Transfer.java:188)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at io.undertow.server.protocol.framed.AbstractFramedStreamSinkChannel$1.run(AbstractFramedStreamSinkChannel.java:219)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$3.run(AbstractFramedChannel.java:232)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:580)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:464)java.lang.RuntimeException: Buffer Leak io.undertow.server.handlers.ReceiverTestCase.testBlockingReceivePartialString{proxy}{http2}
Caused by: java.lang.RuntimeException: java.nio.DirectByteBuffer[pos=0 lim=8192 cap=8192] NO: 178884 [NO_CONTEXT]
------- Stderr: -------
java.lang.RuntimeException: java.nio.DirectByteBuffer[pos=0 lim=8192 cap=8192] NO: 178884 [NO_CONTEXT]
	at io.undertow.testutils.DebuggingSlicePool$DebuggingBuffer.<init>(DebuggingSlicePool.java:67)
	at io.undertow.testutils.DebuggingSlicePool.allocate(DebuggingSlicePool.java:38)
	at io.undertow.util.Transfer.initiateTransfer(Transfer.java:57)
	at io.undertow.server.handlers.proxy.ProxyHandler$ProxyAction$1.completed(ProxyHandler.java:603)
	at io.undertow.server.handlers.proxy.ProxyHandler$ProxyAction$1.completed(ProxyHandler.java:522)
	at io.undertow.client.http2.Http2ClientConnection.sendRequest(Http2ClientConnection.java:187)
	at io.undertow.server.handlers.proxy.ProxyHandler$ProxyAction.run(ProxyHandler.java:522)
	at io.undertow.util.SameThreadExecutor.execute(SameThreadExecutor.java:35)
	at io.undertow.server.HttpServerExchange.dispatch(HttpServerExchange.java:777)
	at io.undertow.server.handlers.proxy.ProxyHandler$ProxyClientHandler.completed(ProxyHandler.java:285)
	at io.undertow.server.handlers.proxy.ProxyHandler$ProxyClientHandler.completed(ProxyHandler.java:261)
	at io.undertow.server.handlers.proxy.ProxyConnectionPool.connectionReady(ProxyConnectionPool.java:325)
	at io.undertow.server.handlers.proxy.ProxyConnectionPool.connect(ProxyConnectionPool.java:512)
	at io.undertow.server.handlers.proxy.LoadBalancingProxyClient.getConnection(LoadBalancingProxyClient.java:301)
	at io.undertow.server.handlers.proxy.ProxyHandler$ProxyClientHandler.run(ProxyHandler.java:279)
	at io.undertow.util.SameThreadExecutor.execute(SameThreadExecutor.java:35)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:215)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:233)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:131)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:57)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:559)java.lang.RuntimeException: Buffer Leak io.undertow.server.handlers.ReceiverTestCase.testBlockingReceivePartialString{proxy}{http2}
Caused by: java.lang.RuntimeException: java.nio.DirectByteBuffer[pos=0 lim=8192 cap=8192] NO: 178963 [NO_CONTEXT]
------- Stderr: -------
java.lang.RuntimeException: java.nio.DirectByteBuffer[pos=0 lim=8192 cap=8192] NO: 178963 [NO_CONTEXT]
	at io.undertow.testutils.DebuggingSlicePool$DebuggingBuffer.<init>(DebuggingSlicePool.java:67)
	at io.undertow.testutils.DebuggingSlicePool.allocate(DebuggingSlicePool.java:38)


io.undertow.servlet.test.response.contenttype.ContentTypeCharsetTestCase.testCharsetAndContentType: 	at io.undertow.servlet.test.response.contenttype.ContentTypeCharsetTestCase.runtest(ContentTypeCharsetTestCase.java:69)
	at io.undertow.servlet.test.response.contenttype.ContentTypeCharsetTestCase.testCharsetAndContentType(ContentTypeCharsetTestCase.java:53)


io.undertow.servlet.test.charset.UnmappableCharacterTestCase.testUnmappableCharacters: 	at io.undertow.servlet.test.charset.UnmappableCharacterTestCase.testUnmappableCharacters(UnmappableCharacterTestCase.java:59)
------- Stdout: -------
Received message: abcčšžgg


io.undertow.servlet.test.response.contenttype.ContentTypeCharsetTestCase.testCharsetAndContentType{proxy}: 	at io.undertow.servlet.test.response.contenttype.ContentTypeCharsetTestCase.runtest(ContentTypeCharsetTestCase.java:69)
	at io.undertow.servlet.test.response.contenttype.ContentTypeCharsetTestCase.testCharsetAndContentType(ContentTypeCharsetTestCase.java:53)


io.undertow.servlet.test.charset.UnmappableCharacterTestCase.testUnmappableCharacters{proxy}: 	at io.undertow.servlet.test.charset.UnmappableCharacterTestCase.testUnmappableCharacters(UnmappableCharacterTestCase.java:59)
------- Stdout: -------
Received message: abcčšžgg


io.undertow.servlet.test.response.contenttype.ContentTypeCharsetTestCase.testCharsetAndContentType{proxy}{ajp}: 	at io.undertow.servlet.test.response.contenttype.ContentTypeCharsetTestCase.runtest(ContentTypeCharsetTestCase.java:69)
	at io.undertow.servlet.test.response.contenttype.ContentTypeCharsetTestCase.testCharsetAndContentType(ContentTypeCharsetTestCase.java:53)


io.undertow.servlet.test.charset.UnmappableCharacterTestCase.testUnmappableCharacters{proxy}{ajp}: 	at io.undertow.servlet.test.charset.UnmappableCharacterTestCase.testUnmappableCharacters(UnmappableCharacterTestCase.java:59)
------- Stdout: -------
Received message: abcčšžgg


io.undertow.servlet.test.response.contenttype.ContentTypeCharsetTestCase.testCharsetAndContentType{proxy}{spdy}: 	at io.undertow.servlet.test.response.contenttype.ContentTypeCharsetTestCase.runtest(ContentTypeCharsetTestCase.java:69)
	at io.undertow.servlet.test.response.contenttype.ContentTypeCharsetTestCase.testCharsetAndContentType(ContentTypeCharsetTestCase.java:53)
------- Stderr: -------
o.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at io.undertow.protocols.ssl.SslConduit$SslReadReadyHandler.readReady(SslConduit.java:1116)
	at io.undertow.protocols.ssl.SslConduit$1.run(SslConduit.java:166)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:580)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:464)

18:48:19,040 ERROR (XNIO-1 I/O-8) [io.undertow.proxy] <ProxyHandler.java:673> UT005028: Proxy request to /servletContext/j_security_check failed: java.nio.channels.ClosedChannelException
	at io.undertow.client.spdy.SpdyClientConnection$SpdyReceiveListener.handleEvent(SpdyClientConnection.java:310)
	at io.undertow.client.spdy.SpdyClientConnection$SpdyReceiveListener.handleEvent(SpdyClientConnection.java:274)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:920)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:901)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at io.undertow.protocols.ssl.SslConduit$SslReadReadyHandler.readReady(SslConduit.java:1116)
	at io.undertow.protocols.ssl.SslConduit$1.run(SslConduit.java:166)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:580)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:464)

18:48:19,050 ERROR (XNIO-1 I/O-8) [io.undertow.proxy] <ProxyHandler.java:673> UT005028: Proxy request to /servletContext/blockingOutput failed: java.nio.channels.ClosedChannelException
	at io.undertow.client.spdy.SpdyClientConnection$SpdyReceiveListener.handleEvent(SpdyClientConnection.java:310)
	at io.undertow.client.spdy.SpdyClientConnection$SpdyReceiveListener.handleEvent(SpdyClientConnection.java:274)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:920)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:901)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at io.undertow.protocols.ssl.SslConduit$SslReadReadyHandler.readReady(SslConduit.java:1116)
	at io.undertow.protocols.ssl.SslConduit$1.run(SslConduit.java:166)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:580)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:464)

18:48:19,062 ERROR (XNIO-1 I/O-8) [io.undertow.proxy] <ProxyHandler.java:673> UT005028: Proxy request to /servletContext/blockingOutput failed: java.nio.channels.ClosedChannelException
	at io.undertow.client.spdy.SpdyClientConnection$SpdyReceiveListener.handleEvent(SpdyClientConnection.java:310)
	at io.undertow.client.spdy.SpdyClientConnection$SpdyReceiveListener.handleEvent(SpdyClientConnection.java:274)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:920)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:901)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at io.undertow.protocols.ssl.SslConduit$SslReadReadyHandler.readReady(SslConduit.java:1116)
	at io.undertow.protocols.ssl.SslConduit$1.run(SslConduit.java:166)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:580)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:464)

18:48:19,070 ERROR (XNIO-1 I/O-8) [io.undertow.proxy] <ProxyHandler.java:673> UT005028: Proxy request to /servletContext/blockingOutput failed: java.nio.channels.ClosedChannelException
	at io.undertow.client.spdy.SpdyClientConnection$SpdyReceiveListener.handleEvent(SpdyClientConnection.java:310)


io.undertow.servlet.test.charset.UnmappableCharacterTestCase.testUnmappableCharacters{proxy}{spdy}: 	at io.undertow.servlet.test.charset.UnmappableCharacterTestCase.testUnmappableCharacters(UnmappableCharacterTestCase.java:59)
------- Stdout: -------
Received message: abcčšžgg


io.undertow.servlet.test.response.contenttype.ContentTypeCharsetTestCase.testCharsetAndContentType{proxy}{https}: 	at io.undertow.servlet.test.response.contenttype.ContentTypeCharsetTestCase.runtest(ContentTypeCharsetTestCase.java:69)
	at io.undertow.servlet.test.response.contenttype.ContentTypeCharsetTestCase.testCharsetAndContentType(ContentTypeCharsetTestCase.java:53)


io.undertow.servlet.test.charset.UnmappableCharacterTestCase.testUnmappableCharacters{proxy}{https}: 	at io.undertow.servlet.test.charset.UnmappableCharacterTestCase.testUnmappableCharacters(UnmappableCharacterTestCase.java:59)
------- Stdout: -------
Received message: abcčšžgg



##### there are 5 more failed tests, see build details
```

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1599](https://ci.wildfly.org/viewLog.html?buildId=14164&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 814d2b158291d2e049a659b30b3801f3123b9a3b
Summary: Tests failed: 15 (15 new), passed: 2829, ignored: 595 Build time: 00:24:16
### Failed tests
```
io.undertow.server.handlers.proxy.LoadBalancingProxyHTTP2TestCase.testLoadShared{proxy}{spdy}: java.lang.AssertionError
------- Stdout: -------
{x-disable-push=[true], x-forwarded-server=[localhost], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], x-forwarded-proto=[http], x-forwarded-port=[8888], x-forwarded-for=[127.0.0.1], x-forwarded-host=[localhost], Host=[localhost:7777]}
{x-disable-push=[true], x-forwarded-server=[localhost], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], x-forwarded-proto=[http], x-forwarded-port=[8888], x-forwarded-for=[127.0.0.1], x-forwarded-host=[localhost], Host=[localhost:7777]}
{x-disable-push=[true], x-forwarded-server=[localhost], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], x-forwarded-proto=[http], x-forwarded-port=[8888], x-forwarded-for=[127.0.0.1], x-forwarded-host=[localhost], Host=[localhost:7777]}
{x-disable-push=[true], x-forwarded-server=[localhost], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], x-forwarded-proto=[http], x-forwarded-port=[8888], x-forwarded-for=[127.0.0.1], x-forwarded-host=[localhost], Host=[localhost:7777]}
{x-disable-push=[true], x-forwarded-server=[localhost], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], x-forwarded-proto=[http], x-forwarded-port=[8888], x-forwarded-for=[127.0.0.1], x-forwarded-host=[localhost], Host=[localhost:7777]}
{x-disable-push=[true], x-forwarded-server=[localhost], user-agent=[Apache-HttpClient/4.2.6 (java 1.5)], x-forwarded-proto=[http], x-forwarded-port=[8888], x-forwarded-for=[127.0.0.1], x-forwarded-host=[localhost], Host=[localhost:7777]}


io.undertow.servlet.test.response.contenttype.ContentTypeCharsetTestCase.testCharsetAndContentType: 	at io.undertow.servlet.test.response.contenttype.ContentTypeCharsetTestCase.runtest(ContentTypeCharsetTestCase.java:69)
	at io.undertow.servlet.test.response.contenttype.ContentTypeCharsetTestCase.testCharsetAndContentType(ContentTypeCharsetTestCase.java:53)


io.undertow.servlet.test.charset.UnmappableCharacterTestCase.testUnmappableCharacters: 	at io.undertow.servlet.test.charset.UnmappableCharacterTestCase.testUnmappableCharacters(UnmappableCharacterTestCase.java:59)
------- Stdout: -------
Received message: abc?šžgg


io.undertow.servlet.test.response.contenttype.ContentTypeCharsetTestCase.testCharsetAndContentType{proxy}: 	at io.undertow.servlet.test.response.contenttype.ContentTypeCharsetTestCase.runtest(ContentTypeCharsetTestCase.java:69)
	at io.undertow.servlet.test.response.contenttype.ContentTypeCharsetTestCase.testCharsetAndContentType(ContentTypeCharsetTestCase.java:53)


io.undertow.servlet.test.charset.UnmappableCharacterTestCase.testUnmappableCharacters{proxy}: 	at io.undertow.servlet.test.charset.UnmappableCharacterTestCase.testUnmappableCharacters(UnmappableCharacterTestCase.java:59)
------- Stdout: -------
Received message: abc?šžgg


io.undertow.servlet.test.response.contenttype.ContentTypeCharsetTestCase.testCharsetAndContentType{proxy}{ajp}: 	at io.undertow.servlet.test.response.contenttype.ContentTypeCharsetTestCase.runtest(ContentTypeCharsetTestCase.java:69)
	at io.undertow.servlet.test.response.contenttype.ContentTypeCharsetTestCase.testCharsetAndContentType(ContentTypeCharsetTestCase.java:53)


io.undertow.servlet.test.charset.UnmappableCharacterTestCase.testUnmappableCharacters{proxy}{ajp}: 	at io.undertow.servlet.test.charset.UnmappableCharacterTestCase.testUnmappableCharacters(UnmappableCharacterTestCase.java:59)
------- Stdout: -------
Received message: abc?šžgg


io.undertow.servlet.test.response.contenttype.ContentTypeCharsetTestCase.testCharsetAndContentType{proxy}{spdy}: 	at io.undertow.servlet.test.response.contenttype.ContentTypeCharsetTestCase.runtest(ContentTypeCharsetTestCase.java:69)
	at io.undertow.servlet.test.response.contenttype.ContentTypeCharsetTestCase.testCharsetAndContentType(ContentTypeCharsetTestCase.java:53)
------- Stderr: -------
116)
	at io.undertow.protocols.ssl.SslConduit$1.run(SslConduit.java:166)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:580)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:464)

02:52:23,560 ERROR (XNIO-1 I/O-6) [io.undertow.proxy] <ProxyHandler.java:673> UT005028: Proxy request to /servletContext/j_security_check failed: java.nio.channels.ClosedChannelException
	at io.undertow.client.spdy.SpdyClientConnection$SpdyReceiveListener.handleEvent(SpdyClientConnection.java:310)
	at io.undertow.client.spdy.SpdyClientConnection$SpdyReceiveListener.handleEvent(SpdyClientConnection.java:274)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:920)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:901)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at io.undertow.protocols.ssl.SslConduit$SslReadReadyHandler.readReady(SslConduit.java:1116)
	at io.undertow.protocols.ssl.SslConduit$1.run(SslConduit.java:166)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:580)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:464)

02:52:23,567 ERROR (XNIO-1 I/O-6) [io.undertow.proxy] <ProxyHandler.java:673> UT005028: Proxy request to /servletContext/asyncInput failed: java.nio.channels.ClosedChannelException
	at io.undertow.client.spdy.SpdyClientConnection$SpdyReceiveListener.handleEvent(SpdyClientConnection.java:310)
	at io.undertow.client.spdy.SpdyClientConnection$SpdyReceiveListener.handleEvent(SpdyClientConnection.java:274)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:920)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:901)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at io.undertow.protocols.ssl.SslConduit$SslReadReadyHandler.readReady(SslConduit.java:1116)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:559)

02:52:23,571 ERROR (XNIO-1 I/O-6) [io.undertow.proxy] <ProxyHandler.java:673> UT005028: Proxy request to /servletContext/resp failed: java.nio.channels.ClosedChannelException
	at io.undertow.client.spdy.SpdyClientConnection$SpdyReceiveListener.handleEvent(SpdyClientConnection.java:310)
	at io.undertow.client.spdy.SpdyClientConnection$SpdyReceiveListener.handleEvent(SpdyClientConnection.java:274)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:920)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:901)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at io.undertow.protocols.ssl.SslConduit$SslReadReadyHandler.readReady(SslConduit.java:1116)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:559)

02:52:23,578 ERROR (XNIO-1 I/O-6) [io.undertow.proxy] <ProxyHandler.java:673> UT005028: Proxy request to /servletContext/j_security_check failed: java.nio.channels.ClosedChannelException
	at io.undertow.client.spdy.SpdyClientConnection$SpdyReceiveListener.handleEvent(SpdyClientConnection.java:310)
	at io.undertow.client.spdy.SpdyClientConnection$SpdyReceiveListener.handleEvent(SpdyClientConnection.java:274)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:920)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:901)


io.undertow.servlet.test.charset.UnmappableCharacterTestCase.testUnmappableCharacters{proxy}{spdy}: 	at io.undertow.servlet.test.charset.UnmappableCharacterTestCase.testUnmappableCharacters(UnmappableCharacterTestCase.java:59)
------- Stdout: -------
Received message: abc?šžgg


io.undertow.servlet.test.response.contenttype.ContentTypeCharsetTestCase.testCharsetAndContentType{proxy}{https}: 	at io.undertow.servlet.test.response.contenttype.ContentTypeCharsetTestCase.runtest(ContentTypeCharsetTestCase.java:69)
	at io.undertow.servlet.test.response.contenttype.ContentTypeCharsetTestCase.testCharsetAndContentType(ContentTypeCharsetTestCase.java:53)


io.undertow.servlet.test.charset.UnmappableCharacterTestCase.testUnmappableCharacters{proxy}{https}: 	at io.undertow.servlet.test.charset.UnmappableCharacterTestCase.testUnmappableCharacters(UnmappableCharacterTestCase.java:59)
------- Stdout: -------
Received message: abc?šžgg



##### there are 5 more failed tests, see build details
```

**Comment by undertow-pull-request** [comment]
Can one of the admins verify this patch?

**Comment by stuartwdouglas** [comment]
Current default encoding is required by the spec.

**Pull request closed without merging**
