### PR TITLE
[UNDERTOW-462] Deprecate the AuthenticationMechanism handling on the SecurityContext interface.

### PR DESCRIPTION
**Pull request by darranl**
Instead add a specific interface for if Undertow AuthenticationMechanisms are supported.

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1186](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=55383&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of b46ac9ee0057082c7c59c8e2472dc006cda60082

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1467](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=55382&buildTypeId=UT_MASTER_LINUX) is now running using a merge of b46ac9ee0057082c7c59c8e2472dc006cda60082

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1186](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=55383&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of b46ac9ee0057082c7c59c8e2472dc006cda60082
Summary: Out of memory: Java heap space (new); tests failed: 18 (14 new), passed: 776, ignored: 155 Build time: 0:09:37
### Build problems:
Failed tests detected
Process exited with code 1
Out of memory: Java heap space

### Failed tests
```
io.undertow.websockets.core.protocol.WebSocket08ServerTest.testText{proxy}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxySPDYTestCase.testStickySessions{proxy}{spdy}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxySPDYTestCase.testLoadShared{proxy}{spdy}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxySPDYTestCase.testLoadSharedWithServerShutdown{proxy}{spdy}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxyHTTP2TestCase.testLoadSharedWithServerShutdown{proxy}{spdy}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxyHTTP2TestCase.testDuplicateHeaders{proxy}{spdy}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxyAJPTestCase.testStickySessions{proxy}{spdy}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxyAJPTestCase.testLoadShared{proxy}{spdy}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxyAJPTestCase.testLoadSharedWithServerShutdown{proxy}{spdy}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxyAJPTestCase.testDuplicateHeaders{proxy}{spdy}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancerConnectionPoolingTestCase: <no details avaliable>


##### there are 8 more failed tests, see build details
```

**Comment by undertow-pull-request** [comment]
**Linux** [Build 1467](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=55382&buildTypeId=UT_MASTER_LINUX) outcome was **FAILURE** using a merge of b46ac9ee0057082c7c59c8e2472dc006cda60082
Summary: Tests failed: 2 (2 new), passed: 2582, ignored: 298 Build time: 0:15:52
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.handlers.PredicatedHandlersProxyTestCase.testProxy{proxy}{spdy}: <no details avaliable>

io.undertow.server.handlers.file.FileHandlerStressTestCase.simpleFileStressTest{proxy}{https}: <no details avaliable>

```

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1187](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=55389&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of b46ac9ee0057082c7c59c8e2472dc006cda60082

**Comment by ctomc** [comment]
@stuartwdouglas the above windows run failed with OOM, we run testsuite with -Xmx512m
should we increase that or it maybe is memory leak?

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1187](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=55389&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of b46ac9ee0057082c7c59c8e2472dc006cda60082
Summary: Tests failed: 7 (5 new), passed: 2500, ignored: 375 Build time: 0:13:55
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testDigestSuccess{proxy}: <no details avaliable>

io.undertow.server.handlers.PredicatedHandlersProxyTestCase.testProxy{proxy}{spdy}: <no details avaliable>

io.undertow.server.security.DigestAuthenticationAuthTestCase.testDigestSuccess{proxy}{http2}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxyTestCase.testStickySessions{proxy}{http2-clear}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxyTestCase.testLoadShared{proxy}{http2-clear}: <no details avaliable>

io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testDigestSuccess: <no details avaliable>

io.undertow.websockets.jsr.test.stress.WebsocketStressTestCase.webSocketStressTestCase: <no details avaliable>

```

**Pull request merged**
