### PR TITLE
[UNDERTOW-1710] Update the Netty version to 4.1.50.Final

### PR DESCRIPTION
**Pull request by hyperxpro**
Update the Netty version to [4.1.50.Final](https://repo1.maven.org/maven2/io/netty/netty-all/4.1.50.Final/)
Jira: https://issues.redhat.com/browse/UNDERTOW-1710

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
<p>Hello, hyperxpro. I'm waiting for one of the admins to verify this patch with /ok-to-test in a comment.</p>

**Comment by fl4via** [comment]
This is ok to test

**Comment by hyperxpro** [comment]
Just wondering how tests failed. And it's asking for login to check logs. Can you let me know what went wrong?

**Comment by fl4via** [comment]
@hyperxpro  We have quite a few test failures that I need to fix and that are probably unrelated. You can always view the ci result as a guest login though.

**Comment by fl4via** [comment]
Thanks for your PR, @hyperxpro !

**Comment by hyperxpro** [comment]
:D

**Pull request merged**
