### PR TITLE
Avoid deprecated and ignored bufferSize for HttpOpenListener.

### PR DESCRIPTION
**Pull request by ecki**

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1052](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=48376&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 7185903996d5e7c05793e100f477c81a005ca529

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1052](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=48376&buildTypeId=UNDERTOW_MasterWindows) outcome was **SUCCESS** using a merge of 7185903996d5e7c05793e100f477c81a005ca529
Summary: Tests passed: 2490, ignored: 369 Build time: 0:13:36

**Comment by stuartwdouglas** [comment]
I ended up doing this as part of https://github.com/undertow-io/undertow/commit/040662f6694c1ea5e55a9764d2e752e1e94526c3

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1054](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=48384&buildTypeId=UNDERTOW_MasterWindows) is now running using a merge of 7185903996d5e7c05793e100f477c81a005ca529

**Comment by undertow-pull-request** [comment]
**Windows** [Build 1054](http://brontes.lab.eng.brq.redhat.com/viewLog.html?buildId=48384&buildTypeId=UNDERTOW_MasterWindows) outcome was **FAILURE** using a merge of 7185903996d5e7c05793e100f477c81a005ca529
Summary: Tests failed: 64 (64 new), passed: 2428, ignored: 365 Build time: 0:27:18
### Build problems:
Failed tests detected

### Failed tests
```
io.undertow.server.security.SpnegoDigestAuthenticationTestCase.testDigestSuccess{proxy}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxyHTTP2ViaUpgradeTestCase.testHeadersAreLowercase{proxy}{spdy}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxyHTTP2ViaUpgradeTestCase.testLoadShared{proxy}{spdy}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxyHTTP2ViaUpgradeTestCase.testLoadSharedWithServerShutdown{proxy}{spdy}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxyHTTP2TestCase.testHeadersAreLowercase{proxy}{http2}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxyHTTP2TestCase.testLoadShared{proxy}{http2}: <no details avaliable>

io.undertow.server.handlers.proxy.LoadBalancingProxyHTTP2TestCase.testLoadSharedWithServerShutdown{proxy}{http2}: <no details avaliable>

io.undertow.server.handlers.encoding.DeflateContentEncodingTestCase.testDeflateEncodingBigResponse{proxy}{http2}: <no details avaliable>

io.undertow.server.handlers.encoding.DeflateContentEncodingTestCase.testDeflateEncoding{proxy}{http2}: <no details avaliable>

io.undertow.server.handlers.caching.CacheHandlerTestCase.testBasicPathBasedCaching{proxy}{http2}: <no details avaliable>

io.undertow.server.handlers.blocking.SimpleBlockingServerTestCase.testHeadRequests{proxy}{http2}: <no details avaliable>


##### there are 54 more failed tests, see build details
```

**Pull request closed without merging**
