### PR TITLE
UNDERTOW-1230 Fix for Http2ClientConnection overwrites existing X_FORWARDED_FOR header

### PR DESCRIPTION
**Pull request by majk1**

### CODE REVIEW

**Comment by undertow-pull-request** [comment]
Can one of the admins verify this patch?

**Comment by stuartwdouglas** [comment]
This is ok to test

**Comment by undertow-pull-request** [comment]
**Linux** [Build 517](https://ci.wildfly.org/viewLog.html?buildId=79533&buildTypeId=UNDERTOW_14xLinux) outcome was **FAILURE** using a merge of a922faecf00b415623eaab57fb132e4059bfa726
Summary: Tests failed: 3, passed: 3044, ignored: 565 Build time: 00:21:10
### Failed tests
```
io.undertow.servlet.test.multipart.MultiPartTestCase.testMultiPartRequestToLarge[proxy][ajp]: 	at io.undertow.servlet.test.multipart.MultiPartTestCase.testMultiPartRequestToLarge(MultiPartTestCase.java:187)
------- Stderr: -------
22:38:31,809 DEBUG (XNIO-1 task-8) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/2, authentication required: false
22:38:31,810 DEBUG (XNIO-1 task-8) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@fe5b26 for /servletContext/2
22:38:31,810 DEBUG (XNIO-1 task-8) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/2
22:38:31,811 ERROR (XNIO-1 I/O-4) [io.undertow.proxy] <ProxyHandler.java:660> UT005028: Proxy request to /servletContext/2 failed: java.nio.channels.ClosedChannelException
	at io.undertow.client.ajp.AjpClientConnection$ClientReceiveListener.handleEvent(AjpClientConnection.java:347)
	at io.undertow.client.ajp.AjpClientConnection$ClientReceiveListener.handleEvent(AjpClientConnection.java:339)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:921)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:902)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:561)

22:38:31,812 DEBUG (XNIO-1 I/O-4) [io.undertow.client.ajp.AjpClientConnection] <AjpClientConnection.java:115> connection to localhost/127.0.0.1:8888 closed


io.undertow.servlet.test.multipart.MultiPartTestCase.testMultiPartRequestToLarge[proxy][http2]: 	at io.undertow.servlet.test.multipart.MultiPartTestCase.testMultiPartRequestToLarge(MultiPartTestCase.java:187)
------- Stderr: -------
22:42:29,472 DEBUG (XNIO-1 task-22) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/2, authentication required: false
22:42:29,473 DEBUG (XNIO-1 task-22) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@1b60c54 for /servletContext/2
22:42:29,473 ERROR (XNIO-1 I/O-4) [io.undertow.proxy] <ProxyHandler.java:660> UT005028: Proxy request to /servletContext/2 failed: java.io.IOException: UT000103: Http2 stream was reset
	at io.undertow.client.http2.Http2ClientConnection$Http2ReceiveListener.handleEvent(Http2ClientConnection.java:416)
	at io.undertow.client.http2.Http2ClientConnection$Http2ReceiveListener.handleEvent(Http2ClientConnection.java:357)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:921)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:902)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at io.undertow.protocols.ssl.SslConduit$SslReadReadyHandler.readReady(SslConduit.java:1145)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:561)

22:42:29,473 DEBUG (XNIO-1 task-22) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/2


io.undertow.servlet.test.multipart.MultiPartTestCase.testMultiPartRequestToLarge[proxy][http2-clear-upgrade]: 	at io.undertow.servlet.test.multipart.MultiPartTestCase.testMultiPartRequestToLarge(MultiPartTestCase.java:187)
------- Stderr: -------
22:43:42,799 DEBUG (XNIO-1 task-7) [io.undertow.request.security] <SecurityContextImpl.java:86> Attempting to authenticate /servletContext/2, authentication required: false
22:43:42,800 DEBUG (XNIO-1 task-7) [io.undertow.request.security] <SecurityContextImpl.java:247> Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@1030bea for /servletContext/2
22:43:42,800 ERROR (XNIO-1 I/O-2) [io.undertow.proxy] <ProxyHandler.java:660> UT005028: Proxy request to /servletContext/2 failed: java.io.IOException: UT000103: Http2 stream was reset
	at io.undertow.client.http2.Http2ClientConnection$Http2ReceiveListener.handleEvent(Http2ClientConnection.java:416)
	at io.undertow.client.http2.Http2ClientConnection$Http2ReceiveListener.handleEvent(Http2ClientConnection.java:357)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:921)
	at io.undertow.server.protocol.framed.AbstractFramedChannel$FrameReadListener.handleEvent(AbstractFramedChannel.java:902)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:88)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:561)

22:43:42,800 DEBUG (XNIO-1 task-7) [io.undertow.request.security] <SecurityContextImpl.java:110> Authentication result was ATTEMPTED for /servletContext/2


```

**Comment by stuartwdouglas** [comment]
Thinking about it I don't think this code should actually be here, I have just removed it.

**Pull request closed without merging**
